-- Migración #07 — limpieza de nombres de TODO el menú (productos + opciones).
-- Title-case, sin emojis, tamaños normalizados, typos corregidos, dedupe.
-- Reversible: snapshots _pre07 (07_rollback.sql).
begin;
create table if not exists _bak_products_pre07 as select id,name from products;
create table if not exists _bak_modopts_pre07  as select id,name,is_active from modifier_options;
-- PRODUCTOS
update products set name='Chai Latte Vainilla' where id=1;
update products set name='Chai Miel' where id=2;
update products set name='Tea''s' where id=3;
update products set name='Café Americano' where id=4;
update products set name='Capuccino' where id=5;
update products set name='Caramel Latte Macchiato' where id=6;
update products set name='Chai Latte' where id=7;
update products set name='Chococino' where id=8;
update products set name='Chocolate Blanco 16 oz' where id=9;
update products set name='Chocolate Caliente 16 oz' where id=10;
update products set name='Chocolate Oaxaca 16 oz' where id=11;
update products set name='Latte 12 oz' where id=12;
update products set name='Latte Macchiato' where id=13;
update products set name='Moka (Mocha)' where id=14;
update products set name='Frutos Rojos Té''s' where id=15;
update products set name='Chocolate Frío' where id=16;
update products set name='Agua de Mango - Litro' where id=22;
update products set name='Americano Black - Mcnulty' where id=23;
update products set name='Americano Sweet - Mcnulty' where id=24;
update products set name='Bong Bong Bebida' where id=25;
update products set name='Café Cappuccino - OKF 240 ml' where id=26;
update products set name='Café Latte - OKF 240 ml' where id=27;
update products set name='Café Macchiato Caramel - OKF 240 ml' where id=28;
update products set name='Café Mocha (Moka) - OKF 240 ml' where id=29;
update products set name='Cantabile Café Vainilla Americano - 230ml' where id=30;
update products set name='Cantabile Fresa - 230ml' where id=31;
update products set name='Cantabile Granada - 230ml' where id=32;
update products set name='Cantabile Mango (Doble Mango) - 230ml' where id=33;
update products set name='Cantabile Manzana - 230ml' where id=34;
update products set name='Cantabile Mora Azul - 230ml' where id=35;
update products set name='Cantabile Naranja - 230ml' where id=36;
update products set name='Cantabile Sandía - 230ml' where id=37;
update products set name='Cantabile Té Helado Durazno - 230ml' where id=38;
update products set name='Cantabile Uva Verde - 230ml' where id=39;
update products set name='Chupa Chups Bebida Fresa' where id=41;
update products set name='Chupa Chups Bebida Mango' where id=42;
update products set name='Chupa Chups Bebida Melón Cremosa' where id=43;
update products set name='Chupa Chups Bebida Naranja' where id=44;
update products set name='Chupa Chups Bebida Raspberry (Frambuesa)' where id=45;
update products set name='Chupa Chups Bebida Uva' where id=46;
update products set name='Combo Soju Milki' where id=47;
update products set name='Cool Mojito - Pure Plus 500ml' where id=48;
update products set name='Cool Piña Colada - Pure Plus 500 ml' where id=49;
update products set name='Frais Jus Hallabong' where id=52;
update products set name='Frais Jus Mango' where id=53;
update products set name='Frais Jus Piña' where id=54;
update products set name='Haitai Bong Bong Uva 238ml' where id=56;
update products set name='Haitai Coco Palm Mango 340ml' where id=57;
update products set name='Haitai Pera' where id=58;
update products set name='Hata Mora Azul' where id=59;
update products set name='Hazelnut - Mcnulty' where id=60;
update products set name='Ice Talk Blue Lemon' where id=61;
update products set name='Ice Talk Durazno' where id=62;
update products set name='Ice Talk Sandia' where id=63;
update products set name='Let''s Be Café' where id=64;
update products set name='Let''s Be Capuccino - Lotte 240ml' where id=65;
update products set name='Milkis' where id=66;
update products set name='Milkis Durazno 250 ml' where id=67;
update products set name='Milkis Fresa 250 ml' where id=68;
update products set name='Milkis Manzana 250 ml' where id=69;
update products set name='Milkis Melón 250 ml' where id=70;
update products set name='Milkis Original 250 ml' where id=71;
update products set name='Paldo Bts Cold Brew Americano' where id=72;
update products set name='Ponche de Arroz - Paldo Shikhye' where id=73;
update products set name='Ramine Limon' where id=74;
update products set name='Ramune Fresa' where id=76;
update products set name='Ramune Limon' where id=77;
update products set name='Ramune Lychee' where id=78;
update products set name='Ramune Melon' where id=79;
update products set name='Ramune Mora Azul' where id=80;
update products set name='Ramune Naranja' where id=81;
update products set name='Ramune Original' where id=82;
update products set name='Ramune Uva' where id=83;
update products set name='Soda Coreana' where id=84;
update products set name='Soju Americano' where id=85;
update products set name='Soju Blue Berry (Mora Azul)' where id=86;
update products set name='Soju Citron' where id=87;
update products set name='Soju Durazno' where id=88;
update products set name='Soju Fresa' where id=89;
update products set name='Soju Mandarina' where id=90;
update products set name='Soju Mango' where id=91;
update products set name='Soju Manzana' where id=92;
update products set name='Soju Manzana Verde' where id=93;
update products set name='Soju Original' where id=94;
update products set name='Soju Saero' where id=95;
update products set name='Soju Uva' where id=96;
update products set name='Soju Yogurt' where id=97;
update products set name='Hard The Kitten' where id=98;
update products set name='Lilac Purr Latte' where id=99;
update products set name='Red The Flavor Velvet' where id=100;
update products set name='Ring Ding Dong' where id=101;
update products set name='Soda Coreana Cantabile' where id=102;
update products set name='Twice Tastic Kitty' where id=103;
update products set name='Bobah Tea Agua' where id=105;
update products set name='Chai Latte Caliente' where id=113;
update products set name='Leche Deslactosada Light Bobah Tea' where id=114;
update products set name='Matcha Coco' where id=115;
update products set name='Promo Bobah G 2x100' where id=116;
update products set name='Ice Coffee' where id=117;
update products set name='Ice Coffe' where id=118;
update products set name='Ice Coffe (Café Frío)' where id=119;
update products set name='Chamoyada Pelon' where id=123;
update products set name='Chococereza Frappé' where id=125;
update products set name='Dragon Fruit' where id=126;
update products set name='Frappe Magnum' where id=129;
update products set name='Frappe Mordisco' where id=130;
update products set name='Fresa - Chamoyada' where id=131;
update products set name='Cereza - Chamoyada' where id=159;
update products set name='Cham de Tamarindo' where id=160;
update products set name='Chamoyada' where id=161;
update products set name='Frappé de Agua Granizado' where id=162;
update products set name='Fresa Sandía - Chamoyada' where id=163;
update products set name='Frutos Rojos - Chamoyada' where id=164;
update products set name='Granizado Guayaba' where id=165;
update products set name='Granizado Tamarindo' where id=166;
update products set name='Kiwi - Frappé de Agua' where id=167;
update products set name='Limón - Chamoyada' where id=168;
update products set name='Limón - Frappé de Agua' where id=169;
update products set name='Mandarina - Granizado' where id=170;
update products set name='Maracuyá - Chamoyada' where id=171;
update products set name='Mojito - Chamoyada' where id=172;
update products set name='Mora Azul - Chamoyada' where id=173;
update products set name='Pepino Limón - Chamoyada' where id=174;
update products set name='Piña Colada Granizado' where id=175;
update products set name='Pink Lemonade - Chamoyada' where id=176;
update products set name='Sandía - Chamoyada' where id=177;
update products set name='Smoothie Frutos Rojos' where id=178;
update products set name='Chilate' where id=179;
update products set name='Chocobana Licuados' where id=180;
update products set name='Chocolate Licuados' where id=181;
update products set name='Fresa Cremosa Licuados' where id=182;
update products set name='Leche Deslactosada Light' where id=183;
update products set name='Licuado Gatuno' where id=184;
update products set name='Malteada Gatuna' where id=185;
update products set name='Smoothie' where id=186;
update products set name='Smoothie Fresa' where id=187;
update products set name='Smoothie Mango' where id=188;
update products set name='Vainibanana Licuados' where id=189;
update products set name='Vainilla Licuados' where id=190;
update products set name='Amore Mio - Mojito' where id=195;
update products set name='Blue Butterfly - Mojito' where id=196;
update products set name='Dalgi - Mojito' where id=197;
update products set name='Mango Go - Mojito' where id=198;
update products set name='Arizona' where id=199;
update products set name='Arizona 591 ml' where id=200;
update products set name='Cocacola' where id=201;
update products set name='Coca Cola 355ml' where id=202;
update products set name='Coca Cola 600 ml' where id=203;
update products set name='Jarritos Lata 355ml' where id=204;
update products set name='Manzanita Deliciosa Mini' where id=205;
update products set name='Sangria 400ml' where id=206;
update products set name='Chamoy' where id=207;
update products set name='Durazno - Sodas Explosivas' where id=208;
update products set name='Frutos Rojos' where id=209;
update products set name='Perlas Chamoy' where id=210;
update products set name='Soda Explosiva' where id=211;
update products set name='Alitas CH - 250g' where id=212;
update products set name='Alitas G - 500g' where id=213;
update products set name='Alitas J - 1 kg' where id=214;
update products set name='Alitas Lemon Pepper 270gr' where id=215;
update products set name='Alitas M - 370g' where id=216;
update products set name='Boneless CH - 250g' where id=217;
update products set name='Boneless G - 500g' where id=218;
update products set name='Boneless J - 1 kg' where id=219;
update products set name='Boneless M - 370g' where id=220;
update products set name='Combo Alitas Gato Friend Zone (250gr)' where id=221;
update products set name='Combo Alitas Gato Mimado (500gr)' where id=222;
update products set name='Combo Boneless Gato Friend Zone (250gr)' where id=223;
update products set name='Combo Boneless Gato Mimado (500gr)' where id=224;
update products set name='Dedos de Queso (8pz)' where id=226;
update products set name='Tenders 5 pz' where id=227;
update products set name='BBQ a la Diabla Salsa G' where id=228;
update products set name='Boneless Lemon Pepper CH' where id=229;
update products set name='Boneless Lemon Pepper G' where id=230;
update products set name='Catsup sin Azúcar' where id=231;
update products set name='Mango Habanero x2 Salsa CH' where id=232;
update products set name='Mango Habanero x2 Salsa G' where id=233;
update products set name='Pelonrico Gatuno Salsa CH' where id=235;
update products set name='Pelonrico Gatuno Salsa G' where id=236;
update products set name='Piña Guajillo' where id=237;
update products set name='Sazonador Fuego' where id=239;
update products set name='Combo Corean' where id=240;
update products set name='Combo Curry y Cafe OKF' where id=241;
update products set name='Duo Chilate' where id=242;
update products set name='Duo Frappé' where id=243;
update products set name='Combinada' where id=246;
update products set name='Queso' where id=247;
update products set name='Test Ramen Preparado' where id=248;
update products set name='Tteokbokki Preparado' where id=249;
update products set name='Buldak Carbonara' where id=250;
update products set name='Buldak Rose' where id=251;
update products set name='Buldak Swicy' where id=252;
update products set name='Bulkdak Taco' where id=253;
update products set name='Compagguetti' where id=254;
update products set name='Cream Carbonara' where id=255;
update products set name='Hot Chicken 3X' where id=256;
update products set name='Mama Ok Carbonara Flavor' where id=258;
update products set name='Maruchan Queso' where id=259;
update products set name='Nomgshim Soon Veggie' where id=260;
update products set name='Ottogi Odongtong Myon' where id=261;
update products set name='Paldo Kokomen' where id=262;
update products set name='Preparado Llevar' where id=263;
update products set name='Ramen Buldak Swicy' where id=264;
update products set name='Ramen Carbonara - Buldak' where id=265;
update products set name='Ramen Carbonara Volcano - Paldo' where id=266;
update products set name='Ramen Chapagetti - Nongshim' where id=268;
update products set name='Ramen Cheese - Ottogi' where id=269;
update products set name='Ramen Cream Carbonara - Buldak' where id=271;
update products set name='Ramen Curry - Buldak' where id=272;
update products set name='Ramen Habanero Limon- Buldak' where id=273;
update products set name='Ramen Habanero Limon - Buldak' where id=274;
update products set name='Ramen Habanero Limón - Buldak' where id=275;
update products set name='Ramen Hot Chicken 2X' where id=277;
update products set name='Ramen Hot Chicken 2X - Buldak' where id=278;
update products set name='Ramen Hot Chicken 3X' where id=279;
update products set name='Ramen Hot Chicken 3X - Buldak' where id=280;
update products set name='Ramen Hot Chicken - Buldak' where id=281;
update products set name='Ramen Hot Chicken Cheese - Buldak' where id=283;
update products set name='Ramen Hot Pepper - Buldak' where id=284;
update products set name='Ramen Jin - Ottogi' where id=285;
update products set name='Ramen Jin Spicy - Ottogi' where id=286;
update products set name='Ramen Jjajang - Buldak' where id=287;
update products set name='Ramen Kimchi - Buldak' where id=289;
update products set name='Ramen Kimchi - Ottogi' where id=290;
update products set name='Ramen Kimchi - Paldo' where id=291;
update products set name='Ramen Kimchi - Samyang' where id=292;
update products set name='Ramen Lovely Hot Chicken - Buldak' where id=294;
update products set name='Ramen Pollo - Otoki' where id=295;
update products set name='Ramen Quattro Cheese - Buldak' where id=296;
update products set name='Ramen Rosé - Buldak' where id=300;
update products set name='Ramen Samyang Original - Samyang' where id=301;
update products set name='Ramen Samyang Tom Yumy- Buldak' where id=302;
update products set name='Ramen Shin Kimchi - Nongshim' where id=303;
update products set name='Ramen Shin Ramyun - Nongshim' where id=305;
update products set name='Ramen Tomato Hot Chicken - Buldak' where id=306;
update products set name='Ramen Yakisoba Hot Chicken -buldak' where id=310;
update products set name='Samyang Hot Pepper' where id=312;
update products set name='Shin Ramen Toomba' where id=314;
update products set name='Shin Ramyun Toomba' where id=315;
update products set name='Tomato Hot Chicken' where id=316;
update products set name='Tteokbokki Buldak - Original' where id=317;
update products set name='Tteokbokki Cj Bibigo - 125 g Hot & Spicy' where id=318;
update products set name='Tteokbokki Cj Bibigo - 125 g Sweet & Spicy' where id=319;
update products set name='Tteokbokki Cj Bibigo - 360 g Hot & Spicy' where id=320;
update products set name='Tteokbokki Cj Bibigo - 360 g Sweet & Spicy' where id=321;
update products set name='Udon' where id=322;
update products set name='Yaklsoba Hot Chicken' where id=323;
update products set name='Conejito Turin Crepa' where id=326;
update products set name='Crepa Champiñones' where id=327;
update products set name='Crepa Hawaiana' where id=328;
update products set name='Crepizza Hawaiana' where id=329;
update products set name='Crepizza Pepperoni' where id=330;
update products set name='Ferrero Crepa' where id=331;
update products set name='Gansito Crepa' where id=332;
update products set name='Kinder Bueno - Crepa' where id=333;
update products set name='Kinder Delice - Crepa' where id=334;
update products set name='Kit Kat Crepa' where id=335;
update products set name='Almendras - Decoración Crepa' where id=336;
update products set name='¡arma la Tuya!' where id=337;
update products set name='Cajeta - Crepa' where id=338;
update products set name='Chocobanana' where id=339;
update products set name='Crema Batida - Crepa' where id=340;
update products set name='Crema Pastelera - Creppa' where id=341;
update products set name='Crepa 2 Ingredientes' where id=342;
update products set name='Crepa Dulce' where id=344;
update products set name='Crepa- Dulce' where id=345;
update products set name='Crepa Dulce 1 Ingrediente' where id=346;
update products set name='Crepa Dulce 3 Ingredientes' where id=347;
update products set name='Crepa Salada' where id=349;
update products set name='Helado Cookies & Cream' where id=350;
update products set name='Helado de Chocolate' where id=351;
update products set name='Helado de Fresa' where id=352;
update products set name='Helado de Vainilla' where id=353;
update products set name='Lechera - Crepa' where id=354;
update products set name='Mapple - Crepa' where id=355;
update products set name='Mermelada Fresa - Crepa' where id=356;
update products set name='Miel Maple' where id=357;
update products set name='Nutella - Crepaa' where id=358;
update products set name='Philadelphia Crepa' where id=359;
update products set name='Philadelphia - Crepa' where id=360;
update products set name='Philadelphia / Nutella' where id=361;
update products set name='Bowl Frutl del Dia' where id=362;
update products set name='Bowl Griego Frutal' where id=363;
update products set name='Café S' where id=364;
update products set name='Chilaq Rojo Chico' where id=365;
update products set name='Chilaq Rojos Grandes' where id=366;
update products set name='Chilaquiles' where id=367;
update products set name='Chilaq Verde Chicos' where id=368;
update products set name='Chilaq Verdes Grandes' where id=369;
update products set name='Cuernito Dulce' where id=370;
update products set name='Cuernito Salado' where id=371;
update products set name='Hotcakes 2pz' where id=372;
update products set name='Sandwich 3 Quesos' where id=373;
update products set name='Sandwich Jamón' where id=374;
update products set name='Sincronizadas 3pz' where id=375;
update products set name='Aderezo de Queso CH' where id=383;
update products set name='Blue Cheese Aderezo G' where id=384;
update products set name='Camisa L' where id=385;
update products set name='Camisa XL' where id=386;
update products set name='Dedos de Queso 8 pza' where id=387;
update products set name='Dedos de Queso Pza' where id=388;
update products set name='Envio' where id=389;
update products set name='Lunetas - Toppings Crepa' where id=390;
update products set name='Mostaza Miel Aderezo G' where id=391;
update products set name='Mostaza Miel Aderezo M' where id=392;
update products set name='Papas a la Francesa (170g)' where id=393;
update products set name='+ Papas a la Francesa CH' where id=394;
update products set name='+ Papas a la Francesa M' where id=395;
update products set name='Papas F CH (130g)' where id=396;
update products set name='Papas F G (380g)' where id=397;
update products set name='Papas F J (500g)' where id=398;
update products set name='Papas F M (250g)' where id=399;
update products set name='Sazonador Papas' where id=400;
update products set name='Granillo Halloween' where id=401;
update products set name='Chuleta Ahumanda' where id=404;
update products set name='Chocobanana 3 Ingredientes' where id=416;
update products set name='Chocolate Blanco Caliente' where id=419;
update products set name='Chocolate Oaxaca Caliente' where id=421;
update products set name='Perlas de Yogurt' where id=424;
update products set name='Perlas Explosivas Chocolate' where id=426;
update products set name='Zarza Cremosa - Ingrediente Extra Frappé' where id=435;
update products set name='Pastel Indiv Triple Choco - Bellini' where id=436;
update products set name='Banderilla Coreana' where id=437;
update products set name='Blueberry - Pocky 40g' where id=438;
update products set name='Bubble Gum Cola' where id=440;
update products set name='Bubble Gum Durazno' where id=441;
update products set name='Bubble Gum Mango' where id=442;
update products set name='Bubble Gum Uva' where id=443;
update products set name='Cacahuates Japoneses' where id=444;
update products set name='Cajeta Mini Donas 8pz' where id=445;
update products set name='Chocolate Mini Donas 14pz' where id=446;
update products set name='Chocolate - Pocky 40g' where id=447;
update products set name='Dedos de Queso 3 pza' where id=448;
update products set name='Donitas Gatunas 14pza' where id=449;
update products set name='Donitas Gatunas 8pza' where id=450;
update products set name='Flaming. 1' where id=451;
update products set name='Galletas Crown Leche - Crown 77g' where id=452;
update products set name='Gomitas Uva - Orion' where id=453;
update products set name='Jalapeño Relleno 8pza' where id=454;
update products set name='Jalapeño Rellenos 3pz' where id=455;
update products set name='Maruchan' where id=456;
update products set name='Mini Pizza - 4 Quesos' where id=458;
update products set name='Mini Pizza Pepperoni' where id=459;
update products set name='Mini Pizza - Pepperoni' where id=460;
update products set name='Mini Pizza - _pepperoni' where id=461;
update products set name='Mochi Chocolate 180g' where id=462;
update products set name='Mochi Durazno - Royal Family' where id=463;
update products set name='Mochi Frambuesa - Royal F' where id=464;
update products set name='Mochi Fresa - Royal' where id=465;
update products set name='Mochi Mango 132g - Royal Family' where id=467;
update products set name='Mochi Natilla Limon - Royal' where id=468;
update products set name='Mochi Pay de Queso 180g' where id=469;
update products set name='Mochi Tiramisuo 180g' where id=470;
update products set name='Mochi Vainilla 120g' where id=471;
update products set name='Mochi Vainilla 180g' where id=472;
update products set name='Munchers - Palomitas de Papa - 12 pza' where id=473;
update products set name='Munchers - Palomitas de Papa - 6 pza' where id=474;
update products set name='Original Pepero' where id=475;
update products set name='Papas Fritas' where id=476;
update products set name='Papas Fritas - Corte Curly 170g' where id=477;
update products set name='Papas Fritas - Corte Curly 280g' where id=478;
update products set name='Papas Fritas - Corte Curly 350g' where id=479;
update products set name='Papas Fritas - Corte Curly 500g' where id=480;
update products set name='Papas Fritas - Corte Delgado 120g' where id=481;
update products set name='Papas Fritas - Corte Delgado 170g' where id=482;
update products set name='Papas Fritas - Corte Delgado 280g' where id=483;
update products set name='Papas Fritas - Corte Delgado 350g' where id=484;
update products set name='Papas Fritas - Corte Delgado 500g' where id=485;
update products set name='Papas Fritas - Corte Gajo 170g' where id=486;
update products set name='Papas Fritas - Corte Gajo 270g' where id=487;
update products set name='Papas Fritas - Corte Gajo 380g' where id=488;
update products set name='Papas Fritas - Corte Gajo 500g' where id=489;
update products set name='Papas Fritas - Corte Recto - CH (170g)' where id=490;
update products set name='Papas Fritas - Corte Recto G (350g)' where id=491;
update products set name='Papas Fritas - Corte Recto J (500g)' where id=492;
update products set name='Papas Fritas - Corte Recto M (270g)' where id=493;
update products set name='Papas Locas' where id=494;
update products set name='Pizza M - Hawaiana' where id=495;
update products set name='Pizza M - Pepperoni' where id=496;
update products set name='Ramen Panko' where id=497;
update products set name='Rebanada Cheesecake' where id=498;
update products set name='Strawberry - Pocky 40g' where id=499;
update products set name='Yous Puyagi Jellys Uva' where id=500;
update products set name='Youus Puyangi Original' where id=501;
-- OPCIONES
update modifier_options set name='Blue Cheese' where id=1;
update modifier_options set name='Ranch Cremoso' where id=2;
update modifier_options set name='Ranch Habanero' where id=3;
update modifier_options set name='Ranch Cremoso' where id=4;
update modifier_options set is_active=false where id=5; -- dup 'Ranch Cremoso'
update modifier_options set name='Ranch Habanero' where id=6;
update modifier_options set is_active=false where id=7; -- dup 'Ranch Habanero'
update modifier_options set name='Con Crema Batida' where id=8;
update modifier_options set name='Sin Crema Batida' where id=9;
update modifier_options set name='Coca Cola 355ml' where id=10;
update modifier_options set name='Sangria 400ml' where id=11;
update modifier_options set name='Coca Cola 355ml' where id=12;
update modifier_options set name='Sangria 400ml' where id=13;
update modifier_options set name='Flaming. 1' where id=14;
update modifier_options set name='Ramen Panko' where id=15;
update modifier_options set name='Papas a la Francesa Ind (170gr)' where id=16;
update modifier_options set name='Combinada' where id=17;
update modifier_options set name='Queso' where id=18;
update modifier_options set name='Banderilla Coreana' where id=19;
update modifier_options set name='Queso' where id=20;
update modifier_options set name='Crepa Champiñones' where id=21;
update modifier_options set name='Crepa Hawaiana' where id=22;
update modifier_options set name='Crepizza Hawaiana' where id=23;
update modifier_options set name='Crepizza Pepperoni' where id=24;
update modifier_options set name='Almendras - Decoración Crepa' where id=25;
update modifier_options set name='Azúcar Glass - Decoración Crepa' where id=26;
update modifier_options set name='Canela - Decoración Crepa' where id=27;
update modifier_options set name='Chispas de Chocolate - Decoración Crepa' where id=28;
update modifier_options set name='Chocomentas - Decoración Crepa' where id=29;
update modifier_options set name='Granillo Capuccino - Decoración Crepa' where id=30;
update modifier_options set name='Granillo Chocolate - Decoración Crepa' where id=31;
update modifier_options set name='Granillo Fresa - Decoración Crepa' where id=32;
update modifier_options set name='Lunetas M&m''s - Decoración Crepa' where id=33;
update modifier_options set name='Nuez - Decoración Crepa' where id=34;
update modifier_options set name='No, Gracias' where id=35;
update modifier_options set name='Miel Maple' where id=36;
update modifier_options set name='Duraznos en Almibar - Fruta Crepa' where id=37;
update modifier_options set name='Fresa - Fruta Crepa' where id=38;
update modifier_options set name='Frutos Rojos - Fruta Crepa' where id=39;
update modifier_options set name='Mango en Almibar - Fruta Crepa' where id=40;
update modifier_options set name='No, Gracias' where id=41;
update modifier_options set name='Platano - Fruta Crepa' where id=42;
update modifier_options set name='Ajonjolí' where id=43;
update modifier_options set name='Champiñón - Ramen' where id=44;
update modifier_options set name='Chile Quebrado (Chile Seco)' where id=45;
update modifier_options set name='Huevo Duro' where id=46;
update modifier_options set name='Huevo Estrellado' where id=47;
update modifier_options set name='Jamón - Ramen' where id=48;
update modifier_options set name='Mozarella - Ramen' where id=49;
update modifier_options set name='No Aplica' where id=50;
update modifier_options set name='Pepperoni - Ramen' where id=51;
update modifier_options set name='Verduras - Ramen' where id=52;
update modifier_options set name='Chuleta Ahumada' where id=53;
update modifier_options set name='Champiñón - Ramen' where id=54;
update modifier_options set name='Jamón - Ramen' where id=55;
update modifier_options set name='Mozarella - Ramen' where id=56;
update modifier_options set name='No Aplica' where id=57;
update modifier_options set name='Pepperoni - Ramen' where id=58;
update modifier_options set name='Verduras - Ramen' where id=59;
update modifier_options set name='Leche Deslactosada' where id=60;
update modifier_options set name='Leche Entera' where id=61;
update modifier_options set name='Sin' where id=62;
update modifier_options set name='Cereza' where id=63;
update modifier_options set name='Chicle' where id=64;
update modifier_options set name='Chocolate' where id=65;
update modifier_options set name='Dragon Fruit' where id=66;
update modifier_options set name='Fresa' where id=67;
update modifier_options set name='Kiwi' where id=68;
update modifier_options set name='Litchi' where id=69;
update modifier_options set name='Mango' where id=70;
update modifier_options set name='Manzana Verde' where id=71;
update modifier_options set name='Maracuya' where id=72;
update modifier_options set name='Mora Azul' where id=73;
update modifier_options set name='Tapioca' where id=74;
update modifier_options set name='Yogurth' where id=75;
update modifier_options set name='Sin Perlas' where id=76;
update modifier_options set name='Sin' where id=90;
update modifier_options set name='Cereza' where id=91;
update modifier_options set name='Chicle' where id=92;
update modifier_options set name='Chocolate' where id=93;
update modifier_options set name='Dragon Fruit' where id=94;
update modifier_options set name='Fresa' where id=95;
update modifier_options set name='Kiwi' where id=96;
update modifier_options set name='Litchi' where id=97;
update modifier_options set name='Mango' where id=98;
update modifier_options set name='Manzana Verde' where id=99;
update modifier_options set name='Maracuya' where id=100;
update modifier_options set name='Mora Azul' where id=101;
update modifier_options set name='Tapioca' where id=102;
update modifier_options set name='Yogurth' where id=103;
update modifier_options set name='Sin' where id=104;
update modifier_options set name='Cereza Negra' where id=105;
update modifier_options set name='Cereza' where id=106;
update modifier_options set name='Chicle' where id=107;
update modifier_options set name='Chocolate' where id=108;
update modifier_options set name='Fresa' where id=109;
update modifier_options set name='Kiwi' where id=110;
update modifier_options set name='Litchi' where id=111;
update modifier_options set name='Mango' where id=112;
update modifier_options set name='Manzana Verde' where id=113;
update modifier_options set name='Maracuya' where id=114;
update modifier_options set name='Mora Azul' where id=115;
update modifier_options set name='Tapioca' where id=116;
update modifier_options set name='Yogurth' where id=117;
update modifier_options set name='Sin' where id=118;
update modifier_options set name='Cereza' where id=119;
update modifier_options set name='Chicle' where id=120;
update modifier_options set name='Chocolate' where id=121;
update modifier_options set name='Dragon Fruit' where id=122;
update modifier_options set name='Fresa' where id=123;
update modifier_options set name='Kiwi' where id=124;
update modifier_options set name='Litchi' where id=125;
update modifier_options set name='Mango' where id=126;
update modifier_options set name='Manzana Verde' where id=127;
update modifier_options set name='Maracuya' where id=128;
update modifier_options set name='Mora Azul' where id=129;
update modifier_options set name='Perlas Chamoy' where id=130;
update modifier_options set name='Perlas de Sandia' where id=131;
update modifier_options set name='Tapioca' where id=132;
update modifier_options set name='Yogurth' where id=133;
update modifier_options set name='Huevo Proteina' where id=134;
update modifier_options set name='Pollo Proteina' where id=135;
update modifier_options set name='Sin Proteina' where id=136;
update modifier_options set name='Gratinados' where id=137;
update modifier_options set name='Huevo Extra' where id=138;
update modifier_options set name='Pollo Extra' where id=139;
update modifier_options set name='Tenders Proteina' where id=140;
update modifier_options set name='Banderilla Coreana' where id=141;
update modifier_options set name='Queso' where id=142;
update modifier_options set name='Preparado' where id=143;
update modifier_options set name='Sin Preparar' where id=144;
update modifier_options set name='Cereza' where id=157;
update modifier_options set name='Pelon' where id=158;
update modifier_options set name='Fresa' where id=159;
update modifier_options set name='Fresa Sandía' where id=160;
update modifier_options set name='Frutos Rojos' where id=161;
update modifier_options set name='Limón' where id=162;
update modifier_options set name='Mango' where id=163;
update modifier_options set name='Maracuyá' where id=164;
update modifier_options set name='Mojito' where id=165;
update modifier_options set name='Mora Azul' where id=166;
update modifier_options set name='Pepino Limón' where id=167;
update modifier_options set name='Pink Lemonade' where id=168;
update modifier_options set name='Sandía' where id=169;
update modifier_options set name='Capuccino' where id=174;
update modifier_options set name='Cookies & Cream (Oreo)' where id=184;
update modifier_options set name='Strawberry Cream (Fresa)' where id=206;
update modifier_options set name='Dragon Fruit' where id=211;
update modifier_options set name='Fresa' where id=212;
update modifier_options set name='Fresa Sandía' where id=213;
update modifier_options set name='Frutos Rojos' where id=214;
update modifier_options set name='Ice Cereza' where id=215;
update modifier_options set name='Ice Mora Azul' where id=216;
update modifier_options set name='Mango' where id=217;
update modifier_options set name='Maracuyá' where id=218;
update modifier_options set name='Mojito' where id=219;
update modifier_options set name='Pepino Limón' where id=220;
update modifier_options set name='Rompope' where id=221;
update modifier_options set name='Sandía' where id=222;
update modifier_options set name='Chocobana' where id=223;
update modifier_options set name='Chocolate' where id=224;
update modifier_options set name='Fresa Cremosa' where id=225;
update modifier_options set name='Frutos Rojos' where id=226;
update modifier_options set name='Chocolate' where id=227;
update modifier_options set name='Cookies & Cream' where id=228;
update modifier_options set name='Fresa' where id=229;
update modifier_options set name='Vainilla' where id=230;
update modifier_options set name='Milkis Durazno 250 ml' where id=231;
update modifier_options set name='Milkis Fresa 250 ml' where id=232;
update modifier_options set name='Milkis Manzana 250 ml' where id=233;
update modifier_options set name='Milkis Melón 250 ml' where id=234;
update modifier_options set name='Milkis Original 250 ml' where id=235;
update modifier_options set name='Cajeta Mini Donas 14pz' where id=236;
update modifier_options set name='Chocolate Mini Donas 14pz' where id=237;
update modifier_options set name='Crema Pastelera Mini Donas 14pz' where id=238;
update modifier_options set name='Fresa Mini Donas 14pz' where id=239;
update modifier_options set name='Lechera - Toppings Crepa' where id=240;
update modifier_options set name='Mapple Mini Donas 14pz' where id=241;
update modifier_options set name='Nutella Mini Donas 14pz' where id=242;
update modifier_options set name='Zarzamora Mini Donas 14pz' where id=243;
update modifier_options set name='Cajeta Mini Donas 8pz' where id=244;
update modifier_options set name='Chocolate Mini Donas 8pz' where id=245;
update modifier_options set name='Crema Pastelera Mini Donas 8pz' where id=246;
update modifier_options set name='Fresa Mini Donas 8pz' where id=247;
update modifier_options set name='Lechera - Toppings Crepa' where id=248;
update modifier_options set name='Mapple Mini Donas 8pz' where id=249;
update modifier_options set name='Nutella Mini Donas 8pz' where id=250;
update modifier_options set name='Zarzamora Mini Donas 8pz' where id=251;
update modifier_options set name='Mini Pizza - 4 Quesos' where id=252;
update modifier_options set name='Mini Pizza - Pepperoni' where id=253;
update modifier_options set name='Chocolate' where id=254;
update modifier_options set name='Frutos Rojos' where id=255;
update modifier_options set is_active=false where id=256; -- dup 'Frutos Rojos'
update modifier_options set name='Horchata' where id=257;
update modifier_options set name='Matcha' where id=258;
update modifier_options set name='Pink Lemonade' where id=259;
update modifier_options set name='Taro' where id=260;
update modifier_options set name='Taro Purple' where id=261;
update modifier_options set name='Vainilla' where id=262;
update modifier_options set name='Matcha Coco' where id=263;
update modifier_options set name='Buldak Swicy' where id=264;
update modifier_options set name='Ramen Carbonara - Buldak' where id=265;
update modifier_options set name='Ramen Chapagetti - Nongshim' where id=266;
update modifier_options set name='Ramen Cream Carbonara - Buldak' where id=267;
update modifier_options set name='Ramen Habanero Limon - Buldak' where id=268;
update modifier_options set name='Ramen Hot Chicken - Buldak' where id=269;
update modifier_options set name='Ramen Hot Chicken 2X - Buldak' where id=270;
update modifier_options set name='Ramen Hot Chicken 3X - Buldak' where id=271;
update modifier_options set name='Ramen Hot Chicken Cheese - Buldak' where id=272;
update modifier_options set name='Ramen Hot Pepper - Buldak' where id=273;
update modifier_options set name='Ramen Jin - Ottogi' where id=274;
update modifier_options set name='Ramen Jin Spicy - Ottogi' where id=275;
update modifier_options set name='Ramen Kimchi - Samyang' where id=276;
update modifier_options set name='Ramen Lovely Hot Chicken - Buldak' where id=277;
update modifier_options set name='Ramen Quattro Cheese - Buldak' where id=278;
update modifier_options set name='Ramen Rosé - Buldak' where id=279;
update modifier_options set name='Ramen Samyang Original - Samyang' where id=280;
update modifier_options set name='Ramen Shin Kimchi - Nongshim' where id=281;
update modifier_options set name='Ramen Shin Ramyun - Nongshim' where id=282;
update modifier_options set name='Ramen Tomato Hot Chicken - Buldak' where id=283;
update modifier_options set name='Ramen Yakisoba Hot Chicken -buldak' where id=284;
update modifier_options set name='Ramen Curry - Buldak' where id=285;
update modifier_options set name='Ramen Jjajang (Combo Corean)' where id=286;
update modifier_options set name='Smoothie Fresa' where id=287;
update modifier_options set name='Smoothie Frutos Rojos' where id=288;
update modifier_options set name='Bubaloo' where id=289;
update modifier_options set name='Cereza' where id=290;
update modifier_options set name='Chicle' where id=291;
update modifier_options set name='Durazno' where id=292;
update modifier_options set name='Frambuesa' where id=293;
update modifier_options set name='Fresa' where id=294;
update modifier_options set name='Kiwi' where id=295;
update modifier_options set name='Litchi' where id=296;
update modifier_options set name='Mango' where id=297;
update modifier_options set name='Manzana Verde' where id=298;
update modifier_options set name='Maracuya' where id=299;
update modifier_options set name='Mora Azul' where id=300;
update modifier_options set name='Neon Frutos Rojos' where id=301;
update modifier_options set name='Neon Manzana Verde' where id=302;
update modifier_options set name='Neon Mora Azul' where id=303;
update modifier_options set name='Sandía' where id=304;
update modifier_options set name='Frutos Rojos' where id=305;
update modifier_options set name='Matcha Coco' where id=306;
update modifier_options set name='Canela Manzana Té´s' where id=307;
update modifier_options set name='Frutos Rojos Té''s' where id=308;
update modifier_options set name='Fusión Herbal Té´s' where id=309;
update modifier_options set name='Hierbabuena Té´s' where id=310;
update modifier_options set name='Limón Té´s' where id=311;
update modifier_options set name='Manzanilla Té´s' where id=312;
update modifier_options set name='Tteokbokki Buldak - Original' where id=313;
update modifier_options set name='Tteokbokki Cj Bibigo - 125 g Sweet & Spicy' where id=314;
update modifier_options set name='Tteokbokki Cj Bibigo - 125 g Hot & Spicy' where id=315;
update modifier_options set name='Tteokbokki Cj Bibigo - 360 g Hot & Spicy' where id=316;
update modifier_options set name='Tteokbokki Cj Bibigo - 360 g Sweet & Spicy' where id=317;
update modifier_options set name='Banderilla Coreana' where id=318;
update modifier_options set name='Salsa Roja Chilaquiles' where id=383;
update modifier_options set name='Salsa Verde Chilaquiles' where id=384;
update modifier_options set name='Ajo Parmesano' where id=385;
update modifier_options set name='BBQ a la Diabla' where id=386;
update modifier_options set name='BBQ Chipotle' where id=387;
update modifier_options set name='BBQ Habanero' where id=388;
update modifier_options set name='BBQ' where id=389;
update modifier_options set name='Búfalo' where id=390;
update modifier_options set name='Cajún' where id=391;
update modifier_options set name='Cheetos' where id=392;
update modifier_options set name='Chingu Teriyaki' where id=393;
update modifier_options set name='Doritos Nacho' where id=394;
update modifier_options set name='Flamin Hot' where id=395;
update modifier_options set name='Fresa Spicy' where id=396;
update modifier_options set name='Jalapeño Spicy' where id=397;
update modifier_options set name='Krazy Hot' where id=398;
update modifier_options set name='Lemon Pepper' where id=399;
update modifier_options set name='Mango Guajillo' where id=400;
update modifier_options set name='Mango Habanero' where id=401;
update modifier_options set name='Mango Hot' where id=402;
update modifier_options set name='Mezcat' where id=403;
update modifier_options set name='Naranja Chipotle' where id=404;
update modifier_options set name='Original Hot' where id=405;
update modifier_options set name='Rancheritos' where id=406;
update modifier_options set name='Ruffless Queso' where id=407;
update modifier_options set name='Salsa Brava CH' where id=408;
update modifier_options set name='Sriracha' where id=409;
update modifier_options set name='Tamarindo' where id=410;
update modifier_options set name='Ajo Parmesano' where id=411;
update modifier_options set name='BBQ a la Diabla' where id=412;
update modifier_options set name='BBQ Chipotle' where id=413;
update modifier_options set name='BBQ Habanero' where id=414;
update modifier_options set name='BBQ' where id=415;
update modifier_options set name='Búfalo' where id=416;
update modifier_options set name='Cajún' where id=417;
update modifier_options set name='Cheetos' where id=418;
update modifier_options set name='Chingu Teriyaki' where id=419;
update modifier_options set name='Doritos Nacho' where id=420;
update modifier_options set name='Flamin Hot' where id=421;
update modifier_options set name='Fresa Spicy' where id=422;
update modifier_options set name='Jalapeño Spicy' where id=423;
update modifier_options set name='Krazy Hot' where id=424;
update modifier_options set name='Lemon Pepper' where id=425;
update modifier_options set name='Mango Guajillo' where id=426;
update modifier_options set name='Mango Habanero' where id=427;
update modifier_options set name='Mango Hot' where id=428;
update modifier_options set name='Mezcat' where id=429;
update modifier_options set name='Naranja Chipotle' where id=430;
update modifier_options set name='Original Hot' where id=431;
update modifier_options set name='Rancheritos' where id=432;
update modifier_options set name='Ruffless Queso' where id=433;
update modifier_options set name='Salsa Brava G' where id=434;
update modifier_options set name='Sriracha' where id=435;
update modifier_options set name='Tamarindo' where id=436;
update modifier_options set name='Cajun Sazonador G' where id=437;
update modifier_options set name='Lemon Pepper' where id=438;
update modifier_options set name='Queso Chedar Sazonador G' where id=439;
update modifier_options set name='Arizona Kiwi Fresa' where id=440;
update modifier_options set name='Arizona Mango' where id=441;
update modifier_options set name='Arizona Sandia' where id=442;
update modifier_options set name='14 oz' where id=443;
update modifier_options set name='16 oz' where id=444;
update modifier_options set name='14 oz (Ch)' where id=445;
update modifier_options set name='16 oz' where id=446;
update modifier_options set name='Donitas Gatunas 14pza' where id=449;
update modifier_options set name='Donitas Gatunas 8pza' where id=450;
update modifier_options set name='Papas Fritas - Corte Recto - CH (170g)' where id=451;
update modifier_options set name='Papas Fritas - Corte Recto G (350g)' where id=452;
update modifier_options set name='Papas Fritas - Corte Recto J (500g)' where id=453;
update modifier_options set name='Papas Fritas - Corte Recto M (270g)' where id=454;
update modifier_options set name='Base Agua' where id=455;
update modifier_options set name='Leche Deslactosada' where id=456;
update modifier_options set name='Leche Entera' where id=457;
update modifier_options set name='Leche Deslactosada' where id=458;
update modifier_options set name='Leche Entera' where id=459;
update modifier_options set name='Leche Deslactosada' where id=460;
update modifier_options set name='Leche Entera' where id=461;
update modifier_options set name='Leche Deslactosada' where id=462;
update modifier_options set name='Leche Entera' where id=463;
update modifier_options set name='Leche Deslactosada' where id=464;
update modifier_options set name='Leche Entera' where id=465;
update modifier_options set name='Cajeta - Toppings Crepa' where id=466;
update modifier_options set name='Chocolate Liq Hersey - Toppings Crepa' where id=467;
update modifier_options set name='Crema Batida - Toppings Crepa' where id=468;
update modifier_options set name='Crema Pastelera - Toppings Crepa' where id=469;
update modifier_options set name='Galleta Oreo - Toppings Crepa' where id=470;
update modifier_options set name='Lechera - Toppings Crepa' where id=471;
update modifier_options set name='Mapple - Toppings Crepa' where id=472;
update modifier_options set name='Mermelada Cereza Negra - Toppings Crepa' where id=473;
update modifier_options set name='Mermelada de Zarzamora - Toppings Crepa' where id=474;
update modifier_options set name='Mermelada Fresa - Toppings Crepa' where id=475;
update modifier_options set name='Mermelada Frutos Rojos - Toppings Crepa' where id=476;
update modifier_options set name='Nutella - Toppings Crepa' where id=477;
update modifier_options set name='No, Gracias' where id=478;
update modifier_options set name='Philadelphia - Toppings Crepa' where id=479;
update modifier_options set name='Azúcar Glass - Decoración Crepa' where id=480;
update modifier_options set name='Canela - Decoración Crepa' where id=481;
update modifier_options set name='Frappe de Agua' where id=484;
update modifier_options set name='No Aplica' where id=485;
commit;
cho '--- productos con MAYÚSCULAS residuales (debe ser bajo) ---'
select count(*) from products where is_active and name ~ '[A-Z]{4,}';
