// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: admin.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const adminCreateProduct = `-- name: AdminCreateProduct :one

insert into products (name, category_id, price, is_favorite, track_stock)
values ($1, $2, $3, $4, $5)
returning id
`

type AdminCreateProductParams struct {
	Name       string          `json:"name"`
	CategoryID int64           `json:"category_id"`
	Price      decimal.Decimal `json:"price"`
	IsFavorite bool            `json:"is_favorite"`
	TrackStock bool            `json:"track_stock"`
}

// lim=0 → sin límite (POS modo edición pide todo)
// Alta mínima de producto (tipo 'simple', activo por defecto). El costo/receta/canales se
// configuran después; sku/imagen quedan null.
func (q *Queries) AdminCreateProduct(ctx context.Context, arg AdminCreateProductParams) (int64, error) {
	row := q.db.QueryRow(ctx, adminCreateProduct,
		arg.Name,
		arg.CategoryID,
		arg.Price,
		arg.IsFavorite,
		arg.TrackStock,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const adminListModifierOptions = `-- name: AdminListModifierOptions :many
select mo.id, mo.group_id, mg.name as group_name, mo.name, mo.price_delta, mo.is_favorite, mo.is_active,
       count(*) over() as total
from modifier_options mo
join modifier_groups mg on mg.id = mo.group_id
where mg.is_active
  and ($1::text = ''
        or ($1 = 'act' and mo.is_active)
        or ($1 = 'inact' and not mo.is_active))
  and ($2::text = '' or mo.name ilike '%' || $2 || '%' or mg.name ilike '%' || $2 || '%')
order by mg.name, mo.sort_key, mo.name
limit nullif($4::int, 0) offset $3
`

type AdminListModifierOptionsParams struct {
	Status string `json:"status"`
	Search string `json:"search"`
	Off    int32  `json:"off"`
	Lim    int32  `json:"lim"`
}

type AdminListModifierOptionsRow struct {
	ID         int64           `json:"id"`
	GroupID    int64           `json:"group_id"`
	GroupName  string          `json:"group_name"`
	Name       string          `json:"name"`
	PriceDelta decimal.Decimal `json:"price_delta"`
	IsFavorite bool            `json:"is_favorite"`
	IsActive   bool            `json:"is_active"`
	Total      int64           `json:"total"`
}

// Página de opciones (de grupos activos) filtrada por estado (”=todas | 'act' | 'inact') y
// búsqueda (nombre de opción o de grupo). count(*) over() = total del filtro, para el paginador.
// Incluye inactivas y price_delta: el POS puede mostrar/cobrar una opción archivada al reactivarla.
func (q *Queries) AdminListModifierOptions(ctx context.Context, arg AdminListModifierOptionsParams) ([]AdminListModifierOptionsRow, error) {
	rows, err := q.db.Query(ctx, adminListModifierOptions,
		arg.Status,
		arg.Search,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListModifierOptionsRow{}
	for rows.Next() {
		var i AdminListModifierOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.GroupName,
			&i.Name,
			&i.PriceDelta,
			&i.IsFavorite,
			&i.IsActive,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminListProducts = `-- name: AdminListProducts :many
select q.id, q.name, q.price, q.current_cost, q.type, q.is_active, q.is_favorite, q.available_from, q.available_until, q.category, q.group_count, q.override_count, count(*) over() as total
from (
  select p.id, p.name, p.price, p.current_cost, p.type, p.is_active, p.is_favorite,
         p.available_from, p.available_until, c.name as category,
         (select count(*) from product_modifier_groups pmg
            join modifier_groups mg on mg.id = pmg.group_id
           where pmg.product_id = p.id and mg.is_active)::int as group_count,
         (select count(*) from product_modifier_groups pmg
           where pmg.product_id = p.id and pmg.min_select is not null)::int as override_count
  from products p
  join categories c on c.id = p.category_id
  where ($1::text = ''
          or ($1 = 'act' and p.is_active)
          or ($1 = 'inact' and not p.is_active))
    and ($2::text = '' or p.name ilike '%' || $2 || '%')
    and ($3::bigint = 0 or p.category_id = $3 or c.parent_id = $3)
) q
where ($4::text = ''
        or ($4 = 'none' and q.group_count = 0)
        or ($4 = 'some' and q.group_count > 0))
order by
  case when $5::text = 'price'    and $6::text = 'asc'  then q.price end asc  nulls last,
  case when $5::text = 'price'    and $6::text <> 'asc' then q.price end desc nulls last,
  case when $5::text = 'cost'     and $6::text = 'asc'  then q.current_cost end asc  nulls last,
  case when $5::text = 'cost'     and $6::text <> 'asc' then q.current_cost end desc nulls last,
  case when $5::text = 'margin'   and $6::text = 'asc'  then (q.price - q.current_cost) end asc  nulls last,
  case when $5::text = 'margin'   and $6::text <> 'asc' then (q.price - q.current_cost) end desc nulls last,
  case when $5::text = 'groups'   and $6::text = 'asc'  then q.group_count end asc  nulls last,
  case when $5::text = 'groups'   and $6::text <> 'asc' then q.group_count end desc nulls last,
  case when $5::text = 'category' and $6::text = 'asc'  then q.category end asc  nulls last,
  case when $5::text = 'category' and $6::text <> 'asc' then q.category end desc nulls last,
  case when $5::text = 'name'     and $6::text = 'desc' then q.name end desc nulls last,
  q.name
limit nullif($8::int, 0) offset $7
`

type AdminListProductsParams struct {
	Status     string `json:"status"`
	Search     string `json:"search"`
	CategoryID int64  `json:"category_id"`
	Groups     string `json:"groups"`
	Sort       string `json:"sort"`
	Dir        string `json:"dir"`
	Off        int32  `json:"off"`
	Lim        int32  `json:"lim"`
}

type AdminListProductsRow struct {
	ID             int64           `json:"id"`
	Name           string          `json:"name"`
	Price          decimal.Decimal `json:"price"`
	CurrentCost    decimal.Decimal `json:"current_cost"`
	Type           ProductType     `json:"type"`
	IsActive       bool            `json:"is_active"`
	IsFavorite     bool            `json:"is_favorite"`
	AvailableFrom  pgtype.Date     `json:"available_from"`
	AvailableUntil pgtype.Date     `json:"available_until"`
	Category       string          `json:"category"`
	GroupCount     int32           `json:"group_count"`
	OverrideCount  int32           `json:"override_count"`
	Total          int64           `json:"total"`
}

// Página filtrada por estado (”=todos | 'act' | 'inact'), búsqueda (”=sin filtro), categoría
// (@category_id=0 → todas; elegir una raíz incluye sus subcategorías vía c.parent_id) y grupos
// (”=todos | 'none'=sin grupos activos | 'some'=con grupos). Orden por columna: @sort ∈
// (”|name|price|cost|margin|category|groups) × @dir (asc|desc); default nombre asc. count(*)
// over() (tras el filtro de grupos) = total del filtro en la misma consulta (sin viaje extra).
func (q *Queries) AdminListProducts(ctx context.Context, arg AdminListProductsParams) ([]AdminListProductsRow, error) {
	rows, err := q.db.Query(ctx, adminListProducts,
		arg.Status,
		arg.Search,
		arg.CategoryID,
		arg.Groups,
		arg.Sort,
		arg.Dir,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AdminListProductsRow{}
	for rows.Next() {
		var i AdminListProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.CurrentCost,
			&i.Type,
			&i.IsActive,
			&i.IsFavorite,
			&i.AvailableFrom,
			&i.AvailableUntil,
			&i.Category,
			&i.GroupCount,
			&i.OverrideCount,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const adminModifierOptionCounts = `-- name: AdminModifierOptionCounts :one

select count(*) filter (where mo.is_active)::int as active,
       count(*) filter (where not mo.is_active)::int as inactive
from modifier_options mo
join modifier_groups mg on mg.id = mo.group_id
where mg.is_active
`

type AdminModifierOptionCountsRow struct {
	Active   int32 `json:"active"`
	Inactive int32 `json:"inactive"`
}

// lim=0 → sin límite (el POS pide todas)
// Totales por estado (opciones de grupos activos), para las pestañas. Independiente de la búsqueda.
func (q *Queries) AdminModifierOptionCounts(ctx context.Context) (AdminModifierOptionCountsRow, error) {
	row := q.db.QueryRow(ctx, adminModifierOptionCounts)
	var i AdminModifierOptionCountsRow
	err := row.Scan(&i.Active, &i.Inactive)
	return i, err
}

const adminProductCounts = `-- name: AdminProductCounts :one
select count(*) filter (where is_active)::int as active,
       count(*) filter (where not is_active)::int as inactive
from products
`

type AdminProductCountsRow struct {
	Active   int32 `json:"active"`
	Inactive int32 `json:"inactive"`
}

// Totales del catálogo por estado, para las pestañas (independientes de la búsqueda, como antes).
func (q *Queries) AdminProductCounts(ctx context.Context) (AdminProductCountsRow, error) {
	row := q.db.QueryRow(ctx, adminProductCounts)
	var i AdminProductCountsRow
	err := row.Scan(&i.Active, &i.Inactive)
	return i, err
}

const adminSetOptionActive = `-- name: AdminSetOptionActive :exec
update modifier_options set is_active = $2 where id = $1
`

type AdminSetOptionActiveParams struct {
	ID       int64 `json:"id"`
	IsActive bool  `json:"is_active"`
}

func (q *Queries) AdminSetOptionActive(ctx context.Context, arg AdminSetOptionActiveParams) error {
	_, err := q.db.Exec(ctx, adminSetOptionActive, arg.ID, arg.IsActive)
	return err
}

const adminSetOptionFavorite = `-- name: AdminSetOptionFavorite :exec
update modifier_options set is_favorite = $2 where id = $1
`

type AdminSetOptionFavoriteParams struct {
	ID         int64 `json:"id"`
	IsFavorite bool  `json:"is_favorite"`
}

func (q *Queries) AdminSetOptionFavorite(ctx context.Context, arg AdminSetOptionFavoriteParams) error {
	_, err := q.db.Exec(ctx, adminSetOptionFavorite, arg.ID, arg.IsFavorite)
	return err
}

const adminUpdateProduct = `-- name: AdminUpdateProduct :exec
update products
set name = $2, price = $3, is_favorite = $4, is_active = $5,
    available_from = $6, available_until = $7, updated_at = now()
where id = $1
`

type AdminUpdateProductParams struct {
	ID             int64           `json:"id"`
	Name           string          `json:"name"`
	Price          decimal.Decimal `json:"price"`
	IsFavorite     bool            `json:"is_favorite"`
	IsActive       bool            `json:"is_active"`
	AvailableFrom  pgtype.Date     `json:"available_from"`
	AvailableUntil pgtype.Date     `json:"available_until"`
}

func (q *Queries) AdminUpdateProduct(ctx context.Context, arg AdminUpdateProductParams) error {
	_, err := q.db.Exec(ctx, adminUpdateProduct,
		arg.ID,
		arg.Name,
		arg.Price,
		arg.IsFavorite,
		arg.IsActive,
		arg.AvailableFrom,
		arg.AvailableUntil,
	)
	return err
}

const cloneComboSlot = `-- name: CloneComboSlot :one
insert into combo_slots (combo_id, name, min_select, max_select, position)
values ($1, $2, $3, $4, $5)
returning id
`

type CloneComboSlotParams struct {
	ComboID   int64  `json:"combo_id"`
	Name      string `json:"name"`
	MinSelect int16  `json:"min_select"`
	MaxSelect int16  `json:"max_select"`
	Position  int32  `json:"position"`
}

func (q *Queries) CloneComboSlot(ctx context.Context, arg CloneComboSlotParams) (int64, error) {
	row := q.db.QueryRow(ctx, cloneComboSlot,
		arg.ComboID,
		arg.Name,
		arg.MinSelect,
		arg.MaxSelect,
		arg.Position,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const cloneComboSlotProducts = `-- name: CloneComboSlotProducts :exec
insert into combo_slot_products (slot_id, product_id, price_delta, is_default)
select $1, csp.product_id, csp.price_delta, csp.is_default
from combo_slot_products csp where csp.slot_id = $2
`

type CloneComboSlotProductsParams struct {
	DstSlot int64 `json:"dst_slot"`
	SrcSlot int64 `json:"src_slot"`
}

func (q *Queries) CloneComboSlotProducts(ctx context.Context, arg CloneComboSlotProductsParams) error {
	_, err := q.db.Exec(ctx, cloneComboSlotProducts, arg.DstSlot, arg.SrcSlot)
	return err
}

const cloneProductChannels = `-- name: CloneProductChannels :exec
insert into product_channels (product_id, channel_id, visibility)
select $1, pc.channel_id, pc.visibility
from product_channels pc where pc.product_id = $2
`

type CloneProductChannelsParams struct {
	DstProduct int64 `json:"dst_product"`
	SrcProduct int64 `json:"src_product"`
}

func (q *Queries) CloneProductChannels(ctx context.Context, arg CloneProductChannelsParams) error {
	_, err := q.db.Exec(ctx, cloneProductChannels, arg.DstProduct, arg.SrcProduct)
	return err
}

const cloneProductModifierGroups = `-- name: CloneProductModifierGroups :exec
insert into product_modifier_groups (product_id, group_id, title, min_select, max_select, position)
select $1, pmg.group_id, pmg.title, pmg.min_select, pmg.max_select, pmg.position
from product_modifier_groups pmg where pmg.product_id = $2
`

type CloneProductModifierGroupsParams struct {
	DstProduct int64 `json:"dst_product"`
	SrcProduct int64 `json:"src_product"`
}

func (q *Queries) CloneProductModifierGroups(ctx context.Context, arg CloneProductModifierGroupsParams) error {
	_, err := q.db.Exec(ctx, cloneProductModifierGroups, arg.DstProduct, arg.SrcProduct)
	return err
}

const cloneProductRow = `-- name: CloneProductRow :one
insert into products (
  name, description, type, category_id, price, cost_source, manual_cost, current_cost,
  recipe_id, track_stock, allow_oversell, min_stock, is_favorite, sort_key, image_url, is_active
)
select $1, p.description, p.type, p.category_id, p.price, p.cost_source, p.manual_cost, p.current_cost,
       $2, p.track_stock, p.allow_oversell, p.min_stock, p.is_favorite, p.sort_key, p.image_url, p.is_active
from products p where p.id = $3
returning id
`

type CloneProductRowParams struct {
	Name     string `json:"name"`
	RecipeID *int64 `json:"recipe_id"`
	SrcID    int64  `json:"src_id"`
}

// Copia la fila del producto de origen con nombre nuevo. sku queda null (es unique; no se copia)
// y recipe_id apunta a la receta ya clonada (o null). company_id lo sella el default del GUC.
func (q *Queries) CloneProductRow(ctx context.Context, arg CloneProductRowParams) (int64, error) {
	row := q.db.QueryRow(ctx, cloneProductRow, arg.Name, arg.RecipeID, arg.SrcID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const cloneRecipe = `-- name: CloneRecipe :one
insert into recipes default values returning id
`

// Receta vacía nueva (hereda company_id del GUC vía default); luego se copian sus ítems.
func (q *Queries) CloneRecipe(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, cloneRecipe)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const cloneRecipeItems = `-- name: CloneRecipeItems :exec
insert into recipe_items (recipe_id, ingredient_id, quantity, unit_id, position)
select $1, ri.ingredient_id, ri.quantity, ri.unit_id, ri.position
from recipe_items ri where ri.recipe_id = $2
`

type CloneRecipeItemsParams struct {
	DstRecipe int64 `json:"dst_recipe"`
	SrcRecipe int64 `json:"src_recipe"`
}

// Alias en la fuente: el insert y el select son sobre tablas del mismo esquema; sin alias, sqlc
// reporta columnas ambiguas entre el target del insert y la fuente del select.
func (q *Queries) CloneRecipeItems(ctx context.Context, arg CloneRecipeItemsParams) error {
	_, err := q.db.Exec(ctx, cloneRecipeItems, arg.DstRecipe, arg.SrcRecipe)
	return err
}

const getProductCloneInfo = `-- name: GetProductCloneInfo :one

select type, recipe_id from products where id = $1
`

type GetProductCloneInfoRow struct {
	Type     ProductType `json:"type"`
	RecipeID *int64      `json:"recipe_id"`
}

// ==== Duplicar producto (clon profundo con sus relaciones) ====
// Datos que deciden el clon: tipo (para slots de combo) y si tiene receta propia (a clonar).
func (q *Queries) GetProductCloneInfo(ctx context.Context, id int64) (GetProductCloneInfoRow, error) {
	row := q.db.QueryRow(ctx, getProductCloneInfo, id)
	var i GetProductCloneInfoRow
	err := row.Scan(&i.Type, &i.RecipeID)
	return i, err
}

const listComboSlots = `-- name: ListComboSlots :many
select id, name, min_select, max_select, position from combo_slots where combo_id = $1 order by position, id
`

type ListComboSlotsRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	MinSelect int16  `json:"min_select"`
	MaxSelect int16  `json:"max_select"`
	Position  int32  `json:"position"`
}

func (q *Queries) ListComboSlots(ctx context.Context, comboID int64) ([]ListComboSlotsRow, error) {
	rows, err := q.db.Query(ctx, listComboSlots, comboID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListComboSlotsRow{}
	for rows.Next() {
		var i ListComboSlotsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.MinSelect,
			&i.MaxSelect,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
