// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cash.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const anyOpenSession = `-- name: AnyOpenSession :one
select exists(select 1 from register_sessions where status = 'abierta')
`

func (q *Queries) AnyOpenSession(ctx context.Context) (bool, error) {
	row := q.db.QueryRow(ctx, anyOpenSession)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const closeSession = `-- name: CloseSession :exec
update register_sessions set status = 'cerrada', closed_by = $2, closed_at = now(), notes = $3
where id = $1
`

type CloseSessionParams struct {
	ID       int64   `json:"id"`
	ClosedBy *int64  `json:"closed_by"`
	Notes    *string `json:"notes"`
}

func (q *Queries) CloseSession(ctx context.Context, arg CloseSessionParams) error {
	_, err := q.db.Exec(ctx, closeSession, arg.ID, arg.ClosedBy, arg.Notes)
	return err
}

const createCashRegister = `-- name: CreateCashRegister :one
insert into cash_registers (name) values ($1)
returning id, name, is_primary, is_active
`

type CreateCashRegisterRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	IsPrimary bool   `json:"is_primary"`
	IsActive  bool   `json:"is_active"`
}

// is_primary/is_active toman su default (secundaria, activa): la primaria la fija la migración.
func (q *Queries) CreateCashRegister(ctx context.Context, name string) (CreateCashRegisterRow, error) {
	row := q.db.QueryRow(ctx, createCashRegister, name)
	var i CreateCashRegisterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrimary,
		&i.IsActive,
	)
	return i, err
}

const createCashTransfer = `-- name: CreateCashTransfer :one
insert into cash_transfers (from_session_id, to_session_id, amount, note, created_by)
values ($1, $2, $3, $4, $5)
returning id
`

type CreateCashTransferParams struct {
	FromSessionID int64           `json:"from_session_id"`
	ToSessionID   int64           `json:"to_session_id"`
	Amount        decimal.Decimal `json:"amount"`
	Note          *string         `json:"note"`
	CreatedBy     int64           `json:"created_by"`
}

// Traspasos entre cajas: la fila de traspaso + cada pierna como movimiento ligado.
func (q *Queries) CreateCashTransfer(ctx context.Context, arg CreateCashTransferParams) (int64, error) {
	row := q.db.QueryRow(ctx, createCashTransfer,
		arg.FromSessionID,
		arg.ToSessionID,
		arg.Amount,
		arg.Note,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const expectedByMethodSince = `-- name: ExpectedByMethodSince :many
select pm.id as payment_method_id, pm.name, pm.kind, pm.affects_cash_drawer, pm.auto_declare,
       coalesce(sum(op.amount), 0)::numeric(10,2) as expected,
       coalesce(sum(op.tip_amount), 0)::numeric(10,2) as tips
from payment_methods pm
left join order_payments op on op.payment_method_id = pm.id and op.created_at >= $1
where pm.is_active
group by pm.id, pm.name, pm.kind, pm.affects_cash_drawer, pm.auto_declare
order by pm.sort_key
`

type ExpectedByMethodSinceRow struct {
	PaymentMethodID   int16           `json:"payment_method_id"`
	Name              string          `json:"name"`
	Kind              PaymentKind     `json:"kind"`
	AffectsCashDrawer bool            `json:"affects_cash_drawer"`
	AutoDeclare       bool            `json:"auto_declare"`
	Expected          decimal.Decimal `json:"expected"`
	Tips              decimal.Decimal `json:"tips"`
}

// Totales esperados por método desde la apertura de la sesión (ventana temporal).
// expected = ventas (amount); tips = propinas (tip_amount) por método desde la apertura. Ambas son
// dinero recibido: entran al esperado del corte, pero se muestran como líneas separadas (Ventas / Propinas).
// kind viaja además de affects_cash_drawer porque distinguen cosas distintas: el segundo dice si
// ese dinero se cuenta en el arqueo (lo cumplen el efectivo del mostrador Y el de las plataformas),
// y el primero identifica al ÚNICO al que pertenecen el fondo de apertura y los movimientos de
// caja. Sumar el fondo a todo lo que toca el cajón lo contaba una vez por método.
func (q *Queries) ExpectedByMethodSince(ctx context.Context, createdAt time.Time) ([]ExpectedByMethodSinceRow, error) {
	rows, err := q.db.Query(ctx, expectedByMethodSince, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExpectedByMethodSinceRow{}
	for rows.Next() {
		var i ExpectedByMethodSinceRow
		if err := rows.Scan(
			&i.PaymentMethodID,
			&i.Name,
			&i.Kind,
			&i.AffectsCashDrawer,
			&i.AutoDeclare,
			&i.Expected,
			&i.Tips,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCashRegister = `-- name: GetCashRegister :one
select id, name, is_primary, is_active from cash_registers where id = $1
`

type GetCashRegisterRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	IsPrimary bool   `json:"is_primary"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) GetCashRegister(ctx context.Context, id int64) (GetCashRegisterRow, error) {
	row := q.db.QueryRow(ctx, getCashRegister, id)
	var i GetCashRegisterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrimary,
		&i.IsActive,
	)
	return i, err
}

const getOpenPrimarySession = `-- name: GetOpenPrimarySession :one
select s.id, s.register_id, s.business_date
from register_sessions s
join cash_registers r on r.id = s.register_id
where s.status = 'abierta' and r.is_primary and r.is_active
limit 1
`

type GetOpenPrimarySessionRow struct {
	ID           int64       `json:"id"`
	RegisterID   int64       `json:"register_id"`
	BusinessDate pgtype.Date `json:"business_date"`
}

// La sesión que habilita cobrar. Es SIEMPRE la de la caja principal: las secundarias (caja fuerte,
// caja externa) existen para traspasos y gastos, y si una de ellas bastara para vender el efectivo
// del mostrador caería en un arqueo que no es el suyo.
func (q *Queries) GetOpenPrimarySession(ctx context.Context) (GetOpenPrimarySessionRow, error) {
	row := q.db.QueryRow(ctx, getOpenPrimarySession)
	var i GetOpenPrimarySessionRow
	err := row.Scan(&i.ID, &i.RegisterID, &i.BusinessDate)
	return i, err
}

const getOpenSessionByRegister = `-- name: GetOpenSessionByRegister :one

select id, business_date, status, opening_cash, opened_by, opened_at, closed_by, closed_at, notes, currency, register_id from register_sessions where register_id = $1 and status = 'abierta' limit 1
`

// Cortes de caja (sesiones de una caja)
func (q *Queries) GetOpenSessionByRegister(ctx context.Context, registerID int64) (RegisterSession, error) {
	row := q.db.QueryRow(ctx, getOpenSessionByRegister, registerID)
	var i RegisterSession
	err := row.Scan(
		&i.ID,
		&i.BusinessDate,
		&i.Status,
		&i.OpeningCash,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.Notes,
		&i.Currency,
		&i.RegisterID,
	)
	return i, err
}

const getPaymentMethod = `-- name: GetPaymentMethod :one
select id, name, kind, affects_cash_drawer, auto_declare from payment_methods where id = $1
`

type GetPaymentMethodRow struct {
	ID                int16       `json:"id"`
	Name              string      `json:"name"`
	Kind              PaymentKind `json:"kind"`
	AffectsCashDrawer bool        `json:"affects_cash_drawer"`
	AutoDeclare       bool        `json:"auto_declare"`
}

func (q *Queries) GetPaymentMethod(ctx context.Context, id int16) (GetPaymentMethodRow, error) {
	row := q.db.QueryRow(ctx, getPaymentMethod, id)
	var i GetPaymentMethodRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.AffectsCashDrawer,
		&i.AutoDeclare,
	)
	return i, err
}

const getSession = `-- name: GetSession :one
select s.id, s.business_date, s.status, s.opening_cash, s.opened_by, s.opened_at, s.closed_by, s.closed_at, s.notes, s.currency, s.register_id, r.name as register_name, ob.name as opened_by_name, cb.name as closed_by_name
from register_sessions s
join cash_registers r on r.id = s.register_id
join users ob on ob.id = s.opened_by
left join users cb on cb.id = s.closed_by
where s.id = $1
`

type GetSessionRow struct {
	ID           int64              `json:"id"`
	BusinessDate pgtype.Date        `json:"business_date"`
	Status       SessionStatus      `json:"status"`
	OpeningCash  decimal.Decimal    `json:"opening_cash"`
	OpenedBy     int64              `json:"opened_by"`
	OpenedAt     time.Time          `json:"opened_at"`
	ClosedBy     *int64             `json:"closed_by"`
	ClosedAt     pgtype.Timestamptz `json:"closed_at"`
	Notes        *string            `json:"notes"`
	Currency     string             `json:"currency"`
	RegisterID   int64              `json:"register_id"`
	RegisterName string             `json:"register_name"`
	OpenedByName string             `json:"opened_by_name"`
	ClosedByName *string            `json:"closed_by_name"`
}

func (q *Queries) GetSession(ctx context.Context, id int64) (GetSessionRow, error) {
	row := q.db.QueryRow(ctx, getSession, id)
	var i GetSessionRow
	err := row.Scan(
		&i.ID,
		&i.BusinessDate,
		&i.Status,
		&i.OpeningCash,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.Notes,
		&i.Currency,
		&i.RegisterID,
		&i.RegisterName,
		&i.OpenedByName,
		&i.ClosedByName,
	)
	return i, err
}

const insertCashMovement = `-- name: InsertCashMovement :one
insert into register_cash_movements (session_id, kind, amount, concept, user_id)
values ($1, $2, $3, $4, $5)
returning id, session_id, kind, amount, concept, expense_id, user_id, created_at, transfer_id
`

type InsertCashMovementParams struct {
	SessionID int64           `json:"session_id"`
	Kind      string          `json:"kind"`
	Amount    decimal.Decimal `json:"amount"`
	Concept   string          `json:"concept"`
	UserID    int64           `json:"user_id"`
}

// Movimientos de efectivo (entradas/salidas del cajón durante la sesión).
func (q *Queries) InsertCashMovement(ctx context.Context, arg InsertCashMovementParams) (RegisterCashMovement, error) {
	row := q.db.QueryRow(ctx, insertCashMovement,
		arg.SessionID,
		arg.Kind,
		arg.Amount,
		arg.Concept,
		arg.UserID,
	)
	var i RegisterCashMovement
	err := row.Scan(
		&i.ID,
		&i.SessionID,
		&i.Kind,
		&i.Amount,
		&i.Concept,
		&i.ExpenseID,
		&i.UserID,
		&i.CreatedAt,
		&i.TransferID,
	)
	return i, err
}

const insertExpenseCashMovement = `-- name: InsertExpenseCashMovement :exec
insert into register_cash_movements (session_id, kind, amount, concept, expense_id, user_id)
values ($1, 'salida', $2, $3, $4, $5)
`

type InsertExpenseCashMovementParams struct {
	SessionID int64           `json:"session_id"`
	Amount    decimal.Decimal `json:"amount"`
	Concept   string          `json:"concept"`
	ExpenseID *int64          `json:"expense_id"`
	UserID    int64           `json:"user_id"`
}

// Salida de efectivo del cajón al pagar un gasto en efectivo (liga el gasto al corte).
func (q *Queries) InsertExpenseCashMovement(ctx context.Context, arg InsertExpenseCashMovementParams) error {
	_, err := q.db.Exec(ctx, insertExpenseCashMovement,
		arg.SessionID,
		arg.Amount,
		arg.Concept,
		arg.ExpenseID,
		arg.UserID,
	)
	return err
}

const insertTransferMovement = `-- name: InsertTransferMovement :exec
insert into register_cash_movements (session_id, kind, amount, concept, user_id, transfer_id)
values ($1, $2, $3, $4, $5, $6)
`

type InsertTransferMovementParams struct {
	SessionID  int64           `json:"session_id"`
	Kind       string          `json:"kind"`
	Amount     decimal.Decimal `json:"amount"`
	Concept    string          `json:"concept"`
	UserID     int64           `json:"user_id"`
	TransferID *int64          `json:"transfer_id"`
}

func (q *Queries) InsertTransferMovement(ctx context.Context, arg InsertTransferMovementParams) error {
	_, err := q.db.Exec(ctx, insertTransferMovement,
		arg.SessionID,
		arg.Kind,
		arg.Amount,
		arg.Concept,
		arg.UserID,
		arg.TransferID,
	)
	return err
}

const listAllCashRegisters = `-- name: ListAllCashRegisters :many
select id, name, is_primary, is_active from cash_registers order by is_primary desc, name
`

type ListAllCashRegistersRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	IsPrimary bool   `json:"is_primary"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) ListAllCashRegisters(ctx context.Context) ([]ListAllCashRegistersRow, error) {
	rows, err := q.db.Query(ctx, listAllCashRegisters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListAllCashRegistersRow{}
	for rows.Next() {
		var i ListAllCashRegistersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrimary,
			&i.IsActive,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashMovements = `-- name: ListCashMovements :many
select m.id, m.kind, m.amount, m.concept, m.created_at, u.name as user_name, m.transfer_id, m.expense_id
from register_cash_movements m
join users u on u.id = m.user_id
where m.session_id = $1
order by m.created_at
`

type ListCashMovementsRow struct {
	ID         int64           `json:"id"`
	Kind       string          `json:"kind"`
	Amount     decimal.Decimal `json:"amount"`
	Concept    string          `json:"concept"`
	CreatedAt  time.Time       `json:"created_at"`
	UserName   string          `json:"user_name"`
	TransferID *int64          `json:"transfer_id"`
	ExpenseID  *int64          `json:"expense_id"`
}

// expense_id: no-null si el movimiento es la salida de un gasto → el front lo excluye de la tabla
// de efectivo (los gastos van en su propia sección) para no contarlos dos veces.
func (q *Queries) ListCashMovements(ctx context.Context, sessionID int64) ([]ListCashMovementsRow, error) {
	rows, err := q.db.Query(ctx, listCashMovements, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCashMovementsRow{}
	for rows.Next() {
		var i ListCashMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.Kind,
			&i.Amount,
			&i.Concept,
			&i.CreatedAt,
			&i.UserName,
			&i.TransferID,
			&i.ExpenseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCashRegisters = `-- name: ListCashRegisters :many

select r.id, r.name, r.is_primary, r.is_active, s.id as open_session_id
from cash_registers r
left join register_sessions s on s.register_id = r.id and s.status = 'abierta'
where r.is_active
order by r.is_primary desc, r.name
`

type ListCashRegistersRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	IsPrimary     bool   `json:"is_primary"`
	IsActive      bool   `json:"is_active"`
	OpenSessionID *int64 `json:"open_session_id"`
}

// Cajas (registros físicos con nombre; la primaria recibe las ventas del POS)
// Cajas activas + el id de su sesión abierta (null si está cerrada). Para pickers y la vista de caja.
// LEFT JOIN (no subquery escalar) para que sqlc infiera open_session_id como nullable; el índice
// único one_open_session_per_register garantiza ≤1 sesión abierta por caja (sin duplicar filas).
func (q *Queries) ListCashRegisters(ctx context.Context) ([]ListCashRegistersRow, error) {
	rows, err := q.db.Query(ctx, listCashRegisters)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCashRegistersRow{}
	for rows.Next() {
		var i ListCashRegistersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.IsPrimary,
			&i.IsActive,
			&i.OpenSessionID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesBySession = `-- name: ListExpensesBySession :many
select ep.id, e.id as expense_id, ec.name as category, s.name as supplier,
       pm.name as payment_method, ep.amount, e.currency, e.status
from expense_payments ep
join expenses e on e.id = ep.expense_id
join expense_categories ec on ec.id = e.category_id
join payment_methods pm on pm.id = ep.payment_method_id
left join suppliers s on s.id = e.supplier_id
where ep.register_session_id = $1
order by ep.id
`

type ListExpensesBySessionRow struct {
	ID            int64           `json:"id"`
	ExpenseID     int64           `json:"expense_id"`
	Category      string          `json:"category"`
	Supplier      *string         `json:"supplier"`
	PaymentMethod string          `json:"payment_method"`
	Amount        decimal.Decimal `json:"amount"`
	Currency      string          `json:"currency"`
	Status        ExpenseStatus   `json:"status"`
}

// Gastos atribuidos a un corte (efectivo y no-efectivo): sección "Gastos" del resumen del corte.
//
// La atribución al corte pasó del encabezado del gasto a CADA PAGO (0029): un gasto con pago
// partido puede tocar dos cortes distintos, así que lo que se lista es el PAGO, y el importe
// que se muestra es el del pago, no el del gasto completo.
func (q *Queries) ListExpensesBySession(ctx context.Context, registerSessionID *int64) ([]ListExpensesBySessionRow, error) {
	rows, err := q.db.Query(ctx, listExpensesBySession, registerSessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListExpensesBySessionRow{}
	for rows.Next() {
		var i ListExpensesBySessionRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.Category,
			&i.Supplier,
			&i.PaymentMethod,
			&i.Amount,
			&i.Currency,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOpenSessions = `-- name: ListOpenSessions :many
select s.id, s.register_id, r.name as register_name, r.is_primary, s.opening_cash, s.currency, s.opened_at
from register_sessions s
join cash_registers r on r.id = s.register_id
where s.status = 'abierta'
order by r.is_primary desc, r.name
`

type ListOpenSessionsRow struct {
	ID           int64           `json:"id"`
	RegisterID   int64           `json:"register_id"`
	RegisterName string          `json:"register_name"`
	IsPrimary    bool            `json:"is_primary"`
	OpeningCash  decimal.Decimal `json:"opening_cash"`
	Currency     string          `json:"currency"`
	OpenedAt     time.Time       `json:"opened_at"`
}

// Todas las cajas abiertas (para el POS / aviso y validaciones de traspaso).
func (q *Queries) ListOpenSessions(ctx context.Context) ([]ListOpenSessionsRow, error) {
	rows, err := q.db.Query(ctx, listOpenSessions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOpenSessionsRow{}
	for rows.Next() {
		var i ListOpenSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.RegisterID,
			&i.RegisterName,
			&i.IsPrimary,
			&i.OpeningCash,
			&i.Currency,
			&i.OpenedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaymentMethods = `-- name: ListPaymentMethods :many

select id, name, kind, affects_cash_drawer, auto_declare from payment_methods where is_active order by sort_key, name
`

type ListPaymentMethodsRow struct {
	ID                int16       `json:"id"`
	Name              string      `json:"name"`
	Kind              PaymentKind `json:"kind"`
	AffectsCashDrawer bool        `json:"affects_cash_drawer"`
	AutoDeclare       bool        `json:"auto_declare"`
}

// Medios de pago (lookup)
func (q *Queries) ListPaymentMethods(ctx context.Context) ([]ListPaymentMethodsRow, error) {
	rows, err := q.db.Query(ctx, listPaymentMethods)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPaymentMethodsRow{}
	for rows.Next() {
		var i ListPaymentMethodsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Kind,
			&i.AffectsCashDrawer,
			&i.AutoDeclare,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessionTotals = `-- name: ListSessionTotals :many
select t.payment_method_id, pm.name, pm.kind, pm.affects_cash_drawer, t.expected, t.declared, t.tips,
       (t.declared - t.expected)::numeric(10,2) as difference
from register_session_totals t
join payment_methods pm on pm.id = t.payment_method_id
where t.session_id = $1
order by pm.sort_key
`

type ListSessionTotalsRow struct {
	PaymentMethodID   int16           `json:"payment_method_id"`
	Name              string          `json:"name"`
	Kind              PaymentKind     `json:"kind"`
	AffectsCashDrawer bool            `json:"affects_cash_drawer"`
	Expected          decimal.Decimal `json:"expected"`
	Declared          decimal.Decimal `json:"declared"`
	Tips              decimal.Decimal `json:"tips"`
	Difference        decimal.Decimal `json:"difference"`
}

func (q *Queries) ListSessionTotals(ctx context.Context, sessionID int64) ([]ListSessionTotalsRow, error) {
	rows, err := q.db.Query(ctx, listSessionTotals, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionTotalsRow{}
	for rows.Next() {
		var i ListSessionTotalsRow
		if err := rows.Scan(
			&i.PaymentMethodID,
			&i.Name,
			&i.Kind,
			&i.AffectsCashDrawer,
			&i.Expected,
			&i.Declared,
			&i.Tips,
			&i.Difference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSessions = `-- name: ListSessions :many
select s.id, s.business_date, s.status, s.opening_cash, s.currency, s.opened_at, s.closed_at, s.notes,
       r.name as register_name,
       ob.name as opened_by_name, cb.name as closed_by_name,
       coalesce((select sum(difference) from register_session_totals t where t.session_id = s.id), 0)::numeric(10,2) as total_difference
from register_sessions s
join cash_registers r on r.id = s.register_id
join users ob on ob.id = s.opened_by
left join users cb on cb.id = s.closed_by
order by s.opened_at desc limit $1
`

type ListSessionsRow struct {
	ID              int64              `json:"id"`
	BusinessDate    pgtype.Date        `json:"business_date"`
	Status          SessionStatus      `json:"status"`
	OpeningCash     decimal.Decimal    `json:"opening_cash"`
	Currency        string             `json:"currency"`
	OpenedAt        time.Time          `json:"opened_at"`
	ClosedAt        pgtype.Timestamptz `json:"closed_at"`
	Notes           *string            `json:"notes"`
	RegisterName    string             `json:"register_name"`
	OpenedByName    string             `json:"opened_by_name"`
	ClosedByName    *string            `json:"closed_by_name"`
	TotalDifference decimal.Decimal    `json:"total_difference"`
}

func (q *Queries) ListSessions(ctx context.Context, limit int32) ([]ListSessionsRow, error) {
	rows, err := q.db.Query(ctx, listSessions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSessionsRow{}
	for rows.Next() {
		var i ListSessionsRow
		if err := rows.Scan(
			&i.ID,
			&i.BusinessDate,
			&i.Status,
			&i.OpeningCash,
			&i.Currency,
			&i.OpenedAt,
			&i.ClosedAt,
			&i.Notes,
			&i.RegisterName,
			&i.OpenedByName,
			&i.ClosedByName,
			&i.TotalDifference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const netCashMovements = `-- name: NetCashMovements :one
select coalesce(sum(case when kind = 'entrada' then amount else -amount end), 0)::numeric(10,2) as net
from register_cash_movements where session_id = $1
`

// Neto de efectivo movido en la sesión (entradas − salidas); suma al efectivo esperado al cerrar.
func (q *Queries) NetCashMovements(ctx context.Context, sessionID int64) (decimal.Decimal, error) {
	row := q.db.QueryRow(ctx, netCashMovements, sessionID)
	var net decimal.Decimal
	err := row.Scan(&net)
	return net, err
}

const openSession = `-- name: OpenSession :one
insert into register_sessions (business_date, opening_cash, opened_by, register_id)
values ($1, $2, $3, $4)
returning id, business_date, status, opening_cash, opened_by, opened_at, closed_by, closed_at, notes, currency, register_id
`

type OpenSessionParams struct {
	BusinessDate pgtype.Date     `json:"business_date"`
	OpeningCash  decimal.Decimal `json:"opening_cash"`
	OpenedBy     int64           `json:"opened_by"`
	RegisterID   int64           `json:"register_id"`
}

func (q *Queries) OpenSession(ctx context.Context, arg OpenSessionParams) (RegisterSession, error) {
	row := q.db.QueryRow(ctx, openSession,
		arg.BusinessDate,
		arg.OpeningCash,
		arg.OpenedBy,
		arg.RegisterID,
	)
	var i RegisterSession
	err := row.Scan(
		&i.ID,
		&i.BusinessDate,
		&i.Status,
		&i.OpeningCash,
		&i.OpenedBy,
		&i.OpenedAt,
		&i.ClosedBy,
		&i.ClosedAt,
		&i.Notes,
		&i.Currency,
		&i.RegisterID,
	)
	return i, err
}

const saveSessionTotal = `-- name: SaveSessionTotal :exec
insert into register_session_totals (session_id, payment_method_id, expected, declared, tips)
values ($1, $2, $3, $4, $5)
`

type SaveSessionTotalParams struct {
	SessionID       int64           `json:"session_id"`
	PaymentMethodID int16           `json:"payment_method_id"`
	Expected        decimal.Decimal `json:"expected"`
	Declared        decimal.Decimal `json:"declared"`
	Tips            decimal.Decimal `json:"tips"`
}

func (q *Queries) SaveSessionTotal(ctx context.Context, arg SaveSessionTotalParams) error {
	_, err := q.db.Exec(ctx, saveSessionTotal,
		arg.SessionID,
		arg.PaymentMethodID,
		arg.Expected,
		arg.Declared,
		arg.Tips,
	)
	return err
}

const seedBasePaymentMethods = `-- name: SeedBasePaymentMethods :exec
insert into payment_methods (company_id, name, kind, affects_cash_drawer, is_active, sort_key, auto_declare)
values
  ($1, 'Efectivo',           'efectivo',      true,  true, 100, false),
  ($1, 'Tarjeta débito',     'tarjeta',       false, true, 200, true),
  ($1, 'Tarjeta crédito',    'tarjeta',       false, true, 250, true),
  ($1, 'Transferencia SPEI', 'transferencia', false, true, 300, true)
on conflict (company_id, name) do nothing
`

// Métodos de pago base para una empresa recién creada. Desde 0037 la tabla es per-tenant, así que
// una empresa nueva nace SIN NINGUNO y no podría cobrar: /payment-methods devolvería vacío y el
// checkout se quedaría sin botones. Antes los heredaba por ser una tabla global.
//
// Los de PLATAFORMA quedan fuera a propósito: vender por Uber/DiDi/Rappi exige que ese negocio haya
// hecho su propia vinculación con la plataforma, y darle tres formas de cobro que no tiene
// contratadas es peor que no darle ninguna.
func (q *Queries) SeedBasePaymentMethods(ctx context.Context, companyID int64) error {
	_, err := q.db.Exec(ctx, seedBasePaymentMethods, companyID)
	return err
}

const updateCashRegister = `-- name: UpdateCashRegister :one
update cash_registers set name = $2, is_active = $3 where id = $1
returning id, name, is_primary, is_active
`

type UpdateCashRegisterParams struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
}

type UpdateCashRegisterRow struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	IsPrimary bool   `json:"is_primary"`
	IsActive  bool   `json:"is_active"`
}

func (q *Queries) UpdateCashRegister(ctx context.Context, arg UpdateCashRegisterParams) (UpdateCashRegisterRow, error) {
	row := q.db.QueryRow(ctx, updateCashRegister, arg.ID, arg.Name, arg.IsActive)
	var i UpdateCashRegisterRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.IsPrimary,
		&i.IsActive,
	)
	return i, err
}

const updatePaymentMethodAutoDeclare = `-- name: UpdatePaymentMethodAutoDeclare :one
update payment_methods set auto_declare = $2 where id = $1
returning id, name, kind, affects_cash_drawer, auto_declare
`

type UpdatePaymentMethodAutoDeclareParams struct {
	ID          int16 `json:"id"`
	AutoDeclare bool  `json:"auto_declare"`
}

type UpdatePaymentMethodAutoDeclareRow struct {
	ID                int16       `json:"id"`
	Name              string      `json:"name"`
	Kind              PaymentKind `json:"kind"`
	AffectsCashDrawer bool        `json:"affects_cash_drawer"`
	AutoDeclare       bool        `json:"auto_declare"`
}

func (q *Queries) UpdatePaymentMethodAutoDeclare(ctx context.Context, arg UpdatePaymentMethodAutoDeclareParams) (UpdatePaymentMethodAutoDeclareRow, error) {
	row := q.db.QueryRow(ctx, updatePaymentMethodAutoDeclare, arg.ID, arg.AutoDeclare)
	var i UpdatePaymentMethodAutoDeclareRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Kind,
		&i.AffectsCashDrawer,
		&i.AutoDeclare,
	)
	return i, err
}
