// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: cash_concepts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const archiveCashConcept = `-- name: ArchiveCashConcept :execrows
update cash_concepts set archived_at = now() where id = $1 and archived_at is null
`

func (q *Queries) ArchiveCashConcept(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCashConcept, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findActiveCashConceptByName = `-- name: FindActiveCashConceptByName :one
select id, name from cash_concepts where archived_at is null and lower(name) = lower($1::text)
`

type FindActiveCashConceptByNameRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) FindActiveCashConceptByName(ctx context.Context, name string) (FindActiveCashConceptByNameRow, error) {
	row := q.db.QueryRow(ctx, findActiveCashConceptByName, name)
	var i FindActiveCashConceptByNameRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const getCashConcept = `-- name: GetCashConcept :one
select id, name, archived_at from cash_concepts where id = $1
`

type GetCashConceptRow struct {
	ID         int64              `json:"id"`
	Name       string             `json:"name"`
	ArchivedAt pgtype.Timestamptz `json:"archived_at"`
}

func (q *Queries) GetCashConcept(ctx context.Context, id int64) (GetCashConceptRow, error) {
	row := q.db.QueryRow(ctx, getCashConcept, id)
	var i GetCashConceptRow
	err := row.Scan(&i.ID, &i.Name, &i.ArchivedAt)
	return i, err
}

const getMovementForCorrection = `-- name: GetMovementForCorrection :one
select m.id, m.kind, m.amount, m.concept, m.session_id, s.register_id,
       (m.expense_id is not null)::boolean as is_expense,
       (m.transfer_id is not null)::boolean as is_transfer,
       exists (select 1 from order_refunds r where r.cash_movement_id = m.id) as is_refund,
       exists (select 1 from register_cash_movements x where x.reverses_id = m.id) as already_reversed
  from register_cash_movements m
  join register_sessions s on s.id = m.session_id
 where m.id = $1
 for update of m
`

type GetMovementForCorrectionRow struct {
	ID              int64           `json:"id"`
	Kind            string          `json:"kind"`
	Amount          decimal.Decimal `json:"amount"`
	Concept         string          `json:"concept"`
	SessionID       int64           `json:"session_id"`
	RegisterID      int64           `json:"register_id"`
	IsExpense       bool            `json:"is_expense"`
	IsTransfer      bool            `json:"is_transfer"`
	IsRefund        bool            `json:"is_refund"`
	AlreadyReversed bool            `json:"already_reversed"`
}

// La salida que se corrige, con lo que decide si se puede: su caja (para el turno abierto donde cae
// el reverso) y si ya tiene reverso.
func (q *Queries) GetMovementForCorrection(ctx context.Context, id int64) (GetMovementForCorrectionRow, error) {
	row := q.db.QueryRow(ctx, getMovementForCorrection, id)
	var i GetMovementForCorrectionRow
	err := row.Scan(
		&i.ID,
		&i.Kind,
		&i.Amount,
		&i.Concept,
		&i.SessionID,
		&i.RegisterID,
		&i.IsExpense,
		&i.IsTransfer,
		&i.IsRefund,
		&i.AlreadyReversed,
	)
	return i, err
}

const insertCashConcept = `-- name: InsertCashConcept :one
insert into cash_concepts (name) values ($1) returning id, name
`

type InsertCashConceptRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) InsertCashConcept(ctx context.Context, name string) (InsertCashConceptRow, error) {
	row := q.db.QueryRow(ctx, insertCashConcept, name)
	var i InsertCashConceptRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertCashOut = `-- name: InsertCashOut :one
insert into register_cash_movements (session_id, kind, amount, concept, user_id, concept_id)
values ($1, 'salida', $2, $3, $4, $5)
returning id
`

type InsertCashOutParams struct {
	SessionID int64           `json:"session_id"`
	Amount    decimal.Decimal `json:"amount"`
	Concept   string          `json:"concept"`
	UserID    int64           `json:"user_id"`
	ConceptID *int64          `json:"concept_id"`
}

func (q *Queries) InsertCashOut(ctx context.Context, arg InsertCashOutParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCashOut,
		arg.SessionID,
		arg.Amount,
		arg.Concept,
		arg.UserID,
		arg.ConceptID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertCashReversal = `-- name: InsertCashReversal :one
insert into register_cash_movements (session_id, kind, amount, concept, user_id, reverses_id)
values ($1, 'reverso', $2, $3, $4, $5)
returning id
`

type InsertCashReversalParams struct {
	SessionID  int64           `json:"session_id"`
	Amount     decimal.Decimal `json:"amount"`
	Concept    string          `json:"concept"`
	UserID     int64           `json:"user_id"`
	ReversesID *int64          `json:"reverses_id"`
}

func (q *Queries) InsertCashReversal(ctx context.Context, arg InsertCashReversalParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertCashReversal,
		arg.SessionID,
		arg.Amount,
		arg.Concept,
		arg.UserID,
		arg.ReversesID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listCashConcepts = `-- name: ListCashConcepts :many

select c.id, c.name, c.expense_category_id, c.supplier_id, ec.name as category_name, sp.name as supplier_name
  from cash_concepts c
  left join expense_categories ec on ec.id = c.expense_category_id
  left join suppliers sp on sp.id = c.supplier_id
 where c.archived_at is null
 order by lower(c.name)
`

type ListCashConceptsRow struct {
	ID                int64   `json:"id"`
	Name              string  `json:"name"`
	ExpenseCategoryID *int64  `json:"expense_category_id"`
	SupplierID        *int64  `json:"supplier_id"`
	CategoryName      *string `json:"category_name"`
	SupplierName      *string `json:"supplier_name"`
}

// Conceptos de salida de caja (spec 032, punto 3). RLS acota a la empresa.
func (q *Queries) ListCashConcepts(ctx context.Context) ([]ListCashConceptsRow, error) {
	rows, err := q.db.Query(ctx, listCashConcepts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCashConceptsRow{}
	for rows.Next() {
		var i ListCashConceptsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ExpenseCategoryID,
			&i.SupplierID,
			&i.CategoryName,
			&i.SupplierName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const mergeCashConcept = `-- name: MergeCashConcept :execrows
update cash_concepts set archived_at = now(), merged_into_id = $1
 where id = $2 and archived_at is null
`

type MergeCashConceptParams struct {
	IntoID *int64 `json:"into_id"`
	ID     int64  `json:"id"`
}

// El duplicado queda archivado y apuntando al que queda; sus salidas pasan a ese concepto.
func (q *Queries) MergeCashConcept(ctx context.Context, arg MergeCashConceptParams) (int64, error) {
	result, err := q.db.Exec(ctx, mergeCashConcept, arg.IntoID, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const moveCashOutsToConcept = `-- name: MoveCashOutsToConcept :exec
update register_cash_movements set concept_id = $1 where concept_id = $2
`

type MoveCashOutsToConceptParams struct {
	IntoID *int64 `json:"into_id"`
	FromID *int64 `json:"from_id"`
}

func (q *Queries) MoveCashOutsToConcept(ctx context.Context, arg MoveCashOutsToConceptParams) error {
	_, err := q.db.Exec(ctx, moveCashOutsToConcept, arg.IntoID, arg.FromID)
	return err
}

const updateCashConcept = `-- name: UpdateCashConcept :one
update cash_concepts set name = $2, expense_category_id = $3,
       supplier_id = $4
 where id = $1 and archived_at is null
returning id, name
`

type UpdateCashConceptParams struct {
	ID                int64  `json:"id"`
	Name              string `json:"name"`
	ExpenseCategoryID *int64 `json:"expense_category_id"`
	SupplierID        *int64 `json:"supplier_id"`
}

type UpdateCashConceptRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) UpdateCashConcept(ctx context.Context, arg UpdateCashConceptParams) (UpdateCashConceptRow, error) {
	row := q.db.QueryRow(ctx, updateCashConcept,
		arg.ID,
		arg.Name,
		arg.ExpenseCategoryID,
		arg.SupplierID,
	)
	var i UpdateCashConceptRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
