// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: composition.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const insertOrderLineComponent = `-- name: InsertOrderLineComponent :exec
insert into order_line_components (order_line_id, product_id, quantity) values ($1, $2, $3)
`

type InsertOrderLineComponentParams struct {
	OrderLineID int64           `json:"order_line_id"`
	ProductID   int64           `json:"product_id"`
	Quantity    decimal.Decimal `json:"quantity"`
}

// Lo que se vendió dentro de un paquete, copiado al vender: editar el paquete después no reescribe
// el historial.
func (q *Queries) InsertOrderLineComponent(ctx context.Context, arg InsertOrderLineComponentParams) error {
	_, err := q.db.Exec(ctx, insertOrderLineComponent, arg.OrderLineID, arg.ProductID, arg.Quantity)
	return err
}

const listProductsForStock = `-- name: ListProductsForStock :many
select id, type, track_stock, recipe_id from products
`

type ListProductsForStockRow struct {
	ID         int64       `json:"id"`
	Type       ProductType `json:"type"`
	TrackStock bool        `json:"track_stock"`
	RecipeID   *int64      `json:"recipe_id"`
}

// Lo mínimo de cada producto para saber qué descuenta al venderse (spec 028). Sin filtro de empresa:
// lo pone RLS.
func (q *Queries) ListProductsForStock(ctx context.Context) ([]ListProductsForStockRow, error) {
	rows, err := q.db.Query(ctx, listProductsForStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsForStockRow{}
	for rows.Next() {
		var i ListProductsForStockRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TrackStock,
			&i.RecipeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
