// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: composition.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const confirmIngredientComposition = `-- name: ConfirmIngredientComposition :execrows
update ingredients set composition_status = 'confirmed', composition_confirmed_by = $2, composition_confirmed_at = now()
 where id = $1 and composition_status = 'estimated'
`

type ConfirmIngredientCompositionParams struct {
	ID                     int64  `json:"id"`
	CompositionConfirmedBy *int64 `json:"composition_confirmed_by"`
}

func (q *Queries) ConfirmIngredientComposition(ctx context.Context, arg ConfirmIngredientCompositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmIngredientComposition, arg.ID, arg.CompositionConfirmedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmOptionComposition = `-- name: ConfirmOptionComposition :execrows
update modifier_options set composition_status = 'confirmed', composition_confirmed_by = $2, composition_confirmed_at = now()
 where id = $1 and composition_status is distinct from 'confirmed'
`

type ConfirmOptionCompositionParams struct {
	ID                     int64  `json:"id"`
	CompositionConfirmedBy *int64 `json:"composition_confirmed_by"`
}

func (q *Queries) ConfirmOptionComposition(ctx context.Context, arg ConfirmOptionCompositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmOptionComposition, arg.ID, arg.CompositionConfirmedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const confirmProductComposition = `-- name: ConfirmProductComposition :execrows
update products set composition_status = 'confirmed', composition_confirmed_by = $2, composition_confirmed_at = now()
 where id = $1 and composition_status is distinct from 'confirmed'
`

type ConfirmProductCompositionParams struct {
	ID                     int64  `json:"id"`
	CompositionConfirmedBy *int64 `json:"composition_confirmed_by"`
}

// Confirmar sin composición es decidir «no lleva nada que se descuente» (un «Sin hielo»): así deja
// de salir en «sin capturar», y lo pendiente no se confunde con lo decidido.
func (q *Queries) ConfirmProductComposition(ctx context.Context, arg ConfirmProductCompositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmProductComposition, arg.ID, arg.CompositionConfirmedBy)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const createCompositionRecipe = `-- name: CreateCompositionRecipe :one
insert into recipes default values returning id
`

// Receta nueva en cada captura y no editar la que había: `recipe_id` es único por tabla, pero un
// producto y un extra cargados de FUDO pueden apuntar a la misma, y editarla en su lugar cambiaría
// lo que descuenta el otro sin que nadie lo viera.
func (q *Queries) CreateCompositionRecipe(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, createCompositionRecipe)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deletePackageSlots = `-- name: DeletePackageSlots :exec
delete from combo_slots where combo_id = $1
`

// Los productos de cada hueco se van en cascada.
func (q *Queries) DeletePackageSlots(ctx context.Context, comboID int64) error {
	_, err := q.db.Exec(ctx, deletePackageSlots, comboID)
	return err
}

const getIngredientComposition = `-- name: GetIngredientComposition :one
select i.id, i.is_prep, i.recipe_id, i.yield_qty, bu.code as base_unit_code,
       i.composition_status, i.composition_confirmed_at, u.name as confirmed_by_name
  from ingredients i
  join units bu on bu.id = i.base_unit_id
  left join users u on u.id = i.composition_confirmed_by
 where i.id = $1
`

type GetIngredientCompositionRow struct {
	ID                     int64              `json:"id"`
	IsPrep                 bool               `json:"is_prep"`
	RecipeID               *int64             `json:"recipe_id"`
	YieldQty               *decimal.Decimal   `json:"yield_qty"`
	BaseUnitCode           string             `json:"base_unit_code"`
	CompositionStatus      *string            `json:"composition_status"`
	CompositionConfirmedAt pgtype.Timestamptz `json:"composition_confirmed_at"`
	ConfirmedByName        *string            `json:"confirmed_by_name"`
}

func (q *Queries) GetIngredientComposition(ctx context.Context, id int64) (GetIngredientCompositionRow, error) {
	row := q.db.QueryRow(ctx, getIngredientComposition, id)
	var i GetIngredientCompositionRow
	err := row.Scan(
		&i.ID,
		&i.IsPrep,
		&i.RecipeID,
		&i.YieldQty,
		&i.BaseUnitCode,
		&i.CompositionStatus,
		&i.CompositionConfirmedAt,
		&i.ConfirmedByName,
	)
	return i, err
}

const getLinkableProduct = `-- name: GetLinkableProduct :one
select id, type, name::text as name from products where id = $1
`

type GetLinkableProductRow struct {
	ID   int64       `json:"id"`
	Type ProductType `json:"type"`
	Name string      `json:"name"`
}

func (q *Queries) GetLinkableProduct(ctx context.Context, id int64) (GetLinkableProductRow, error) {
	row := q.db.QueryRow(ctx, getLinkableProduct, id)
	var i GetLinkableProductRow
	err := row.Scan(&i.ID, &i.Type, &i.Name)
	return i, err
}

const getOptionComposition = `-- name: GetOptionComposition :one
select o.id, o.recipe_id, o.linked_product_id, lp.name as linked_product_name,
       o.composition_status, o.composition_confirmed_at, u.name as confirmed_by_name
  from modifier_options o
  left join products lp on lp.id = o.linked_product_id
  left join users u on u.id = o.composition_confirmed_by
 where o.id = $1
`

type GetOptionCompositionRow struct {
	ID                     int64              `json:"id"`
	RecipeID               *int64             `json:"recipe_id"`
	LinkedProductID        *int64             `json:"linked_product_id"`
	LinkedProductName      *string            `json:"linked_product_name"`
	CompositionStatus      *string            `json:"composition_status"`
	CompositionConfirmedAt pgtype.Timestamptz `json:"composition_confirmed_at"`
	ConfirmedByName        *string            `json:"confirmed_by_name"`
}

func (q *Queries) GetOptionComposition(ctx context.Context, id int64) (GetOptionCompositionRow, error) {
	row := q.db.QueryRow(ctx, getOptionComposition, id)
	var i GetOptionCompositionRow
	err := row.Scan(
		&i.ID,
		&i.RecipeID,
		&i.LinkedProductID,
		&i.LinkedProductName,
		&i.CompositionStatus,
		&i.CompositionConfirmedAt,
		&i.ConfirmedByName,
	)
	return i, err
}

const getProductComposition = `-- name: GetProductComposition :one
select p.id, p.type, p.track_stock, p.recipe_id, p.composition_status, p.composition_confirmed_at,
       u.name as confirmed_by_name
  from products p left join users u on u.id = p.composition_confirmed_by
 where p.id = $1
`

type GetProductCompositionRow struct {
	ID                     int64              `json:"id"`
	Type                   ProductType        `json:"type"`
	TrackStock             bool               `json:"track_stock"`
	RecipeID               *int64             `json:"recipe_id"`
	CompositionStatus      *string            `json:"composition_status"`
	CompositionConfirmedAt pgtype.Timestamptz `json:"composition_confirmed_at"`
	ConfirmedByName        *string            `json:"confirmed_by_name"`
}

func (q *Queries) GetProductComposition(ctx context.Context, id int64) (GetProductCompositionRow, error) {
	row := q.db.QueryRow(ctx, getProductComposition, id)
	var i GetProductCompositionRow
	err := row.Scan(
		&i.ID,
		&i.Type,
		&i.TrackStock,
		&i.RecipeID,
		&i.CompositionStatus,
		&i.CompositionConfirmedAt,
		&i.ConfirmedByName,
	)
	return i, err
}

const insertCompositionItem = `-- name: InsertCompositionItem :exec
insert into recipe_items (recipe_id, ingredient_id, quantity, unit_id, position) values ($1, $2, $3, $4, $5)
`

type InsertCompositionItemParams struct {
	RecipeID     int64           `json:"recipe_id"`
	IngredientID int64           `json:"ingredient_id"`
	Quantity     decimal.Decimal `json:"quantity"`
	UnitID       int16           `json:"unit_id"`
	Position     int32           `json:"position"`
}

func (q *Queries) InsertCompositionItem(ctx context.Context, arg InsertCompositionItemParams) error {
	_, err := q.db.Exec(ctx, insertCompositionItem,
		arg.RecipeID,
		arg.IngredientID,
		arg.Quantity,
		arg.UnitID,
		arg.Position,
	)
	return err
}

const insertOrderLineComponent = `-- name: InsertOrderLineComponent :exec
insert into order_line_components (order_line_id, product_id, quantity) values ($1, $2, $3)
`

type InsertOrderLineComponentParams struct {
	OrderLineID int64           `json:"order_line_id"`
	ProductID   int64           `json:"product_id"`
	Quantity    decimal.Decimal `json:"quantity"`
}

// Lo que se vendió dentro de un paquete, copiado al vender: editar el paquete después no reescribe
// el historial.
func (q *Queries) InsertOrderLineComponent(ctx context.Context, arg InsertOrderLineComponentParams) error {
	_, err := q.db.Exec(ctx, insertOrderLineComponent, arg.OrderLineID, arg.ProductID, arg.Quantity)
	return err
}

const insertPackageSlot = `-- name: InsertPackageSlot :one
insert into combo_slots (combo_id, name, min_select, max_select, position)
values ($1, $2, $3, $3, $4)
returning id
`

type InsertPackageSlotParams struct {
	ComboID  int64  `json:"combo_id"`
	Name     string `json:"name"`
	Quantity int16  `json:"quantity"`
	Position int32  `json:"position"`
}

// Un hueco por producto, con un solo producto: min = max = las piezas que lleva.
func (q *Queries) InsertPackageSlot(ctx context.Context, arg InsertPackageSlotParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertPackageSlot,
		arg.ComboID,
		arg.Name,
		arg.Quantity,
		arg.Position,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertPackageSlotProduct = `-- name: InsertPackageSlotProduct :exec
insert into combo_slot_products (slot_id, product_id, is_default) values ($1, $2, true)
`

type InsertPackageSlotProductParams struct {
	SlotID    int64 `json:"slot_id"`
	ProductID int64 `json:"product_id"`
}

func (q *Queries) InsertPackageSlotProduct(ctx context.Context, arg InsertPackageSlotProductParams) error {
	_, err := q.db.Exec(ctx, insertPackageSlotProduct, arg.SlotID, arg.ProductID)
	return err
}

const isPackageComponent = `-- name: IsPackageComponent :one
select exists (select 1 from combo_slot_products where product_id = $1)::boolean as used
`

// Si el producto va dentro de algún paquete: entonces no puede volverse paquete él mismo.
func (q *Queries) IsPackageComponent(ctx context.Context, productID int64) (bool, error) {
	row := q.db.QueryRow(ctx, isPackageComponent, productID)
	var used bool
	err := row.Scan(&used)
	return used, err
}

const listCompositionItems = `-- name: ListCompositionItems :many
select ri.ingredient_id, i.name as ingredient_name, ri.quantity, ri.unit_id, u.code as unit_code
  from recipe_items ri
  join ingredients i on i.id = ri.ingredient_id
  join units u on u.id = ri.unit_id
 where ri.recipe_id = $1
 order by ri.position, ri.id
`

type ListCompositionItemsRow struct {
	IngredientID   int64           `json:"ingredient_id"`
	IngredientName string          `json:"ingredient_name"`
	Quantity       decimal.Decimal `json:"quantity"`
	UnitID         int16           `json:"unit_id"`
	UnitCode       string          `json:"unit_code"`
}

func (q *Queries) ListCompositionItems(ctx context.Context, recipeID int64) ([]ListCompositionItemsRow, error) {
	rows, err := q.db.Query(ctx, listCompositionItems, recipeID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCompositionItemsRow{}
	for rows.Next() {
		var i ListCompositionItemsRow
		if err := rows.Scan(
			&i.IngredientID,
			&i.IngredientName,
			&i.Quantity,
			&i.UnitID,
			&i.UnitCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIngredientUnitKinds = `-- name: ListIngredientUnitKinds :many
select i.id, u.kind::text as kind
  from ingredients i join units u on u.id = i.base_unit_id
 where i.id = any($1::bigint[])
`

type ListIngredientUnitKindsRow struct {
	ID   int64  `json:"id"`
	Kind string `json:"kind"`
}

// El tipo de unidad base de cada insumo. Uno de otra empresa no sale (RLS), y eso es lo que impide
// ligarlo: la FK de recipe_items es simple.
func (q *Queries) ListIngredientUnitKinds(ctx context.Context, ids []int64) ([]ListIngredientUnitKindsRow, error) {
	rows, err := q.db.Query(ctx, listIngredientUnitKinds, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListIngredientUnitKindsRow{}
	for rows.Next() {
		var i ListIngredientUnitKindsRow
		if err := rows.Scan(&i.ID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPackageComponents = `-- name: ListPackageComponents :many
select csp.product_id, p.name::text as product_name, cs.min_select
  from combo_slots cs
  join combo_slot_products csp on csp.slot_id = cs.id and csp.is_default
  join products p on p.id = csp.product_id
 where cs.combo_id = $1
 order by cs.position, cs.id
`

type ListPackageComponentsRow struct {
	ProductID   int64  `json:"product_id"`
	ProductName string `json:"product_name"`
	MinSelect   int16  `json:"min_select"`
}

// Lo que lleva un paquete: el producto por omisión de cada hueco y cuántas piezas.
func (q *Queries) ListPackageComponents(ctx context.Context, comboID int64) ([]ListPackageComponentsRow, error) {
	rows, err := q.db.Query(ctx, listPackageComponents, comboID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPackageComponentsRow{}
	for rows.Next() {
		var i ListPackageComponentsRow
		if err := rows.Scan(&i.ProductID, &i.ProductName, &i.MinSelect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductsForStock = `-- name: ListProductsForStock :many
select id, type, track_stock, recipe_id from products
`

type ListProductsForStockRow struct {
	ID         int64       `json:"id"`
	Type       ProductType `json:"type"`
	TrackStock bool        `json:"track_stock"`
	RecipeID   *int64      `json:"recipe_id"`
}

// Lo mínimo de cada producto para saber qué descuenta al venderse (spec 028). Sin filtro de empresa:
// lo pone RLS.
func (q *Queries) ListProductsForStock(ctx context.Context) ([]ListProductsForStockRow, error) {
	rows, err := q.db.Query(ctx, listProductsForStock)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductsForStockRow{}
	for rows.Next() {
		var i ListProductsForStockRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.TrackStock,
			&i.RecipeID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitKinds = `-- name: ListUnitKinds :many
select id, kind::text as kind from units where id = any($1::smallint[])
`

type ListUnitKindsRow struct {
	ID   int16  `json:"id"`
	Kind string `json:"kind"`
}

func (q *Queries) ListUnitKinds(ctx context.Context, ids []int16) ([]ListUnitKindsRow, error) {
	rows, err := q.db.Query(ctx, listUnitKinds, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitKindsRow{}
	for rows.Next() {
		var i ListUnitKindsRow
		if err := rows.Scan(&i.ID, &i.Kind); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lockCompositionEdits = `-- name: LockCompositionEdits :exec
select pg_advisory_xact_lock(28028, coalesce(nullif(current_setting('app.company_id', true), '')::int, 0))
`

// Una captura de composición a la vez por empresa, hasta el fin de la transacción. Las reglas
// (paquete dentro de paquete, insumo circular) miran a otros productos e insumos: validadas sin
// este candado, dos capturas cruzadas pasaban las dos. Capturar es raro; esperar unos
// milisegundos no le cuesta nada a nadie.
func (q *Queries) LockCompositionEdits(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockCompositionEdits)
	return err
}

const packageHasChoices = `-- name: PackageHasChoices :one
select exists (
  select 1 from combo_slots cs
   where cs.combo_id = $1
     and (cs.min_select <> cs.max_select
          or (select count(*) from combo_slot_products csp where csp.slot_id = cs.id) > 1
          or not exists (select 1 from combo_slot_products csp where csp.slot_id = cs.id and csp.is_default))
)::boolean as has_choices
`

// Un paquete armado fuera de «Qué lleva» puede dejar elegir (un hueco con varios productos o con
// mínimo distinto del máximo) o tener un hueco sin producto por omisión, que «Qué lleva» no muestra.
// Reescribirlo con lo que se ve borraría esas opciones o ese hueco sin avisar.
func (q *Queries) PackageHasChoices(ctx context.Context, comboID int64) (bool, error) {
	row := q.db.QueryRow(ctx, packageHasChoices, comboID)
	var has_choices bool
	err := row.Scan(&has_choices)
	return has_choices, err
}

const setIngredientComposition = `-- name: SetIngredientComposition :execrows
update ingredients
   set is_prep = $1,
       recipe_id = $2,
       yield_qty = $3,
       composition_status = $4,
       composition_confirmed_by = $5,
       composition_confirmed_at = case when $4::text = 'confirmed' then now() end
 where id = $6
`

type SetIngredientCompositionParams struct {
	IsPrep      bool             `json:"is_prep"`
	RecipeID    *int64           `json:"recipe_id"`
	YieldQty    *decimal.Decimal `json:"yield_qty"`
	Status      *string          `json:"status"`
	ConfirmedBy *int64           `json:"confirmed_by"`
	ID          int64            `json:"id"`
}

// Preparado = con receta y rendimiento (check de 0003); sin receta vuelve a ser un insumo que se compra.
func (q *Queries) SetIngredientComposition(ctx context.Context, arg SetIngredientCompositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setIngredientComposition,
		arg.IsPrep,
		arg.RecipeID,
		arg.YieldQty,
		arg.Status,
		arg.ConfirmedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setOptionComposition = `-- name: SetOptionComposition :execrows
update modifier_options
   set recipe_id = $1,
       linked_product_id = $2,
       composition_status = $3,
       composition_confirmed_by = $4,
       composition_confirmed_at = case when $3::text = 'confirmed' then now() end
 where id = $5
`

type SetOptionCompositionParams struct {
	RecipeID        *int64  `json:"recipe_id"`
	LinkedProductID *int64  `json:"linked_product_id"`
	Status          *string `json:"status"`
	ConfirmedBy     *int64  `json:"confirmed_by"`
	ID              int64   `json:"id"`
}

func (q *Queries) SetOptionComposition(ctx context.Context, arg SetOptionCompositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setOptionComposition,
		arg.RecipeID,
		arg.LinkedProductID,
		arg.Status,
		arg.ConfirmedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setProductComposition = `-- name: SetProductComposition :execrows
update products
   set type = $1::product_type,
       recipe_id = $2,
       composition_status = $3,
       composition_confirmed_by = $4,
       composition_confirmed_at = case when $3::text = 'confirmed' then now() end
 where id = $5
`

type SetProductCompositionParams struct {
	ProductType ProductType `json:"product_type"`
	RecipeID    *int64      `json:"recipe_id"`
	Status      *string     `json:"status"`
	ConfirmedBy *int64      `json:"confirmed_by"`
	ID          int64       `json:"id"`
}

// El tipo va con la composición: un paquete es `combo` y no lleva receta (check de 0004).
func (q *Queries) SetProductComposition(ctx context.Context, arg SetProductCompositionParams) (int64, error) {
	result, err := q.db.Exec(ctx, setProductComposition,
		arg.ProductType,
		arg.RecipeID,
		arg.Status,
		arg.ConfirmedBy,
		arg.ID,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
