// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: daily_summary.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const claimSummarySend = `-- name: ClaimSummarySend :one
insert into daily_summary_sends (business_date, status, attempts) values ($1, 'pending', 1)
on conflict (company_id, business_date) do update
   set status = 'pending', attempts = daily_summary_sends.attempts + 1, last_error = null
 where daily_summary_sends.attempts < 5
   and (daily_summary_sends.status = 'failed'
        or (daily_summary_sends.status = 'pending' and daily_summary_sends.created_at < now() - interval '10 minutes'))
returning id
`

// La fila se toma ANTES de mandar: un reintento o una pasada paralela no manda dos veces. Solo se
// vuelve a tomar una fallida (o una pendiente que quedó colgada más de 10 minutos).
func (q *Queries) ClaimSummarySend(ctx context.Context, businessDate pgtype.Date) (int64, error) {
	row := q.db.QueryRow(ctx, claimSummarySend, businessDate)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const daySummaryCashOuts = `-- name: DaySummaryCashOuts :many
select coalesce(c.name, 'Sin concepto') as concept,
       (sum(m.amount) - coalesce(sum(rv.amount), 0))::numeric(12,2) as total
  from register_cash_movements m
  join register_sessions s on s.id = m.session_id
  left join cash_concepts c on c.id = m.concept_id
  left join register_cash_movements rv on rv.reverses_id = m.id
 where s.business_date = $1::date and s.status = 'cerrada' and m.kind = 'salida'
   and m.expense_id is null and m.transfer_id is null
   and not exists (select 1 from order_refunds r where r.cash_movement_id = m.id)
 group by coalesce(c.name, 'Sin concepto')
 order by 2 desc
`

type DaySummaryCashOutsRow struct {
	Concept string          `json:"concept"`
	Total   decimal.Decimal `json:"total"`
}

// Salidas a mano por concepto (sin gastos, traspasos, devoluciones ni propinas), netas de reversos.
func (q *Queries) DaySummaryCashOuts(ctx context.Context, day pgtype.Date) ([]DaySummaryCashOutsRow, error) {
	rows, err := q.db.Query(ctx, daySummaryCashOuts, day)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DaySummaryCashOutsRow{}
	for rows.Next() {
		var i DaySummaryCashOutsRow
		if err := rows.Scan(&i.Concept, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const daySummaryMoney = `-- name: DaySummaryMoney :one
with t as (
  select rs.id, rs.tips_carried_over from register_sessions rs where rs.business_date = $1::date and rs.status = 'cerrada'
), pagos as (
  select coalesce(sum(op.amount), 0) as ventas, coalesce(sum(op.tip_amount), 0) as propinas
    from order_payments op where op.register_session_id in (select id from t)
), mov as (
  select coalesce(sum(m.amount) filter (where m.kind = 'propina'), 0) as entregadas,
         count(*) filter (where m.kind = 'salida' and m.concept_id is null and m.expense_id is null
                          and m.transfer_id is null
                          and not exists (select 1 from order_refunds r where r.cash_movement_id = m.id)
                          and not exists (select 1 from register_cash_movements x where x.reverses_id = m.id)) as sin_concepto
    from register_cash_movements m where m.session_id in (select id from t)
), cajon as (
  select coalesce(sum(c.difference), 0) as diferencia
    from session_cash_counts c where c.moment = 'cierre' and c.session_id in (select id from t)
), term as (
  select coalesce(sum(declared - expected), 0) as diferencia from session_terminal_counts where session_id in (select id from t)
)
select (select count(*) from t)::int as shifts,
       pagos.ventas::numeric(12,2) as sales, pagos.propinas::numeric(12,2) as tips,
       mov.entregadas::numeric(12,2) as tips_paid_out,
       (select coalesce(sum(tips_carried_over), 0) from t)::numeric(12,2) as tips_pending,
       mov.sin_concepto::int as cash_outs_without_concept,
       cajon.diferencia::numeric(12,2) as drawer_difference,
       term.diferencia::numeric(12,2) as terminal_difference
  from pagos, mov, cajon, term
`

type DaySummaryMoneyRow struct {
	Shifts                 int32           `json:"shifts"`
	Sales                  decimal.Decimal `json:"sales"`
	Tips                   decimal.Decimal `json:"tips"`
	TipsPaidOut            decimal.Decimal `json:"tips_paid_out"`
	TipsPending            decimal.Decimal `json:"tips_pending"`
	CashOutsWithoutConcept int32           `json:"cash_outs_without_concept"`
	DrawerDifference       decimal.Decimal `json:"drawer_difference"`
	TerminalDifference     decimal.Decimal `json:"terminal_difference"`
}

// Las cifras del día, cada rama pre-agregada por su cuenta (1:N con los turnos). Ventas sin
// propinas; propinas cobradas, entregadas y por entregar aparte: no son del negocio.
func (q *Queries) DaySummaryMoney(ctx context.Context, day pgtype.Date) (DaySummaryMoneyRow, error) {
	row := q.db.QueryRow(ctx, daySummaryMoney, day)
	var i DaySummaryMoneyRow
	err := row.Scan(
		&i.Shifts,
		&i.Sales,
		&i.Tips,
		&i.TipsPaidOut,
		&i.TipsPending,
		&i.CashOutsWithoutConcept,
		&i.DrawerDifference,
		&i.TerminalDifference,
	)
	return i, err
}

const daysReadyForSummary = `-- name: DaysReadyForSummary :many
select distinct s.business_date
  from register_sessions s
 where s.status = 'cerrada' and s.business_date >= $1::date
   and not exists (select 1 from register_sessions o where o.status = 'abierta' and o.business_date = s.business_date)
   and not exists (select 1 from daily_summary_sends d
                    where d.business_date = s.business_date and (d.status = 'sent' or d.attempts >= 5))
 order by s.business_date
`

// Días de negocio recientes con al menos un turno cerrado, ninguno abierto, y sin resumen enviado ni
// agotado. Con dos cajas el día espera a que cierren las dos.
func (q *Queries) DaysReadyForSummary(ctx context.Context, since pgtype.Date) ([]pgtype.Date, error) {
	rows, err := q.db.Query(ctx, daysReadyForSummary, since)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []pgtype.Date{}
	for rows.Next() {
		var business_date pgtype.Date
		if err := rows.Scan(&business_date); err != nil {
			return nil, err
		}
		items = append(items, business_date)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSummaryEmails = `-- name: GetSummaryEmails :one

select daily_summary_emails from business_settings
`

// Resumen diario del cierre por correo (spec 032, punto 7). Todo bajo RLS: corre dentro de la
// transacción de UNA empresa.
func (q *Queries) GetSummaryEmails(ctx context.Context) ([]string, error) {
	row := q.db.QueryRow(ctx, getSummaryEmails)
	var daily_summary_emails []string
	err := row.Scan(&daily_summary_emails)
	return daily_summary_emails, err
}

const markSummaryFailed = `-- name: MarkSummaryFailed :exec
update daily_summary_sends set status = 'failed', last_error = left($2, 500) where id = $1
`

type MarkSummaryFailedParams struct {
	ID   int64  `json:"id"`
	Left string `json:"left"`
}

func (q *Queries) MarkSummaryFailed(ctx context.Context, arg MarkSummaryFailedParams) error {
	_, err := q.db.Exec(ctx, markSummaryFailed, arg.ID, arg.Left)
	return err
}

const markSummarySent = `-- name: MarkSummarySent :exec
update daily_summary_sends set status = 'sent', sent_at = now() where id = $1
`

func (q *Queries) MarkSummarySent(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markSummarySent, id)
	return err
}

const setSummaryEmails = `-- name: SetSummaryEmails :execrows
update business_settings set daily_summary_emails = $1, updated_at = now()
`

func (q *Queries) SetSummaryEmails(ctx context.Context, dailySummaryEmails []string) (int64, error) {
	result, err := q.db.Exec(ctx, setSummaryEmails, dailySummaryEmails)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}
