// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
insert into expenses (expense_date, category_id, supplier_id, amount, payment_method_id, description, created_by)
values ($1, $2, $3, $4, $5, $6, $7)
returning id
`

type CreateExpenseParams struct {
	ExpenseDate     pgtype.Date `json:"expense_date"`
	CategoryID      int64       `json:"category_id"`
	SupplierID      *int64      `json:"supplier_id"`
	Amount          float64     `json:"amount"`
	PaymentMethodID *int16      `json:"payment_method_id"`
	Description     *string     `json:"description"`
	CreatedBy       int64       `json:"created_by"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (int64, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.ExpenseDate,
		arg.CategoryID,
		arg.SupplierID,
		arg.Amount,
		arg.PaymentMethodID,
		arg.Description,
		arg.CreatedBy,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listExpenseCategories = `-- name: ListExpenseCategories :many
select id, name, financial_group from expense_categories where is_active order by financial_group, name
`

type ListExpenseCategoriesRow struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	FinancialGroup FinancialGroup `json:"financial_group"`
}

func (q *Queries) ListExpenseCategories(ctx context.Context) ([]ListExpenseCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listExpenseCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpenseCategoriesRow
	for rows.Next() {
		var i ListExpenseCategoriesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.FinancialGroup); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpenses = `-- name: ListExpenses :many
select e.id, e.expense_date, ec.name as category, ec.financial_group, s.name as supplier,
       e.amount, e.description
from expenses e
join expense_categories ec on ec.id = e.category_id
left join suppliers s on s.id = e.supplier_id
order by e.expense_date desc, e.id desc
limit $1
`

type ListExpensesRow struct {
	ID             int64          `json:"id"`
	ExpenseDate    pgtype.Date    `json:"expense_date"`
	Category       string         `json:"category"`
	FinancialGroup FinancialGroup `json:"financial_group"`
	Supplier       *string        `json:"supplier"`
	Amount         float64        `json:"amount"`
	Description    *string        `json:"description"`
}

func (q *Queries) ListExpenses(ctx context.Context, limit int32) ([]ListExpensesRow, error) {
	rows, err := q.db.Query(ctx, listExpenses, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListExpensesRow
	for rows.Next() {
		var i ListExpensesRow
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseDate,
			&i.Category,
			&i.FinancialGroup,
			&i.Supplier,
			&i.Amount,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSuppliers = `-- name: ListSuppliers :many
select id, name from suppliers where is_active order by name
`

type ListSuppliersRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

func (q *Queries) ListSuppliers(ctx context.Context) ([]ListSuppliersRow, error) {
	rows, err := q.db.Query(ctx, listSuppliers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSuppliersRow
	for rows.Next() {
		var i ListSuppliersRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
