// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: folios.sql

package db

import (
	"context"
)

const folioNamesConsumidos = `-- name: FolioNamesConsumidos :many
select name from folio_consumido where scheme = $1
`

// Los nombres que ya salieron en la vuelta en curso de este esquema.
//
// company_id no se nombra: lo pone RLS en el where y el DEFAULT en el insert, como en el resto del
// repo. La PK (company_id, scheme, name) cubre esta lectura entera.
func (q *Queries) FolioNamesConsumidos(ctx context.Context, scheme FolioScheme) ([]string, error) {
	rows, err := q.db.Query(ctx, folioNamesConsumidos, scheme)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []string{}
	for rows.Next() {
		var name string
		if err := rows.Scan(&name); err != nil {
			return nil, err
		}
		items = append(items, name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const folioSchemeDelNegocio = `-- name: FolioSchemeDelNegocio :one
select folio_scheme from business_settings limit 1
`

// Con qué se nombran los pedidos. RLS acota a la empresa actual, que tiene exactamente una fila.
//
// Un negocio SIN fila de ajustes no es un error: se cae al default del dominio, nunca a la otra
// lista. Quien llama trata pgx.ErrNoRows así.
func (q *Queries) FolioSchemeDelNegocio(ctx context.Context) (FolioScheme, error) {
	row := q.db.QueryRow(ctx, folioSchemeDelNegocio)
	var folio_scheme FolioScheme
	err := row.Scan(&folio_scheme)
	return folio_scheme, err
}

const marcarFolioConsumido = `-- name: MarcarFolioConsumido :exec
insert into folio_consumido (scheme, name) values ($1, $2)
on conflict do nothing
`

type MarcarFolioConsumidoParams struct {
	Scheme FolioScheme `json:"scheme"`
	Name   string      `json:"name"`
}

// Saca el nombre de la bolsa. `do nothing` porque dos cajas pueden sortear el mismo nombre a la vez:
// el índice único del día es el que decide quién se lo queda, y aquí anotar dos veces es inofensivo.
func (q *Queries) MarcarFolioConsumido(ctx context.Context, arg MarcarFolioConsumidoParams) error {
	_, err := q.db.Exec(ctx, marcarFolioConsumido, arg.Scheme, arg.Name)
	return err
}

const vaciarBolsaDeFolios = `-- name: VaciarBolsaDeFolios :exec
delete from folio_consumido where scheme = $1
`

// Se agotó la vuelta: todos los nombres del esquema salieron al menos una vez y empieza otra.
//
// Borra SOLO el esquema que se agotó. La bolsa del otro sigue donde iba: un negocio que prueba
// animales una semana y vuelve a razas no pierde su vuelta a medias.
func (q *Queries) VaciarBolsaDeFolios(ctx context.Context, scheme FolioScheme) error {
	_, err := q.db.Exec(ctx, vaciarBolsaDeFolios, scheme)
	return err
}
