// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menus_plataforma.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const clearCapturePrice = `-- name: ClearCapturePrice :exec
update platform_item_links set is_capture_price = false
where connection_id = $1
  and (product_id = $2 or modifier_option_id = $3)
`

type ClearCapturePriceParams struct {
	ConnectionID     int64  `json:"connection_id"`
	ProductID        *int64 `json:"product_id"`
	ModifierOptionID *int64 `json:"modifier_option_id"`
}

func (q *Queries) ClearCapturePrice(ctx context.Context, arg ClearCapturePriceParams) error {
	_, err := q.db.Exec(ctx, clearCapturePrice, arg.ConnectionID, arg.ProductID, arg.ModifierOptionID)
	return err
}

const confirmItemLinkProposal = `-- name: ConfirmItemLinkProposal :execrows
insert into platform_item_links (connection_id, external_id, kind, product_id, modifier_option_id,
                                 local_kind, confirmed_at, confirmed_by, is_capture_price)
values ($1, $2, $3, $4, $5,
        $6, now(), $7, $8)
on conflict (connection_id, external_id) do nothing
`

type ConfirmItemLinkProposalParams struct {
	ConnectionID     int64            `json:"connection_id"`
	ExternalID       string           `json:"external_id"`
	Kind             PlatformItemKind `json:"kind"`
	ProductID        *int64           `json:"product_id"`
	ModifierOptionID *int64           `json:"modifier_option_id"`
	LocalKind        string           `json:"local_kind"`
	ConfirmedBy      *int64           `json:"confirmed_by"`
	IsCapturePrice   bool             `json:"is_capture_price"`
}

// Confirma una propuesta del lote. `do nothing` si ya existe: dos personas confirmando a la vez
// dejan la misma fila. :execrows para saber si ESTA escribió, y no reportar como confirmado lo que
// ya estaba (quizá apuntando a otro producto).
func (q *Queries) ConfirmItemLinkProposal(ctx context.Context, arg ConfirmItemLinkProposalParams) (int64, error) {
	result, err := q.db.Exec(ctx, confirmItemLinkProposal,
		arg.ConnectionID,
		arg.ExternalID,
		arg.Kind,
		arg.ProductID,
		arg.ModifierOptionID,
		arg.LocalKind,
		arg.ConfirmedBy,
		arg.IsCapturePrice,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const countConnectionsOfPlatform = `-- name: CountConnectionsOfPlatform :one
select count(*) from platform_connections where delivery_platform_id = $1
`

// Más de una tienda de la misma plataforma impide copiar precios (ver domain.PriceSync).
func (q *Queries) CountConnectionsOfPlatform(ctx context.Context, deliveryPlatformID int16) (int64, error) {
	row := q.db.QueryRow(ctx, countConnectionsOfPlatform, deliveryPlatformID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countExclusionsOfConnection = `-- name: CountExclusionsOfConnection :one
select (select count(*) from platform_item_exclusions e where e.connection_id = $1)
     + (select count(*) from local_item_exclusions l where l.connection_id = $1)
`

// Para el aviso antes de borrar la tienda: las decisiones también se pierden.
func (q *Queries) CountExclusionsOfConnection(ctx context.Context, connectionID int64) (int32, error) {
	row := q.db.QueryRow(ctx, countExclusionsOfConnection, connectionID)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const countLinksOfConnection = `-- name: CountLinksOfConnection :one
select count(*) from platform_item_links where connection_id = $1
`

// Cuántas parejas se pierden al dar de baja la tienda. La pantalla lo dice ANTES de confirmar:
// son decisiones manuales de una sesión completa y no se reconstruyen.
func (q *Queries) CountLinksOfConnection(ctx context.Context, connectionID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLinksOfConnection, connectionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createPlatformConnection = `-- name: CreatePlatformConnection :one
insert into platform_connections (delivery_platform_id, external_store_id, label)
values ($1, $2, $3)
returning id
`

type CreatePlatformConnectionParams struct {
	DeliveryPlatformID int16  `json:"delivery_platform_id"`
	ExternalStoreID    string `json:"external_store_id"`
	Label              string `json:"label"`
}

func (q *Queries) CreatePlatformConnection(ctx context.Context, arg CreatePlatformConnectionParams) (int64, error) {
	row := q.db.QueryRow(ctx, createPlatformConnection, arg.DeliveryPlatformID, arg.ExternalStoreID, arg.Label)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const deleteItemExclusion = `-- name: DeleteItemExclusion :execrows
delete from platform_item_exclusions where connection_id = $1 and external_id = $2
`

type DeleteItemExclusionParams struct {
	ConnectionID int64  `json:"connection_id"`
	ExternalID   string `json:"external_id"`
}

func (q *Queries) DeleteItemExclusion(ctx context.Context, arg DeleteItemExclusionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItemExclusion, arg.ConnectionID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteItemLink = `-- name: DeleteItemLink :execrows
delete from platform_item_links where connection_id = $1 and external_id = $2
`

type DeleteItemLinkParams struct {
	ConnectionID int64  `json:"connection_id"`
	ExternalID   string `json:"external_id"`
}

func (q *Queries) DeleteItemLink(ctx context.Context, arg DeleteItemLinkParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteItemLink, arg.ConnectionID, arg.ExternalID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteLocalExclusion = `-- name: DeleteLocalExclusion :execrows
delete from local_item_exclusions
where connection_id = $1
  and (product_id = $2 or modifier_option_id = $3)
`

type DeleteLocalExclusionParams struct {
	ConnectionID     int64  `json:"connection_id"`
	ProductID        *int64 `json:"product_id"`
	ModifierOptionID *int64 `json:"modifier_option_id"`
}

func (q *Queries) DeleteLocalExclusion(ctx context.Context, arg DeleteLocalExclusionParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteLocalExclusion, arg.ConnectionID, arg.ProductID, arg.ModifierOptionID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deletePlatformConnection = `-- name: DeletePlatformConnection :execrows
delete from platform_connections where id = $1
`

// :execrows para distinguir "se borró" de "no existía": el handler responde 404 en el segundo caso
// en vez de fingir que hizo algo.
func (q *Queries) DeletePlatformConnection(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, deletePlatformConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const ensurePlatformUnpairedProduct = `-- name: EnsurePlatformUnpairedProduct :one
select ensure_platform_unpaired_product($1::bigint)::bigint
`

// Al dar de alta una empresa: crea su categoría «Plataformas» y su producto genérico si faltan.
func (q *Queries) EnsurePlatformUnpairedProduct(ctx context.Context, companyID int64) (int64, error) {
	row := q.db.QueryRow(ctx, ensurePlatformUnpairedProduct, companyID)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const failMenuRead = `-- name: FailMenuRead :exec
update platform_menu_reads
   set status = 'fallida', finished_at = now(), failure_kind = $2
 where id = $1
`

type FailMenuReadParams struct {
	ID          int64   `json:"id"`
	FailureKind *string `json:"failure_kind"`
}

// `failure_kind` es una clase cerrada, nunca el mensaje de la plataforma: ahí cabe un secreto.
func (q *Queries) FailMenuRead(ctx context.Context, arg FailMenuReadParams) error {
	_, err := q.db.Exec(ctx, failMenuRead, arg.ID, arg.FailureKind)
	return err
}

const failStaleRunningReads = `-- name: FailStaleRunningReads :execrows
update platform_menu_reads
   set status = 'fallida', finished_at = now(), failure_kind = 'tiempo_agotado'
 where status = 'en_curso' and started_at < $1
`

// Cierra las lecturas que quedaron en curso porque el proceso se cayó a media descarga.
//
// SIN ESTO NO HAY SALIDA: `HasRunningMenuRead` sigue viéndolas, cada intento futuro responde «ya
// hay una lectura en curso», y la pantalla dice «se está leyendo» para siempre — solo se arregla
// tocando la base a mano. Corre al arrancar y con la poda.
func (q *Queries) FailStaleRunningReads(ctx context.Context, startedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, failStaleRunningReads, startedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishMenuReadOK = `-- name: FinishMenuReadOK :exec
update platform_menu_reads
   set status = 'ok', finished_at = now(), item_count = $2
 where id = $1
`

type FinishMenuReadOKParams struct {
	ID        int64  `json:"id"`
	ItemCount *int32 `json:"item_count"`
}

func (q *Queries) FinishMenuReadOK(ctx context.Context, arg FinishMenuReadOKParams) error {
	_, err := q.db.Exec(ctx, finishMenuReadOK, arg.ID, arg.ItemCount)
	return err
}

const getItemLink = `-- name: GetItemLink :one
select external_id, kind, product_id, modifier_option_id, local_kind, confirmed_at, is_capture_price
from platform_item_links
where connection_id = $1 and external_id = $2
`

type GetItemLinkParams struct {
	ConnectionID int64  `json:"connection_id"`
	ExternalID   string `json:"external_id"`
}

type GetItemLinkRow struct {
	ExternalID       string             `json:"external_id"`
	Kind             PlatformItemKind   `json:"kind"`
	ProductID        *int64             `json:"product_id"`
	ModifierOptionID *int64             `json:"modifier_option_id"`
	LocalKind        string             `json:"local_kind"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
	IsCapturePrice   bool               `json:"is_capture_price"`
}

// Con qué está emparejado hoy ese item. Se consulta ANTES de escribir: el upsert pisa en silencio
// una pareja confirmada, y eso es trabajo manual que no se reconstruye.
func (q *Queries) GetItemLink(ctx context.Context, arg GetItemLinkParams) (GetItemLinkRow, error) {
	row := q.db.QueryRow(ctx, getItemLink, arg.ConnectionID, arg.ExternalID)
	var i GetItemLinkRow
	err := row.Scan(
		&i.ExternalID,
		&i.Kind,
		&i.ProductID,
		&i.ModifierOptionID,
		&i.LocalKind,
		&i.ConfirmedAt,
		&i.IsCapturePrice,
	)
	return i, err
}

const getLastMenuRead = `-- name: GetLastMenuRead :one
select id, started_at, finished_at, status, item_count, failure_kind
from platform_menu_reads
where connection_id = $1
order by started_at desc
limit 1
`

type GetLastMenuReadRow struct {
	ID          int64              `json:"id"`
	StartedAt   time.Time          `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	Status      PlatformReadStatus `json:"status"`
	ItemCount   *int32             `json:"item_count"`
	FailureKind *string            `json:"failure_kind"`
}

// La última lectura de la conexión, EN CUALQUIER ESTADO. Es lo que permite distinguir los tres
// casos que una pantalla mal hecha muestra igual: nunca leída (sin fila), fallida, y sin
// diferencias. Devolver solo las 'ok' escondería una lectura rota detrás de una vieja buena.
func (q *Queries) GetLastMenuRead(ctx context.Context, connectionID int64) (GetLastMenuReadRow, error) {
	row := q.db.QueryRow(ctx, getLastMenuRead, connectionID)
	var i GetLastMenuReadRow
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.Status,
		&i.ItemCount,
		&i.FailureKind,
	)
	return i, err
}

const getLastOKMenuRead = `-- name: GetLastOKMenuRead :one
select id, started_at, finished_at, item_count
from platform_menu_reads
where connection_id = $1 and status = 'ok'
order by started_at desc
limit 1
`

type GetLastOKMenuReadRow struct {
	ID         int64              `json:"id"`
	StartedAt  time.Time          `json:"started_at"`
	FinishedAt pgtype.Timestamptz `json:"finished_at"`
	ItemCount  *int32             `json:"item_count"`
}

// La última que sí sirvió, que es contra la que se compara y se empareja.
func (q *Queries) GetLastOKMenuRead(ctx context.Context, connectionID int64) (GetLastOKMenuReadRow, error) {
	row := q.db.QueryRow(ctx, getLastOKMenuRead, connectionID)
	var i GetLastOKMenuReadRow
	err := row.Scan(
		&i.ID,
		&i.StartedAt,
		&i.FinishedAt,
		&i.ItemCount,
	)
	return i, err
}

const getPlatformConnection = `-- name: GetPlatformConnection :one
select c.id, c.delivery_platform_id, p.name as platform_name,
       c.external_store_id, c.label, c.is_active, c.branch_id
from platform_connections c
join delivery_platforms p on p.id = c.delivery_platform_id
where c.id = $1
`

type GetPlatformConnectionRow struct {
	ID                 int64  `json:"id"`
	DeliveryPlatformID int16  `json:"delivery_platform_id"`
	PlatformName       string `json:"platform_name"`
	ExternalStoreID    string `json:"external_store_id"`
	Label              string `json:"label"`
	IsActive           bool   `json:"is_active"`
	BranchID           int64  `json:"branch_id"`
}

func (q *Queries) GetPlatformConnection(ctx context.Context, id int64) (GetPlatformConnectionRow, error) {
	row := q.db.QueryRow(ctx, getPlatformConnection, id)
	var i GetPlatformConnectionRow
	err := row.Scan(
		&i.ID,
		&i.DeliveryPlatformID,
		&i.PlatformName,
		&i.ExternalStoreID,
		&i.Label,
		&i.IsActive,
		&i.BranchID,
	)
	return i, err
}

const getPlatformUnpairedProduct = `-- name: GetPlatformUnpairedProduct :one
select ensure_platform_unpaired_product(nullif(current_setting('app.company_id', true), '')::bigint)::bigint
`

// El producto genérico de la empresa DE LA SESIÓN (0077), creado si faltara. Filtra por la empresa
// explícitamente y no deja el filtro a RLS: como owner (pruebas, scripts) RLS no aplica y un
// `where system_kind = …` a secas devolvía el genérico de otra empresa, que la llave compuesta del
// renglón rechaza con un pedido ya pagado esperando.
func (q *Queries) GetPlatformUnpairedProduct(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, getPlatformUnpairedProduct)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const hasRunningMenuRead = `-- name: HasRunningMenuRead :one
select exists (
  select 1 from platform_menu_reads where connection_id = $1 and status = 'en_curso'
)
`

// Dos lecturas simultáneas de la misma tienda gastan dos tokens para escribir la misma foto, y
// Uber invalida el más viejo a partir del 101 en una hora.
func (q *Queries) HasRunningMenuRead(ctx context.Context, connectionID int64) (bool, error) {
	row := q.db.QueryRow(ctx, hasRunningMenuRead, connectionID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const insertItemExclusion = `-- name: InsertItemExclusion :exec
insert into platform_item_exclusions (connection_id, external_id, kind, decided_by)
values ($1, $2, $3, $4)
on conflict (connection_id, external_id) do nothing
`

type InsertItemExclusionParams struct {
	ConnectionID int64            `json:"connection_id"`
	ExternalID   string           `json:"external_id"`
	Kind         PlatformItemKind `json:"kind"`
	DecidedBy    int64            `json:"decided_by"`
}

func (q *Queries) InsertItemExclusion(ctx context.Context, arg InsertItemExclusionParams) error {
	_, err := q.db.Exec(ctx, insertItemExclusion,
		arg.ConnectionID,
		arg.ExternalID,
		arg.Kind,
		arg.DecidedBy,
	)
	return err
}

const insertLocalExclusion = `-- name: InsertLocalExclusion :exec
insert into local_item_exclusions (connection_id, product_id, modifier_option_id, decided_by)
values ($1, $2, $3, $4)
on conflict do nothing
`

type InsertLocalExclusionParams struct {
	ConnectionID     int64  `json:"connection_id"`
	ProductID        *int64 `json:"product_id"`
	ModifierOptionID *int64 `json:"modifier_option_id"`
	DecidedBy        int64  `json:"decided_by"`
}

func (q *Queries) InsertLocalExclusion(ctx context.Context, arg InsertLocalExclusionParams) error {
	_, err := q.db.Exec(ctx, insertLocalExclusion,
		arg.ConnectionID,
		arg.ProductID,
		arg.ModifierOptionID,
		arg.DecidedBy,
	)
	return err
}

const insertMenuItem = `-- name: InsertMenuItem :exec

insert into platform_menu_items (read_id, external_id, kind, name, price_cents, available)
values ($1, $2, $3, $4, $5, $6)
`

type InsertMenuItemParams struct {
	ReadID     int64            `json:"read_id"`
	ExternalID string           `json:"external_id"`
	Kind       PlatformItemKind `json:"kind"`
	Name       string           `json:"name"`
	PriceCents int64            `json:"price_cents"`
	Available  bool             `json:"available"`
}

// ---------------------------------------------------------------------------------------------
// La foto
// ---------------------------------------------------------------------------------------------
func (q *Queries) InsertMenuItem(ctx context.Context, arg InsertMenuItemParams) error {
	_, err := q.db.Exec(ctx, insertMenuItem,
		arg.ReadID,
		arg.ExternalID,
		arg.Kind,
		arg.Name,
		arg.PriceCents,
		arg.Available,
	)
	return err
}

const insertPlatformPriceChange = `-- name: InsertPlatformPriceChange :exec
insert into platform_price_changes (read_id, external_id, name, product_id, modifier_option_id, old_price, new_price)
values ($1, $2, $3, $4, $5,
        $6, $7)
`

type InsertPlatformPriceChangeParams struct {
	ReadID           int64            `json:"read_id"`
	ExternalID       string           `json:"external_id"`
	Name             string           `json:"name"`
	ProductID        *int64           `json:"product_id"`
	ModifierOptionID *int64           `json:"modifier_option_id"`
	OldPrice         *decimal.Decimal `json:"old_price"`
	NewPrice         decimal.Decimal  `json:"new_price"`
}

func (q *Queries) InsertPlatformPriceChange(ctx context.Context, arg InsertPlatformPriceChangeParams) error {
	_, err := q.db.Exec(ctx, insertPlatformPriceChange,
		arg.ReadID,
		arg.ExternalID,
		arg.Name,
		arg.ProductID,
		arg.ModifierOptionID,
		arg.OldPrice,
		arg.NewPrice,
	)
	return err
}

const listActiveOptionsForCompare = `-- name: ListActiveOptionsForCompare :many
select o.id, o.name, o.price_delta
from modifier_options o
join modifier_groups g on g.id = o.group_id
where o.is_active and g.is_active
order by o.name
`

type ListActiveOptionsForCompareRow struct {
	ID         int64           `json:"id"`
	Name       string          `json:"name"`
	PriceDelta decimal.Decimal `json:"price_delta"`
}

// `g.is_active` ADEMÁS de `o.is_active`, igual que la consulta que arma el menú del POS. Desactivar
// el grupo entero es la forma normal de ocultar algo estacional sin tocar opción por opción; sin
// este filtro, esas opciones se siguen reportando como vendidas y salen como diferencia contra un
// menú que ya no las ofrece.
func (q *Queries) ListActiveOptionsForCompare(ctx context.Context) ([]ListActiveOptionsForCompareRow, error) {
	rows, err := q.db.Query(ctx, listActiveOptionsForCompare)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveOptionsForCompareRow{}
	for rows.Next() {
		var i ListActiveOptionsForCompareRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PriceDelta); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveProductsForCompare = `-- name: ListActiveProductsForCompare :many

select id, name, price from products where is_active order by name
`

type ListActiveProductsForCompareRow struct {
	ID    int64           `json:"id"`
	Name  string          `json:"name"`
	Price decimal.Decimal `json:"price"`
}

// ---------------------------------------------------------------------------------------------
// El lado del POS de la comparación
// ---------------------------------------------------------------------------------------------
// Nombre y precio base de lo que el negocio vende hoy. El precio POR PLATAFORMA no sale de aquí:
// se calcula con el markup y las excepciones, igual que en el menú del POS, para no duplicar esa
// regla en dos lugares que se desincronizan.
func (q *Queries) ListActiveProductsForCompare(ctx context.Context) ([]ListActiveProductsForCompareRow, error) {
	rows, err := q.db.Query(ctx, listActiveProductsForCompare)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveProductsForCompareRow{}
	for rows.Next() {
		var i ListActiveProductsForCompareRow
		if err := rows.Scan(&i.ID, &i.Name, &i.Price); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemExclusions = `-- name: ListItemExclusions :many
select external_id, kind, decided_at from platform_item_exclusions where connection_id = $1
`

type ListItemExclusionsRow struct {
	ExternalID string           `json:"external_id"`
	Kind       PlatformItemKind `json:"kind"`
	DecidedAt  time.Time        `json:"decided_at"`
}

func (q *Queries) ListItemExclusions(ctx context.Context, connectionID int64) ([]ListItemExclusionsRow, error) {
	rows, err := q.db.Query(ctx, listItemExclusions, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemExclusionsRow{}
	for rows.Next() {
		var i ListItemExclusionsRow
		if err := rows.Scan(&i.ExternalID, &i.Kind, &i.DecidedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemLinks = `-- name: ListItemLinks :many

select external_id, kind, product_id, modifier_option_id, local_kind, confirmed_at, confirmed_by,
       is_capture_price, created_at
from platform_item_links
where connection_id = $1
`

type ListItemLinksRow struct {
	ExternalID       string             `json:"external_id"`
	Kind             PlatformItemKind   `json:"kind"`
	ProductID        *int64             `json:"product_id"`
	ModifierOptionID *int64             `json:"modifier_option_id"`
	LocalKind        string             `json:"local_kind"`
	ConfirmedAt      pgtype.Timestamptz `json:"confirmed_at"`
	ConfirmedBy      *int64             `json:"confirmed_by"`
	IsCapturePrice   bool               `json:"is_capture_price"`
	CreatedAt        time.Time          `json:"created_at"`
}

// ---------------------------------------------------------------------------------------------
// Emparejamiento
// ---------------------------------------------------------------------------------------------
// `confirmed_at` viaja hasta la pantalla y no es adorno: sin él, «deshacer el último» tiene que
// adivinar cuál fue, y la lista llega ordenada por NOMBRE. Adivinar ahí no falla ruidoso — deshace
// otra pareja.
func (q *Queries) ListItemLinks(ctx context.Context, connectionID int64) ([]ListItemLinksRow, error) {
	rows, err := q.db.Query(ctx, listItemLinks, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListItemLinksRow{}
	for rows.Next() {
		var i ListItemLinksRow
		if err := rows.Scan(
			&i.ExternalID,
			&i.Kind,
			&i.ProductID,
			&i.ModifierOptionID,
			&i.LocalKind,
			&i.ConfirmedAt,
			&i.ConfirmedBy,
			&i.IsCapturePrice,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinksOfTarget = `-- name: ListLinksOfTarget :many
select external_id, is_capture_price, created_at
from platform_item_links
where connection_id = $1
  and (product_id = $2 or modifier_option_id = $3)
`

type ListLinksOfTargetParams struct {
	ConnectionID     int64  `json:"connection_id"`
	ProductID        *int64 `json:"product_id"`
	ModifierOptionID *int64 `json:"modifier_option_id"`
}

type ListLinksOfTargetRow struct {
	ExternalID     string    `json:"external_id"`
	IsCapturePrice bool      `json:"is_capture_price"`
	CreatedAt      time.Time `json:"created_at"`
}

// Las parejas de la tienda que van al mismo producto u opción del POS: deciden si hace falta elegir
// el precio de captura y a quién pasa cuando se quita la que lo daba.
func (q *Queries) ListLinksOfTarget(ctx context.Context, arg ListLinksOfTargetParams) ([]ListLinksOfTargetRow, error) {
	rows, err := q.db.Query(ctx, listLinksOfTarget, arg.ConnectionID, arg.ProductID, arg.ModifierOptionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinksOfTargetRow{}
	for rows.Next() {
		var i ListLinksOfTargetRow
		if err := rows.Scan(&i.ExternalID, &i.IsCapturePrice, &i.CreatedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLocalExclusions = `-- name: ListLocalExclusions :many
select product_id, modifier_option_id, decided_at from local_item_exclusions where connection_id = $1
`

type ListLocalExclusionsRow struct {
	ProductID        *int64    `json:"product_id"`
	ModifierOptionID *int64    `json:"modifier_option_id"`
	DecidedAt        time.Time `json:"decided_at"`
}

func (q *Queries) ListLocalExclusions(ctx context.Context, connectionID int64) ([]ListLocalExclusionsRow, error) {
	rows, err := q.db.Query(ctx, listLocalExclusions, connectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLocalExclusionsRow{}
	for rows.Next() {
		var i ListLocalExclusionsRow
		if err := rows.Scan(&i.ProductID, &i.ModifierOptionID, &i.DecidedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuItemsOfRead = `-- name: ListMenuItemsOfRead :many
select external_id, kind, name, price_cents, available
from platform_menu_items
where read_id = $1 and kind = $2
order by name
`

type ListMenuItemsOfReadParams struct {
	ReadID int64            `json:"read_id"`
	Kind   PlatformItemKind `json:"kind"`
}

type ListMenuItemsOfReadRow struct {
	ExternalID string           `json:"external_id"`
	Kind       PlatformItemKind `json:"kind"`
	Name       string           `json:"name"`
	PriceCents int64            `json:"price_cents"`
	Available  bool             `json:"available"`
}

func (q *Queries) ListMenuItemsOfRead(ctx context.Context, arg ListMenuItemsOfReadParams) ([]ListMenuItemsOfReadRow, error) {
	rows, err := q.db.Query(ctx, listMenuItemsOfRead, arg.ReadID, arg.Kind)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMenuItemsOfReadRow{}
	for rows.Next() {
		var i ListMenuItemsOfReadRow
		if err := rows.Scan(
			&i.ExternalID,
			&i.Kind,
			&i.Name,
			&i.PriceCents,
			&i.Available,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMenuReads = `-- name: ListMenuReads :many
select id, started_at, finished_at, status, item_count, failure_kind
from platform_menu_reads
where connection_id = $1
order by started_at desc
limit $2
`

type ListMenuReadsParams struct {
	ConnectionID int64 `json:"connection_id"`
	Limit        int32 `json:"limit"`
}

type ListMenuReadsRow struct {
	ID          int64              `json:"id"`
	StartedAt   time.Time          `json:"started_at"`
	FinishedAt  pgtype.Timestamptz `json:"finished_at"`
	Status      PlatformReadStatus `json:"status"`
	ItemCount   *int32             `json:"item_count"`
	FailureKind *string            `json:"failure_kind"`
}

func (q *Queries) ListMenuReads(ctx context.Context, arg ListMenuReadsParams) ([]ListMenuReadsRow, error) {
	rows, err := q.db.Query(ctx, listMenuReads, arg.ConnectionID, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListMenuReadsRow{}
	for rows.Next() {
		var i ListMenuReadsRow
		if err := rows.Scan(
			&i.ID,
			&i.StartedAt,
			&i.FinishedAt,
			&i.Status,
			&i.ItemCount,
			&i.FailureKind,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformConnections = `-- name: ListPlatformConnections :many

select c.id, c.delivery_platform_id, p.name as platform_name,
       c.external_store_id, c.label, c.is_active, c.created_at
from platform_connections c
join delivery_platforms p on p.id = c.delivery_platform_id
order by p.name, c.label
`

type ListPlatformConnectionsRow struct {
	ID                 int64     `json:"id"`
	DeliveryPlatformID int16     `json:"delivery_platform_id"`
	PlatformName       string    `json:"platform_name"`
	ExternalStoreID    string    `json:"external_store_id"`
	Label              string    `json:"label"`
	IsActive           bool      `json:"is_active"`
	CreatedAt          time.Time `json:"created_at"`
}

// Menús de plataforma (spec 020). Todo bajo RLS: ninguna consulta filtra por company_id porque la
// política tenant_isolation ya lo hace, igual que el resto del repo.
// Las tiendas conectadas de la empresa, con el nombre de su plataforma. Una empresa puede tener
// VARIAS de la misma plataforma: una por sucursal.
func (q *Queries) ListPlatformConnections(ctx context.Context) ([]ListPlatformConnectionsRow, error) {
	rows, err := q.db.Query(ctx, listPlatformConnections)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformConnectionsRow{}
	for rows.Next() {
		var i ListPlatformConnectionsRow
		if err := rows.Scan(
			&i.ID,
			&i.DeliveryPlatformID,
			&i.PlatformName,
			&i.ExternalStoreID,
			&i.Label,
			&i.IsActive,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformPriceChanges = `-- name: ListPlatformPriceChanges :many
select external_id, name, old_price, new_price from platform_price_changes where read_id = $1 order by name
`

type ListPlatformPriceChangesRow struct {
	ExternalID string           `json:"external_id"`
	Name       string           `json:"name"`
	OldPrice   *decimal.Decimal `json:"old_price"`
	NewPrice   decimal.Decimal  `json:"new_price"`
}

func (q *Queries) ListPlatformPriceChanges(ctx context.Context, readID int64) ([]ListPlatformPriceChangesRow, error) {
	rows, err := q.db.Query(ctx, listPlatformPriceChanges, readID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformPriceChangesRow{}
	for rows.Next() {
		var i ListPlatformPriceChangesRow
		if err := rows.Scan(
			&i.ExternalID,
			&i.Name,
			&i.OldPrice,
			&i.NewPrice,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuItemExistsInRead = `-- name: MenuItemExistsInRead :one
select exists (
  select 1 from platform_menu_items where read_id = $1 and external_id = $2 and kind = $3
)
`

type MenuItemExistsInReadParams struct {
	ReadID     int64            `json:"read_id"`
	ExternalID string           `json:"external_id"`
	Kind       PlatformItemKind `json:"kind"`
}

// Sustituye a la FK que `platform_item_links` deliberadamente NO tiene. Sin esta validación se
// puede guardar una pareja contra un id que no existe arriba: el PUT responde 200 y la pantalla
// sigue diciendo «sin pareja», sin que nadie vea un error.
func (q *Queries) MenuItemExistsInRead(ctx context.Context, arg MenuItemExistsInReadParams) (bool, error) {
	row := q.db.QueryRow(ctx, menuItemExistsInRead, arg.ReadID, arg.ExternalID, arg.Kind)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const pruneMenuReads = `-- name: PruneMenuReads :execrows
delete from platform_menu_reads r
where r.started_at < $1
  and r.id <> (
    select r2.id from platform_menu_reads r2
    where r2.connection_id = r.connection_id
    order by r2.started_at desc limit 1
  )
`

// Poda por retención. **Conserva SIEMPRE la más reciente de cada conexión**, sin importar su edad:
// sin esa excepción, una tienda que nadie vuelve a leer se queda sin ninguna fila y la pantalla la
// muestra igual que una que nunca se leyó — dos estados que FR-003 exige distinguir.
func (q *Queries) PruneMenuReads(ctx context.Context, startedAt time.Time) (int64, error) {
	result, err := q.db.Exec(ctx, pruneMenuReads, startedAt)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setCapturePrice = `-- name: SetCapturePrice :exec
update platform_item_links set is_capture_price = true
where connection_id = $1 and external_id = $2
`

type SetCapturePriceParams struct {
	ConnectionID int64  `json:"connection_id"`
	ExternalID   string `json:"external_id"`
}

func (q *Queries) SetCapturePrice(ctx context.Context, arg SetCapturePriceParams) error {
	_, err := q.db.Exec(ctx, setCapturePrice, arg.ConnectionID, arg.ExternalID)
	return err
}

const startMenuRead = `-- name: StartMenuRead :one

insert into platform_menu_reads (connection_id) values ($1) returning id, started_at
`

type StartMenuReadRow struct {
	ID        int64     `json:"id"`
	StartedAt time.Time `json:"started_at"`
}

// ---------------------------------------------------------------------------------------------
// Lecturas
// ---------------------------------------------------------------------------------------------
// Falla con 23505 si ya hay una en curso para esa tienda: lo impide el índice único parcial de la
// 0071, no el chequeo previo del servicio, que es dos statements y se puede colar entre ambos.
func (q *Queries) StartMenuRead(ctx context.Context, connectionID int64) (StartMenuReadRow, error) {
	row := q.db.QueryRow(ctx, startMenuRead, connectionID)
	var i StartMenuReadRow
	err := row.Scan(&i.ID, &i.StartedAt)
	return i, err
}

const upsertItemLink = `-- name: UpsertItemLink :exec
insert into platform_item_links (connection_id, external_id, kind, product_id, modifier_option_id,
                                 local_kind, confirmed_at, confirmed_by, is_capture_price)
values ($1, $2, $3, $4, $5,
        $6, now(), $7, $8)
on conflict (connection_id, external_id)
do update set product_id         = excluded.product_id,
              modifier_option_id = excluded.modifier_option_id,
              kind               = excluded.kind,
              local_kind         = excluded.local_kind,
              confirmed_at       = excluded.confirmed_at,
              confirmed_by       = excluded.confirmed_by,
              is_capture_price   = excluded.is_capture_price
`

type UpsertItemLinkParams struct {
	ConnectionID     int64            `json:"connection_id"`
	ExternalID       string           `json:"external_id"`
	Kind             PlatformItemKind `json:"kind"`
	ProductID        *int64           `json:"product_id"`
	ModifierOptionID *int64           `json:"modifier_option_id"`
	LocalKind        string           `json:"local_kind"`
	ConfirmedBy      *int64           `json:"confirmed_by"`
	IsCapturePrice   bool             `json:"is_capture_price"`
}

// Producto u opción según `local_kind` (0077): el `check` de la tabla exige exactamente uno.
func (q *Queries) UpsertItemLink(ctx context.Context, arg UpsertItemLinkParams) error {
	_, err := q.db.Exec(ctx, upsertItemLink,
		arg.ConnectionID,
		arg.ExternalID,
		arg.Kind,
		arg.ProductID,
		arg.ModifierOptionID,
		arg.LocalKind,
		arg.ConfirmedBy,
		arg.IsCapturePrice,
	)
	return err
}
