// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: menu.sql

package db

import (
	"context"
)

const menuCategories = `-- name: MenuCategories :many

select id, name, parent_id, sort_key, color, image_url
from categories
where is_active
order by parent_id nulls first, sort_key, name
`

type MenuCategoriesRow struct {
	ID       int64   `json:"id"`
	Name     string  `json:"name"`
	ParentID *int64  `json:"parent_id"`
	SortKey  float64 `json:"sort_key"`
	Color    *string `json:"color"`
	ImageUrl *string `json:"image_url"`
}

// Lecturas planas para armar el documento del menú POS (se ensambla en Go y se cachea en Redis).
func (q *Queries) MenuCategories(ctx context.Context) ([]MenuCategoriesRow, error) {
	rows, err := q.db.Query(ctx, menuCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuCategoriesRow{}
	for rows.Next() {
		var i MenuCategoriesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.ParentID,
			&i.SortKey,
			&i.Color,
			&i.ImageUrl,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuOptions = `-- name: MenuOptions :many
select mo.id, mo.group_id, mo.name, mo.price_delta, mo.max_per_line, mo.is_favorite
from modifier_options mo
where mo.is_active
order by mo.group_id, mo.sort_key, mo.name
`

type MenuOptionsRow struct {
	ID         int64   `json:"id"`
	GroupID    int64   `json:"group_id"`
	Name       string  `json:"name"`
	PriceDelta float64 `json:"price_delta"`
	MaxPerLine int16   `json:"max_per_line"`
	IsFavorite bool    `json:"is_favorite"`
}

func (q *Queries) MenuOptions(ctx context.Context) ([]MenuOptionsRow, error) {
	rows, err := q.db.Query(ctx, menuOptions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuOptionsRow{}
	for rows.Next() {
		var i MenuOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.GroupID,
			&i.Name,
			&i.PriceDelta,
			&i.MaxPerLine,
			&i.IsFavorite,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuProductGroups = `-- name: MenuProductGroups :many
select pmg.product_id, pmg.group_id, coalesce(pmg.title, mg.name) as title,
       coalesce(pmg.min_select, mg.default_min_select) as min_select,
       coalesce(pmg.max_select, mg.default_max_select) as max_select,
       pmg.position
from product_modifier_groups pmg
join modifier_groups mg on mg.id = pmg.group_id
where mg.is_active
order by pmg.product_id, pmg.position
`

type MenuProductGroupsRow struct {
	ProductID int64  `json:"product_id"`
	GroupID   int64  `json:"group_id"`
	Title     string `json:"title"`
	MinSelect int16  `json:"min_select"`
	MaxSelect int16  `json:"max_select"`
	Position  int32  `json:"position"`
}

// min/max efectivos: el override del producto o, si es NULL, el default del grupo.
func (q *Queries) MenuProductGroups(ctx context.Context) ([]MenuProductGroupsRow, error) {
	rows, err := q.db.Query(ctx, menuProductGroups)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuProductGroupsRow{}
	for rows.Next() {
		var i MenuProductGroupsRow
		if err := rows.Scan(
			&i.ProductID,
			&i.GroupID,
			&i.Title,
			&i.MinSelect,
			&i.MaxSelect,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const menuProducts = `-- name: MenuProducts :many
select p.id, p.name, p.description, p.price, p.current_cost,
       p.category_id, p.type, p.is_favorite, p.image_url, p.track_stock
from products p
where p.is_active
  and (p.available_from is null or p.available_from <= current_date)
  and (p.available_until is null or p.available_until >= current_date)
  and not exists (
    select 1 from product_channels pc
    join channels c on c.id = pc.channel_id
    where pc.product_id = p.id and c.code = 'pos' and pc.visibility = 'oculto'
  )
order by p.sort_key, p.name
`

type MenuProductsRow struct {
	ID          int64       `json:"id"`
	Name        string      `json:"name"`
	Description *string     `json:"description"`
	Price       float64     `json:"price"`
	CurrentCost float64     `json:"current_cost"`
	CategoryID  int64       `json:"category_id"`
	Type        ProductType `json:"type"`
	IsFavorite  bool        `json:"is_favorite"`
	ImageUrl    *string     `json:"image_url"`
	TrackStock  bool        `json:"track_stock"`
}

func (q *Queries) MenuProducts(ctx context.Context) ([]MenuProductsRow, error) {
	rows, err := q.db.Query(ctx, menuProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []MenuProductsRow{}
	for rows.Next() {
		var i MenuProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Price,
			&i.CurrentCost,
			&i.CategoryID,
			&i.Type,
			&i.IsFavorite,
			&i.ImageUrl,
			&i.TrackStock,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const popularProducts = `-- name: PopularProducts :many
select ol.product_id, sum(ol.quantity)::numeric(12,2) as qty
from order_lines ol
join orders o on o.id = ol.order_id
where o.status <> 'cancelada'
  and ol.cancelled_at is null
  and o.opened_at >= now() - interval '30 days'
group by ol.product_id
order by qty desc, ol.product_id
limit 60
`

type PopularProductsRow struct {
	ProductID int64   `json:"product_id"`
	Qty       float64 `json:"qty"`
}

// Productos más vendidos por cantidad en los últimos 30 días; alimenta la pestaña "Top" del POS.
// ceiling: tope 60 filas (el N configurable del front es << 60). Subir si algún día se necesita más.
func (q *Queries) PopularProducts(ctx context.Context) ([]PopularProductsRow, error) {
	rows, err := q.db.Query(ctx, popularProducts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []PopularProductsRow{}
	for rows.Next() {
		var i PopularProductsRow
		if err := rows.Scan(&i.ProductID, &i.Qty); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
