// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"database/sql/driver"
	"fmt"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"uuid"
)

type ChannelVisibility string

const (
	ChannelVisibilityVisible ChannelVisibility = "visible"
	ChannelVisibilityOculto  ChannelVisibility = "oculto"
)

func (e *ChannelVisibility) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ChannelVisibility(s)
	case string:
		*e = ChannelVisibility(s)
	default:
		return fmt.Errorf("unsupported scan type for ChannelVisibility: %T", src)
	}
	return nil
}

type NullChannelVisibility struct {
	ChannelVisibility ChannelVisibility `json:"channel_visibility"`
	Valid             bool              `json:"valid"` // Valid is true if ChannelVisibility is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullChannelVisibility) Scan(value interface{}) error {
	if value == nil {
		ns.ChannelVisibility, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ChannelVisibility.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullChannelVisibility) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ChannelVisibility), nil
}

type CostSource string

const (
	CostSourceManual CostSource = "manual"
	CostSourceCompra CostSource = "compra"
	CostSourceReceta CostSource = "receta"
)

func (e *CostSource) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = CostSource(s)
	case string:
		*e = CostSource(s)
	default:
		return fmt.Errorf("unsupported scan type for CostSource: %T", src)
	}
	return nil
}

type NullCostSource struct {
	CostSource CostSource `json:"cost_source"`
	Valid      bool       `json:"valid"` // Valid is true if CostSource is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullCostSource) Scan(value interface{}) error {
	if value == nil {
		ns.CostSource, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.CostSource.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullCostSource) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.CostSource), nil
}

type ExpenseStatus string

const (
	ExpenseStatusPendiente ExpenseStatus = "pendiente"
	ExpenseStatusPagada    ExpenseStatus = "pagada"
	ExpenseStatusCancelada ExpenseStatus = "cancelada"
)

func (e *ExpenseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExpenseStatus(s)
	case string:
		*e = ExpenseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExpenseStatus: %T", src)
	}
	return nil
}

type NullExpenseStatus struct {
	ExpenseStatus ExpenseStatus `json:"expense_status"`
	Valid         bool          `json:"valid"` // Valid is true if ExpenseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExpenseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExpenseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExpenseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExpenseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExpenseStatus), nil
}

type FinancialGroup string

const (
	FinancialGroupOperacional    FinancialGroup = "operacional"
	FinancialGroupAdministrativo FinancialGroup = "administrativo"
	FinancialGroupOtro           FinancialGroup = "otro"
)

func (e *FinancialGroup) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FinancialGroup(s)
	case string:
		*e = FinancialGroup(s)
	default:
		return fmt.Errorf("unsupported scan type for FinancialGroup: %T", src)
	}
	return nil
}

type NullFinancialGroup struct {
	FinancialGroup FinancialGroup `json:"financial_group"`
	Valid          bool           `json:"valid"` // Valid is true if FinancialGroup is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFinancialGroup) Scan(value interface{}) error {
	if value == nil {
		ns.FinancialGroup, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FinancialGroup.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFinancialGroup) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FinancialGroup), nil
}

type OrderStatus string

const (
	OrderStatusAbierta     OrderStatus = "abierta"
	OrderStatusLista       OrderStatus = "lista"
	OrderStatusEntregada   OrderStatus = "entregada"
	OrderStatusCancelada   OrderStatus = "cancelada"
	OrderStatusReembolsada OrderStatus = "reembolsada"
)

func (e *OrderStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrderStatus(s)
	case string:
		*e = OrderStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrderStatus: %T", src)
	}
	return nil
}

type NullOrderStatus struct {
	OrderStatus OrderStatus `json:"order_status"`
	Valid       bool        `json:"valid"` // Valid is true if OrderStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrderStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrderStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrderStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrderStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrderStatus), nil
}

type PaymentKind string

const (
	PaymentKindEfectivo      PaymentKind = "efectivo"
	PaymentKindTarjeta       PaymentKind = "tarjeta"
	PaymentKindTransferencia PaymentKind = "transferencia"
	PaymentKindPlataforma    PaymentKind = "plataforma"
	PaymentKindOtro          PaymentKind = "otro"
)

func (e *PaymentKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentKind(s)
	case string:
		*e = PaymentKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentKind: %T", src)
	}
	return nil
}

type NullPaymentKind struct {
	PaymentKind PaymentKind `json:"payment_kind"`
	Valid       bool        `json:"valid"` // Valid is true if PaymentKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentKind) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentKind), nil
}

type ProductType string

const (
	ProductTypeSimple ProductType = "simple"
	ProductTypeCombo  ProductType = "combo"
)

func (e *ProductType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductType(s)
	case string:
		*e = ProductType(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductType: %T", src)
	}
	return nil
}

type NullProductType struct {
	ProductType ProductType `json:"product_type"`
	Valid       bool        `json:"valid"` // Valid is true if ProductType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductType) Scan(value interface{}) error {
	if value == nil {
		ns.ProductType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductType), nil
}

type ServiceType string

const (
	ServiceTypeMostrador  ServiceType = "mostrador"
	ServiceTypeParaLlevar ServiceType = "para_llevar"
	ServiceTypeDomicilio  ServiceType = "domicilio"
)

func (e *ServiceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ServiceType(s)
	case string:
		*e = ServiceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ServiceType: %T", src)
	}
	return nil
}

type NullServiceType struct {
	ServiceType ServiceType `json:"service_type"`
	Valid       bool        `json:"valid"` // Valid is true if ServiceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullServiceType) Scan(value interface{}) error {
	if value == nil {
		ns.ServiceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ServiceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullServiceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ServiceType), nil
}

type SessionStatus string

const (
	SessionStatusAbierta SessionStatus = "abierta"
	SessionStatusCerrada SessionStatus = "cerrada"
)

func (e *SessionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SessionStatus(s)
	case string:
		*e = SessionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for SessionStatus: %T", src)
	}
	return nil
}

type NullSessionStatus struct {
	SessionStatus SessionStatus `json:"session_status"`
	Valid         bool          `json:"valid"` // Valid is true if SessionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSessionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.SessionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SessionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSessionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SessionStatus), nil
}

type StockItemType string

const (
	StockItemTypeIngrediente StockItemType = "ingrediente"
	StockItemTypeProducto    StockItemType = "producto"
)

func (e *StockItemType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockItemType(s)
	case string:
		*e = StockItemType(s)
	default:
		return fmt.Errorf("unsupported scan type for StockItemType: %T", src)
	}
	return nil
}

type NullStockItemType struct {
	StockItemType StockItemType `json:"stock_item_type"`
	Valid         bool          `json:"valid"` // Valid is true if StockItemType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockItemType) Scan(value interface{}) error {
	if value == nil {
		ns.StockItemType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockItemType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockItemType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockItemType), nil
}

type StockMovementType string

const (
	StockMovementTypeVenta       StockMovementType = "venta"
	StockMovementTypeCompra      StockMovementType = "compra"
	StockMovementTypeAjuste      StockMovementType = "ajuste"
	StockMovementTypeMerma       StockMovementType = "merma"
	StockMovementTypeProduccion  StockMovementType = "produccion"
	StockMovementTypeCancelacion StockMovementType = "cancelacion"
)

func (e *StockMovementType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = StockMovementType(s)
	case string:
		*e = StockMovementType(s)
	default:
		return fmt.Errorf("unsupported scan type for StockMovementType: %T", src)
	}
	return nil
}

type NullStockMovementType struct {
	StockMovementType StockMovementType `json:"stock_movement_type"`
	Valid             bool              `json:"valid"` // Valid is true if StockMovementType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullStockMovementType) Scan(value interface{}) error {
	if value == nil {
		ns.StockMovementType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.StockMovementType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullStockMovementType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.StockMovementType), nil
}

type UnitKind string

const (
	UnitKindMasa    UnitKind = "masa"
	UnitKindVolumen UnitKind = "volumen"
	UnitKindPieza   UnitKind = "pieza"
)

func (e *UnitKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitKind(s)
	case string:
		*e = UnitKind(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitKind: %T", src)
	}
	return nil
}

type NullUnitKind struct {
	UnitKind UnitKind `json:"unit_kind"`
	Valid    bool     `json:"valid"` // Valid is true if UnitKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitKind) Scan(value interface{}) error {
	if value == nil {
		ns.UnitKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitKind), nil
}

type UserRole string

const (
	UserRoleAdmin   UserRole = "admin"
	UserRoleGerente UserRole = "gerente"
	UserRoleCajero  UserRole = "cajero"
	UserRoleMesero  UserRole = "mesero"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type BusinessSetting struct {
	DeliveryFee        decimal.Decimal    `json:"delivery_fee"`
	UpdatedAt          time.Time          `json:"updated_at"`
	UpdatedBy          *int64             `json:"updated_by"`
	BusinessName       string             `json:"business_name"`
	Address            *string            `json:"address"`
	Phone              *string            `json:"phone"`
	FooterNote         *string            `json:"footer_note"`
	LogoBytes          []byte             `json:"logo_bytes"`
	LogoMime           *string            `json:"logo_mime"`
	LogoUpdatedAt      pgtype.Timestamptz `json:"logo_updated_at"`
	HeaderNote         *string            `json:"header_note"`
	AutoPrintOnClose   bool               `json:"auto_print_on_close"`
	Timezone           string             `json:"timezone"`
	PrintFreeModifiers bool               `json:"print_free_modifiers"`
	PrintKitchenTicket bool               `json:"print_kitchen_ticket"`
}

type CashRegister struct {
	ID        int64  `json:"id"`
	Name      string `json:"name"`
	IsPrimary bool   `json:"is_primary"`
	IsActive  bool   `json:"is_active"`
	CompanyID int64  `json:"company_id"`
}

type CashTransfer struct {
	ID            int64           `json:"id"`
	FromSessionID int64           `json:"from_session_id"`
	ToSessionID   int64           `json:"to_session_id"`
	Amount        decimal.Decimal `json:"amount"`
	Note          *string         `json:"note"`
	CreatedBy     int64           `json:"created_by"`
	CreatedAt     time.Time       `json:"created_at"`
	CompanyID     int64           `json:"company_id"`
}

type Category struct {
	ID       int64           `json:"id"`
	Name     string          `json:"name"`
	ParentID *int64          `json:"parent_id"`
	SortKey  decimal.Decimal `json:"sort_key"`
	Color    *string         `json:"color"`
	ImageUrl *string         `json:"image_url"`
	IsActive bool            `json:"is_active"`
}

type CategoryChannel struct {
	CategoryID int64 `json:"category_id"`
	ChannelID  int16 `json:"channel_id"`
	Visible    bool  `json:"visible"`
}

type Channel struct {
	ID   int16  `json:"id"`
	Code string `json:"code"`
	Name string `json:"name"`
}

type ComboSlot struct {
	ID        int64  `json:"id"`
	ComboID   int64  `json:"combo_id"`
	Name      string `json:"name"`
	MinSelect int16  `json:"min_select"`
	MaxSelect int16  `json:"max_select"`
	Position  int32  `json:"position"`
}

type ComboSlotProduct struct {
	SlotID     int64           `json:"slot_id"`
	ProductID  int64           `json:"product_id"`
	PriceDelta decimal.Decimal `json:"price_delta"`
	IsDefault  bool            `json:"is_default"`
}

type Company struct {
	ID        int64     `json:"id"`
	Slug      string    `json:"slug"`
	Name      string    `json:"name"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type DeliveryPlatform struct {
	ID             int16           `json:"id"`
	Name           string          `json:"name"`
	IsActive       bool            `json:"is_active"`
	PriceMarkupPct decimal.Decimal `json:"price_markup_pct"`
}

type Expense struct {
	ID           int64              `json:"id"`
	ExpenseDate  pgtype.Date        `json:"expense_date"`
	CategoryID   int64              `json:"category_id"`
	SupplierID   *int64             `json:"supplier_id"`
	Amount       decimal.Decimal    `json:"amount"`
	Description  *string            `json:"description"`
	CreatedBy    int64              `json:"created_by"`
	CreatedAt    time.Time          `json:"created_at"`
	Currency     string             `json:"currency"`
	Status       ExpenseStatus      `json:"status"`
	PaidAt       pgtype.Timestamptz `json:"paid_at"`
	PaidBy       *int64             `json:"paid_by"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy  *int64             `json:"cancelled_by"`
	CancelReason *string            `json:"cancel_reason"`
	ReceivedAt   pgtype.Date        `json:"received_at"`
	DocKind      *string            `json:"doc_kind"`
	DocFolio     *string            `json:"doc_folio"`
	DocRaw       []byte             `json:"doc_raw"`
}

type ExpenseCategory struct {
	ID             int64          `json:"id"`
	Name           string         `json:"name"`
	FinancialGroup FinancialGroup `json:"financial_group"`
	IsActive       bool           `json:"is_active"`
}

type ExpenseItem struct {
	ID            int64            `json:"id"`
	ExpenseID     int64            `json:"expense_id"`
	ItemType      *StockItemType   `json:"item_type"`
	IngredientID  *int64           `json:"ingredient_id"`
	ProductID     *int64           `json:"product_id"`
	Description   string           `json:"description"`
	Quantity      decimal.Decimal  `json:"quantity"`
	UnitID        *int16           `json:"unit_id"`
	QtyReceived   *decimal.Decimal `json:"qty_received"`
	UnitCost      decimal.Decimal  `json:"unit_cost"`
	Amount        decimal.Decimal  `json:"amount"`
	PackQtyInBase *decimal.Decimal `json:"pack_qty_in_base"`
	Position      int32            `json:"position"`
	CreatedAt     time.Time        `json:"created_at"`
	CompanyID     int64            `json:"company_id"`
}

type ExpensePayment struct {
	ID                int64           `json:"id"`
	ExpenseID         int64           `json:"expense_id"`
	PaymentMethodID   int16           `json:"payment_method_id"`
	Amount            decimal.Decimal `json:"amount"`
	PaidOn            pgtype.Date     `json:"paid_on"`
	RegisterSessionID *int64          `json:"register_session_id"`
	Reference         *string         `json:"reference"`
	PaidBy            int64           `json:"paid_by"`
	CreatedAt         time.Time       `json:"created_at"`
	CompanyID         int64           `json:"company_id"`
}

type FudoImportMap struct {
	ID       int64   `json:"id"`
	Entity   string  `json:"entity"`
	FudoID   *int64  `json:"fudo_id"`
	FudoName *string `json:"fudo_name"`
	NewTable string  `json:"new_table"`
	NewID    int64   `json:"new_id"`
}

type Ingredient struct {
	ID          int64            `json:"id"`
	Name        string           `json:"name"`
	CategoryID  *int64           `json:"category_id"`
	BaseUnitID  int16            `json:"base_unit_id"`
	IsPrep      bool             `json:"is_prep"`
	RecipeID    *int64           `json:"recipe_id"`
	YieldQty    *decimal.Decimal `json:"yield_qty"`
	WastePct    decimal.Decimal  `json:"waste_pct"`
	CurrentCost decimal.Decimal  `json:"current_cost"`
	CostSource  CostSource       `json:"cost_source"`
	SupplierID  *int64           `json:"supplier_id"`
	IsPackaging bool             `json:"is_packaging"`
	TrackStock  bool             `json:"track_stock"`
	MinStock    *decimal.Decimal `json:"min_stock"`
	IsActive    bool             `json:"is_active"`
	CreatedAt   time.Time        `json:"created_at"`
	UpdatedAt   time.Time        `json:"updated_at"`
}

type IngredientCategory struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	IsActive bool   `json:"is_active"`
}

type IngredientPurchaseFormat struct {
	ID           int64            `json:"id"`
	IngredientID int64            `json:"ingredient_id"`
	Name         string           `json:"name"`
	QtyInBase    decimal.Decimal  `json:"qty_in_base"`
	LastCost     *decimal.Decimal `json:"last_cost"`
	SupplierID   *int64           `json:"supplier_id"`
	IsDefault    bool             `json:"is_default"`
}

type ModifierGroup struct {
	ID               int64  `json:"id"`
	Name             string `json:"name"`
	IsActive         bool   `json:"is_active"`
	DefaultMinSelect int16  `json:"default_min_select"`
	DefaultMaxSelect int16  `json:"default_max_select"`
}

type ModifierOption struct {
	ID              int64           `json:"id"`
	GroupID         int64           `json:"group_id"`
	Name            string          `json:"name"`
	PriceDelta      decimal.Decimal `json:"price_delta"`
	RecipeID        *int64          `json:"recipe_id"`
	LinkedProductID *int64          `json:"linked_product_id"`
	MaxPerLine      int16           `json:"max_per_line"`
	CurrentCost     decimal.Decimal `json:"current_cost"`
	SortKey         decimal.Decimal `json:"sort_key"`
	IsActive        bool            `json:"is_active"`
	IsFavorite      bool            `json:"is_favorite"`
}

type ModifierOptionPlatformPrice struct {
	OptionID   int64           `json:"option_id"`
	PlatformID int16           `json:"platform_id"`
	PriceDelta decimal.Decimal `json:"price_delta"`
	UpdatedBy  int64           `json:"updated_by"`
	UpdatedAt  time.Time       `json:"updated_at"`
	CompanyID  int64           `json:"company_id"`
}

type Order struct {
	ID                 int64              `json:"id"`
	ClientUuid         uuid.UUID          `json:"client_uuid"`
	BusinessDate       pgtype.Date        `json:"business_date"`
	DailyNumber        int32              `json:"daily_number"`
	Status             OrderStatus        `json:"status"`
	ServiceType        ServiceType        `json:"service_type"`
	DeliveryPlatformID *int16             `json:"delivery_platform_id"`
	CustomerName       *string            `json:"customer_name"`
	Notes              *string            `json:"notes"`
	RegisterSessionID  *int64             `json:"register_session_id"`
	OpenedBy           int64              `json:"opened_by"`
	Subtotal           decimal.Decimal    `json:"subtotal"`
	DiscountTotal      decimal.Decimal    `json:"discount_total"`
	Total              decimal.Decimal    `json:"total"`
	OpenedAt           time.Time          `json:"opened_at"`
	ReadyAt            pgtype.Timestamptz `json:"ready_at"`
	CompletedAt        pgtype.Timestamptz `json:"completed_at"`
	CancelledAt        pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy        *int64             `json:"cancelled_by"`
	CancelReason       *string            `json:"cancel_reason"`
	UpdatedAt          time.Time          `json:"updated_at"`
	Currency           string             `json:"currency"`
	RefundedAt         pgtype.Timestamptz `json:"refunded_at"`
	RefundedBy         *int64             `json:"refunded_by"`
	RefundReason       *string            `json:"refund_reason"`
	RefundAmount       decimal.Decimal    `json:"refund_amount"`
	DeliveryFee        decimal.Decimal    `json:"delivery_fee"`
	FolioName          *string            `json:"folio_name"`
}

type OrderCounter struct {
	BusinessDate pgtype.Date `json:"business_date"`
	LastNumber   int32       `json:"last_number"`
}

type OrderLine struct {
	ID             int64              `json:"id"`
	OrderID        int64              `json:"order_id"`
	ProductID      int64              `json:"product_id"`
	ParentLineID   *int64             `json:"parent_line_id"`
	ProductName    string             `json:"product_name"`
	Quantity       decimal.Decimal    `json:"quantity"`
	UnitPrice      decimal.Decimal    `json:"unit_price"`
	ModifiersTotal decimal.Decimal    `json:"modifiers_total"`
	UnitCost       decimal.Decimal    `json:"unit_cost"`
	LineTotal      decimal.Decimal    `json:"line_total"`
	Notes          *string            `json:"notes"`
	CancelledAt    pgtype.Timestamptz `json:"cancelled_at"`
	CancelledBy    *int64             `json:"cancelled_by"`
	CancelReason   *string            `json:"cancel_reason"`
	CreatedAt      time.Time          `json:"created_at"`
	DeliveredQty   decimal.Decimal    `json:"delivered_qty"`
}

type OrderLineModifier struct {
	ID               int64           `json:"id"`
	OrderLineID      int64           `json:"order_line_id"`
	ModifierOptionID int64           `json:"modifier_option_id"`
	GroupTitle       string          `json:"group_title"`
	OptionName       string          `json:"option_name"`
	Quantity         int16           `json:"quantity"`
	PriceDelta       decimal.Decimal `json:"price_delta"`
	UnitCost         decimal.Decimal `json:"unit_cost"`
}

type OrderPayment struct {
	ID                int64           `json:"id"`
	OrderID           int64           `json:"order_id"`
	PaymentMethodID   int16           `json:"payment_method_id"`
	Amount            decimal.Decimal `json:"amount"`
	TipAmount         decimal.Decimal `json:"tip_amount"`
	RegisterSessionID *int64          `json:"register_session_id"`
	ReceivedBy        *int64          `json:"received_by"`
	Reference         *string         `json:"reference"`
	CreatedAt         time.Time       `json:"created_at"`
}

type PasswordResetToken struct {
	ID        int64              `json:"id"`
	CompanyID int64              `json:"company_id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	UsedAt    pgtype.Timestamptz `json:"used_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type PaymentMethod struct {
	ID                 int16           `json:"id"`
	Name               string          `json:"name"`
	Kind               PaymentKind     `json:"kind"`
	AffectsCashDrawer  bool            `json:"affects_cash_drawer"`
	IsActive           bool            `json:"is_active"`
	SortKey            decimal.Decimal `json:"sort_key"`
	AutoDeclare        bool            `json:"auto_declare"`
	CompanyID          int64           `json:"company_id"`
	DeliveryPlatformID *int16          `json:"delivery_platform_id"`
}

type Product struct {
	ID             int64            `json:"id"`
	Sku            *string          `json:"sku"`
	Name           string           `json:"name"`
	Description    *string          `json:"description"`
	Type           ProductType      `json:"type"`
	CategoryID     int64            `json:"category_id"`
	Price          decimal.Decimal  `json:"price"`
	CostSource     CostSource       `json:"cost_source"`
	ManualCost     *decimal.Decimal `json:"manual_cost"`
	CurrentCost    decimal.Decimal  `json:"current_cost"`
	MarginAmount   *decimal.Decimal `json:"margin_amount"`
	RecipeID       *int64           `json:"recipe_id"`
	TrackStock     bool             `json:"track_stock"`
	AllowOversell  bool             `json:"allow_oversell"`
	MinStock       *decimal.Decimal `json:"min_stock"`
	IsFavorite     bool             `json:"is_favorite"`
	SortKey        decimal.Decimal  `json:"sort_key"`
	ImageUrl       *string          `json:"image_url"`
	IsActive       bool             `json:"is_active"`
	CreatedAt      time.Time        `json:"created_at"`
	UpdatedAt      time.Time        `json:"updated_at"`
	AvailableFrom  pgtype.Date      `json:"available_from"`
	AvailableUntil pgtype.Date      `json:"available_until"`
	NeedsPrep      bool             `json:"needs_prep"`
}

type ProductChannel struct {
	ProductID  int64             `json:"product_id"`
	ChannelID  int16             `json:"channel_id"`
	Visibility ChannelVisibility `json:"visibility"`
}

type ProductModifierGroup struct {
	ID        int64   `json:"id"`
	ProductID int64   `json:"product_id"`
	GroupID   int64   `json:"group_id"`
	Title     *string `json:"title"`
	MinSelect *int16  `json:"min_select"`
	MaxSelect *int16  `json:"max_select"`
	Position  int32   `json:"position"`
}

type ProductPlatformPrice struct {
	ProductID  int64           `json:"product_id"`
	PlatformID int16           `json:"platform_id"`
	Price      decimal.Decimal `json:"price"`
	UpdatedBy  int64           `json:"updated_by"`
	UpdatedAt  time.Time       `json:"updated_at"`
	CompanyID  int64           `json:"company_id"`
}

type Recipe struct {
	ID        int64     `json:"id"`
	CreatedAt time.Time `json:"created_at"`
	UpdatedAt time.Time `json:"updated_at"`
}

type RecipeItem struct {
	ID           int64           `json:"id"`
	RecipeID     int64           `json:"recipe_id"`
	IngredientID int64           `json:"ingredient_id"`
	Quantity     decimal.Decimal `json:"quantity"`
	UnitID       int16           `json:"unit_id"`
	Position     int32           `json:"position"`
}

type RefreshToken struct {
	ID        int64              `json:"id"`
	UserID    int64              `json:"user_id"`
	TokenHash string             `json:"token_hash"`
	ExpiresAt time.Time          `json:"expires_at"`
	RevokedAt pgtype.Timestamptz `json:"revoked_at"`
	CreatedAt time.Time          `json:"created_at"`
}

type RegisterCashMovement struct {
	ID         int64           `json:"id"`
	SessionID  int64           `json:"session_id"`
	Kind       string          `json:"kind"`
	Amount     decimal.Decimal `json:"amount"`
	Concept    string          `json:"concept"`
	ExpenseID  *int64          `json:"expense_id"`
	UserID     int64           `json:"user_id"`
	CreatedAt  time.Time       `json:"created_at"`
	TransferID *int64          `json:"transfer_id"`
}

type RegisterSession struct {
	ID           int64              `json:"id"`
	BusinessDate pgtype.Date        `json:"business_date"`
	Status       SessionStatus      `json:"status"`
	OpeningCash  decimal.Decimal    `json:"opening_cash"`
	OpenedBy     int64              `json:"opened_by"`
	OpenedAt     time.Time          `json:"opened_at"`
	ClosedBy     *int64             `json:"closed_by"`
	ClosedAt     pgtype.Timestamptz `json:"closed_at"`
	Notes        *string            `json:"notes"`
	Currency     string             `json:"currency"`
	RegisterID   int64              `json:"register_id"`
}

type RegisterSessionTotal struct {
	SessionID       int64            `json:"session_id"`
	PaymentMethodID int16            `json:"payment_method_id"`
	Expected        decimal.Decimal  `json:"expected"`
	Declared        decimal.Decimal  `json:"declared"`
	Difference      *decimal.Decimal `json:"difference"`
	Tips            decimal.Decimal  `json:"tips"`
}

type StockLevel struct {
	ItemType     StockItemType   `json:"item_type"`
	IngredientID *int64          `json:"ingredient_id"`
	ProductID    *int64          `json:"product_id"`
	OnHand       decimal.Decimal `json:"on_hand"`
	UpdatedAt    time.Time       `json:"updated_at"`
}

type StockMovement struct {
	ID           int64             `json:"id"`
	ItemType     StockItemType     `json:"item_type"`
	IngredientID *int64            `json:"ingredient_id"`
	ProductID    *int64            `json:"product_id"`
	MovementType StockMovementType `json:"movement_type"`
	Quantity     decimal.Decimal   `json:"quantity"`
	UnitCost     *decimal.Decimal  `json:"unit_cost"`
	OrderID      *int64            `json:"order_id"`
	ExpenseID    *int64            `json:"expense_id"`
	UserID       *int64            `json:"user_id"`
	Reason       *string           `json:"reason"`
	Note         *string           `json:"note"`
	CreatedAt    time.Time         `json:"created_at"`
}

type Supplier struct {
	ID        int64     `json:"id"`
	Name      string    `json:"name"`
	Phone     *string   `json:"phone"`
	Notes     *string   `json:"notes"`
	IsActive  bool      `json:"is_active"`
	CreatedAt time.Time `json:"created_at"`
}

type SupplierItem struct {
	ID            int64            `json:"id"`
	SupplierID    int64            `json:"supplier_id"`
	RawCode       *string          `json:"raw_code"`
	RawName       string           `json:"raw_name"`
	NormName      string           `json:"norm_name"`
	Status        string           `json:"status"`
	ItemType      *StockItemType   `json:"item_type"`
	IngredientID  *int64           `json:"ingredient_id"`
	ProductID     *int64           `json:"product_id"`
	PackQtyInBase *decimal.Decimal `json:"pack_qty_in_base"`
	UnitID        *int16           `json:"unit_id"`
	LastCost      *decimal.Decimal `json:"last_cost"`
	LastSeenAt    time.Time        `json:"last_seen_at"`
	CreatedAt     time.Time        `json:"created_at"`
	CompanyID     int64            `json:"company_id"`
}

type Unit struct {
	ID     int16           `json:"id"`
	Code   string          `json:"code"`
	Name   string          `json:"name"`
	Kind   UnitKind        `json:"kind"`
	ToBase decimal.Decimal `json:"to_base"`
}

type User struct {
	ID                 int64     `json:"id"`
	Name               string    `json:"name"`
	Username           *string   `json:"username"`
	Role               string    `json:"role"`
	PinHash            *string   `json:"pin_hash"`
	PasswordHash       *string   `json:"password_hash"`
	IsActive           bool      `json:"is_active"`
	CreatedAt          time.Time `json:"created_at"`
	UpdatedAt          time.Time `json:"updated_at"`
	CompanyID          int64     `json:"company_id"`
	RecoveryEmail      *string   `json:"recovery_email"`
	MustChangePassword bool      `json:"must_change_password"`
}

type UserPreference struct {
	UserID    int64     `json:"user_id"`
	Key       string    `json:"key"`
	Value     []byte    `json:"value"`
	UpdatedAt time.Time `json:"updated_at"`
}
