// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: orders.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"uuid"
)

const cancelOrder = `-- name: CancelOrder :exec
update orders set status = 'cancelada', cancelled_at = now(), cancelled_by = $2, cancel_reason = $3
where id = $1
`

type CancelOrderParams struct {
	ID           int64   `json:"id"`
	CancelledBy  *int64  `json:"cancelled_by"`
	CancelReason *string `json:"cancel_reason"`
}

func (q *Queries) CancelOrder(ctx context.Context, arg CancelOrderParams) error {
	_, err := q.db.Exec(ctx, cancelOrder, arg.ID, arg.CancelledBy, arg.CancelReason)
	return err
}

const countLinesPendingDelivery = `-- name: CountLinesPendingDelivery :one
select count(*) from order_lines
where order_id = $1 and cancelled_at is null and delivered_qty < quantity
`

// Cuántos productos vivos le faltan al pedido. Alimenta la guardia del cierre de caja y el resumen
// del tablero sin traerse los renglones.
func (q *Queries) CountLinesPendingDelivery(ctx context.Context, orderID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countLinesPendingDelivery, orderID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOrder = `-- name: CreateOrder :one
insert into orders (client_uuid, business_date, daily_number, service_type, delivery_platform_id,
                    customer_name, notes, register_session_id, opened_by, subtotal, total, delivery_fee,
                    folio_name, status, completed_at)
values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,
        $14, case when $14::order_status = 'entregada' then now() end)
returning id, client_uuid, business_date, daily_number, status, service_type, delivery_platform_id, customer_name, notes, register_session_id, opened_by, subtotal, discount_total, total, opened_at, ready_at, completed_at, cancelled_at, cancelled_by, cancel_reason, updated_at, currency, refunded_at, refunded_by, refund_reason, refund_amount, delivery_fee, folio_name
`

type CreateOrderParams struct {
	ClientUuid         uuid.UUID       `json:"client_uuid"`
	BusinessDate       pgtype.Date     `json:"business_date"`
	DailyNumber        int32           `json:"daily_number"`
	ServiceType        ServiceType     `json:"service_type"`
	DeliveryPlatformID *int16          `json:"delivery_platform_id"`
	CustomerName       *string         `json:"customer_name"`
	Notes              *string         `json:"notes"`
	RegisterSessionID  *int64          `json:"register_session_id"`
	OpenedBy           int64           `json:"opened_by"`
	Subtotal           decimal.Decimal `json:"subtotal"`
	Total              decimal.Decimal `json:"total"`
	DeliveryFee        decimal.Decimal `json:"delivery_fee"`
	FolioName          *string         `json:"folio_name"`
	Status             OrderStatus     `json:"status"`
}

// status y completed_at los decide quien llama: un pedido que se cobra y se entrega en el mismo
// acto —el refresco de mostrador— nace entregado y nunca pasa por el tablero. El resto nace abierto.
func (q *Queries) CreateOrder(ctx context.Context, arg CreateOrderParams) (Order, error) {
	row := q.db.QueryRow(ctx, createOrder,
		arg.ClientUuid,
		arg.BusinessDate,
		arg.DailyNumber,
		arg.ServiceType,
		arg.DeliveryPlatformID,
		arg.CustomerName,
		arg.Notes,
		arg.RegisterSessionID,
		arg.OpenedBy,
		arg.Subtotal,
		arg.Total,
		arg.DeliveryFee,
		arg.FolioName,
		arg.Status,
	)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.BusinessDate,
		&i.DailyNumber,
		&i.Status,
		&i.ServiceType,
		&i.DeliveryPlatformID,
		&i.CustomerName,
		&i.Notes,
		&i.RegisterSessionID,
		&i.OpenedBy,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.Total,
		&i.OpenedAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.UpdatedAt,
		&i.Currency,
		&i.RefundedAt,
		&i.RefundedBy,
		&i.RefundReason,
		&i.RefundAmount,
		&i.DeliveryFee,
		&i.FolioName,
	)
	return i, err
}

const createOrderLine = `-- name: CreateOrderLine :one
insert into order_lines (order_id, product_id, product_name, quantity, unit_price,
                         modifiers_total, unit_cost, line_total, notes, delivered_qty)
values ($1,$2,$3,$4,$5,$6,$7,$8,$9,
        case when $10::boolean then $4::numeric else 0::numeric end)
returning id
`

type CreateOrderLineParams struct {
	OrderID        int64           `json:"order_id"`
	ProductID      int64           `json:"product_id"`
	ProductName    string          `json:"product_name"`
	Quantity       decimal.Decimal `json:"quantity"`
	UnitPrice      decimal.Decimal `json:"unit_price"`
	ModifiersTotal decimal.Decimal `json:"modifiers_total"`
	UnitCost       decimal.Decimal `json:"unit_cost"`
	LineTotal      decimal.Decimal `json:"line_total"`
	Notes          *string         `json:"notes"`
	NaceEntregada  bool            `json:"nace_entregada"`
}

func (q *Queries) CreateOrderLine(ctx context.Context, arg CreateOrderLineParams) (int64, error) {
	row := q.db.QueryRow(ctx, createOrderLine,
		arg.OrderID,
		arg.ProductID,
		arg.ProductName,
		arg.Quantity,
		arg.UnitPrice,
		arg.ModifiersTotal,
		arg.UnitCost,
		arg.LineTotal,
		arg.Notes,
		arg.NaceEntregada,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const createOrderLineModifier = `-- name: CreateOrderLineModifier :exec
insert into order_line_modifiers (order_line_id, modifier_option_id, group_title, option_name,
                                  quantity, price_delta, unit_cost)
values ($1,$2,$3,$4,$5,$6,$7)
`

type CreateOrderLineModifierParams struct {
	OrderLineID      int64           `json:"order_line_id"`
	ModifierOptionID int64           `json:"modifier_option_id"`
	GroupTitle       string          `json:"group_title"`
	OptionName       string          `json:"option_name"`
	Quantity         int16           `json:"quantity"`
	PriceDelta       decimal.Decimal `json:"price_delta"`
	UnitCost         decimal.Decimal `json:"unit_cost"`
}

func (q *Queries) CreateOrderLineModifier(ctx context.Context, arg CreateOrderLineModifierParams) error {
	_, err := q.db.Exec(ctx, createOrderLineModifier,
		arg.OrderLineID,
		arg.ModifierOptionID,
		arg.GroupTitle,
		arg.OptionName,
		arg.Quantity,
		arg.PriceDelta,
		arg.UnitCost,
	)
	return err
}

const createOrderPayment = `-- name: CreateOrderPayment :exec
insert into order_payments (order_id, payment_method_id, amount, tip_amount, register_session_id, received_by, reference)
values ($1,$2,$3,$4,$5,$6,$7)
`

type CreateOrderPaymentParams struct {
	OrderID           int64           `json:"order_id"`
	PaymentMethodID   int16           `json:"payment_method_id"`
	Amount            decimal.Decimal `json:"amount"`
	TipAmount         decimal.Decimal `json:"tip_amount"`
	RegisterSessionID *int64          `json:"register_session_id"`
	ReceivedBy        *int64          `json:"received_by"`
	Reference         *string         `json:"reference"`
}

func (q *Queries) CreateOrderPayment(ctx context.Context, arg CreateOrderPaymentParams) error {
	_, err := q.db.Exec(ctx, createOrderPayment,
		arg.OrderID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.TipAmount,
		arg.RegisterSessionID,
		arg.ReceivedBy,
		arg.Reference,
	)
	return err
}

const deliverAllOrderLines = `-- name: DeliverAllOrderLines :exec
update order_lines
   set delivered_qty = quantity
 where order_id = $1 and cancelled_at is null
`

// "Entregar todo": el camino de un tap, que es el caso común. Lo cancelado se queda como está.
func (q *Queries) DeliverAllOrderLines(ctx context.Context, orderID int64) error {
	_, err := q.db.Exec(ctx, deliverAllOrderLines, orderID)
	return err
}

const deliverOrderLine = `-- name: DeliverOrderLine :execrows
update order_lines
   set delivered_qty = delivered_qty + $1::numeric
 where id = $2
   and order_id = $3
   and cancelled_at is null
   and delivered_qty + $1::numeric <= quantity
`

type DeliverOrderLineParams struct {
	Cantidad decimal.Decimal `json:"cantidad"`
	LineID   int64           `json:"line_id"`
	OrderID  int64           `json:"order_id"`
}

// Suma a lo ya entregado de un renglón. El tope contra `quantity` lo repite aquí la base aunque el
// dominio ya lo validó: entre validar y escribir cabe otra transacción entregando lo mismo, y el
// resultado sería un renglón con más entregado de lo que se pidió.
func (q *Queries) DeliverOrderLine(ctx context.Context, arg DeliverOrderLineParams) (int64, error) {
	result, err := q.db.Exec(ctx, deliverOrderLine, arg.Cantidad, arg.LineID, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const folioNamesUsedToday = `-- name: FolioNamesUsedToday :many
select folio_name from orders
where business_date = $1 and folio_name is not null
`

// Los nombres ya repartidos hoy, para no repetir uno cuando la pantalla propone el suyo.
//
// Se lee dentro de la MISMA transacción que toma NextDailyNumber, y eso es lo que la hace segura:
// ese insert bloquea la fila del contador del día hasta el commit, así que dos ventas de la misma
// empresa y fecha no pueden estar aquí a la vez. Sin ese lock haría falta uno propio.
func (q *Queries) FolioNamesUsedToday(ctx context.Context, businessDate pgtype.Date) ([]*string, error) {
	rows, err := q.db.Query(ctx, folioNamesUsedToday, businessDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []*string{}
	for rows.Next() {
		var folio_name *string
		if err := rows.Scan(&folio_name); err != nil {
			return nil, err
		}
		items = append(items, folio_name)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getOrder = `-- name: GetOrder :one
select id, client_uuid, business_date, daily_number, status, service_type, delivery_platform_id, customer_name, notes, register_session_id, opened_by, subtotal, discount_total, total, opened_at, ready_at, completed_at, cancelled_at, cancelled_by, cancel_reason, updated_at, currency, refunded_at, refunded_by, refund_reason, refund_amount, delivery_fee, folio_name from orders where id = $1
`

func (q *Queries) GetOrder(ctx context.Context, id int64) (Order, error) {
	row := q.db.QueryRow(ctx, getOrder, id)
	var i Order
	err := row.Scan(
		&i.ID,
		&i.ClientUuid,
		&i.BusinessDate,
		&i.DailyNumber,
		&i.Status,
		&i.ServiceType,
		&i.DeliveryPlatformID,
		&i.CustomerName,
		&i.Notes,
		&i.RegisterSessionID,
		&i.OpenedBy,
		&i.Subtotal,
		&i.DiscountTotal,
		&i.Total,
		&i.OpenedAt,
		&i.ReadyAt,
		&i.CompletedAt,
		&i.CancelledAt,
		&i.CancelledBy,
		&i.CancelReason,
		&i.UpdatedAt,
		&i.Currency,
		&i.RefundedAt,
		&i.RefundedBy,
		&i.RefundReason,
		&i.RefundAmount,
		&i.DeliveryFee,
		&i.FolioName,
	)
	return i, err
}

const getOrderForUpdate = `-- name: GetOrderForUpdate :one
select id, status, service_type, delivery_platform_id
from orders where id = $1
for update
`

type GetOrderForUpdateRow struct {
	ID                 int64       `json:"id"`
	Status             OrderStatus `json:"status"`
	ServiceType        ServiceType `json:"service_type"`
	DeliveryPlatformID *int16      `json:"delivery_platform_id"`
}

// El pedido al que se le va a agregar, bloqueado dentro de la transacción: dos meseros agregando a
// la misma cuenta al mismo tiempo recalcularían el total sobre el estado viejo y uno de los dos
// agregados desaparecería del importe.
func (q *Queries) GetOrderForUpdate(ctx context.Context, id int64) (GetOrderForUpdateRow, error) {
	row := q.db.QueryRow(ctx, getOrderForUpdate, id)
	var i GetOrderForUpdateRow
	err := row.Scan(
		&i.ID,
		&i.Status,
		&i.ServiceType,
		&i.DeliveryPlatformID,
	)
	return i, err
}

const getOrderIDByClientUUID = `-- name: GetOrderIDByClientUUID :one
select id from orders where client_uuid = $1
`

func (q *Queries) GetOrderIDByClientUUID(ctx context.Context, clientUuid uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, getOrderIDByClientUUID, clientUuid)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const getPricedOptions = `-- name: GetPricedOptions :many
select mo.id, mo.name, mo.price_delta, mo.current_cost, mo.max_per_line, mg.name as group_title
from modifier_options mo
join modifier_groups mg on mg.id = mo.group_id
where mo.id = any($1::bigint[])
`

type GetPricedOptionsRow struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	PriceDelta  decimal.Decimal `json:"price_delta"`
	CurrentCost decimal.Decimal `json:"current_cost"`
	MaxPerLine  int16           `json:"max_per_line"`
	GroupTitle  string          `json:"group_title"`
}

// max_per_line viaja porque el servidor lo valida: es el tope de veces que una opción puede ir en
// la misma línea, y desde que la pantalla deja pedir dos salsas del mismo sabor deja de ser un
// valor que nadie ejercía.
func (q *Queries) GetPricedOptions(ctx context.Context, dollar_1 []int64) ([]GetPricedOptionsRow, error) {
	rows, err := q.db.Query(ctx, getPricedOptions, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPricedOptionsRow{}
	for rows.Next() {
		var i GetPricedOptionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.PriceDelta,
			&i.CurrentCost,
			&i.MaxPerLine,
			&i.GroupTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPricedProducts = `-- name: GetPricedProducts :many

select id, name, price, current_cost, is_active, needs_prep
from products where id = any($1::bigint[])
`

type GetPricedProductsRow struct {
	ID          int64           `json:"id"`
	Name        string          `json:"name"`
	Price       decimal.Decimal `json:"price"`
	CurrentCost decimal.Decimal `json:"current_cost"`
	IsActive    bool            `json:"is_active"`
	NeedsPrep   bool            `json:"needs_prep"`
}

// Pricing (autoritativo en el servidor)
func (q *Queries) GetPricedProducts(ctx context.Context, dollar_1 []int64) ([]GetPricedProductsRow, error) {
	rows, err := q.db.Query(ctx, getPricedProducts, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetPricedProductsRow{}
	for rows.Next() {
		var i GetPricedProductsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Price,
			&i.CurrentCost,
			&i.IsActive,
			&i.NeedsPrep,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listActiveOrders = `-- name: ListActiveOrders :many

select o.id, o.daily_number, o.folio_name, o.status, o.service_type, o.customer_name, o.total, o.currency,
       o.opened_at, o.ready_at,
       coalesce((select sum(amount) from order_payments p where p.order_id = o.id), 0)::numeric(10,2) as paid,
       (select count(*) from order_lines l
         where l.order_id = o.id and l.cancelled_at is null)::int as lineas_vivas,
       (select count(*) from order_lines l
         where l.order_id = o.id and l.cancelled_at is null and l.delivered_qty >= l.quantity)::int as lineas_entregadas
from orders o
where o.status in ('abierta','lista')
order by o.opened_at
`

type ListActiveOrdersRow struct {
	ID               int64              `json:"id"`
	DailyNumber      int32              `json:"daily_number"`
	FolioName        *string            `json:"folio_name"`
	Status           OrderStatus        `json:"status"`
	ServiceType      ServiceType        `json:"service_type"`
	CustomerName     *string            `json:"customer_name"`
	Total            decimal.Decimal    `json:"total"`
	Currency         string             `json:"currency"`
	OpenedAt         time.Time          `json:"opened_at"`
	ReadyAt          pgtype.Timestamptz `json:"ready_at"`
	Paid             decimal.Decimal    `json:"paid"`
	LineasVivas      int32              `json:"lineas_vivas"`
	LineasEntregadas int32              `json:"lineas_entregadas"`
}

// Board / detalle
func (q *Queries) ListActiveOrders(ctx context.Context) ([]ListActiveOrdersRow, error) {
	rows, err := q.db.Query(ctx, listActiveOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListActiveOrdersRow{}
	for rows.Next() {
		var i ListActiveOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.DailyNumber,
			&i.FolioName,
			&i.Status,
			&i.ServiceType,
			&i.CustomerName,
			&i.Total,
			&i.Currency,
			&i.OpenedAt,
			&i.ReadyAt,
			&i.Paid,
			&i.LineasVivas,
			&i.LineasEntregadas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDeliveredToday = `-- name: ListDeliveredToday :many
select o.id, o.daily_number, o.folio_name, o.status, o.service_type, o.customer_name, o.total, o.currency,
       o.opened_at, o.ready_at,
       coalesce((select sum(amount) from order_payments p where p.order_id = o.id), 0)::numeric(10,2) as paid,
       (select count(*) from order_lines l
         where l.order_id = o.id and l.cancelled_at is null)::int as lineas_vivas,
       (select count(*) from order_lines l
         where l.order_id = o.id and l.cancelled_at is null and l.delivered_qty >= l.quantity)::int as lineas_entregadas
from orders o
where o.status = 'entregada' and o.business_date = $1
order by o.completed_at desc nulls last, o.id desc
`

type ListDeliveredTodayRow struct {
	ID               int64              `json:"id"`
	DailyNumber      int32              `json:"daily_number"`
	FolioName        *string            `json:"folio_name"`
	Status           OrderStatus        `json:"status"`
	ServiceType      ServiceType        `json:"service_type"`
	CustomerName     *string            `json:"customer_name"`
	Total            decimal.Decimal    `json:"total"`
	Currency         string             `json:"currency"`
	OpenedAt         time.Time          `json:"opened_at"`
	ReadyAt          pgtype.Timestamptz `json:"ready_at"`
	Paid             decimal.Decimal    `json:"paid"`
	LineasVivas      int32              `json:"lineas_vivas"`
	LineasEntregadas int32              `json:"lineas_entregadas"`
}

// Órdenes entregadas del día (para la sección de reembolsos del tablero). Acotada a la
// fecha de negocio para no arrastrar todo el histórico.
func (q *Queries) ListDeliveredToday(ctx context.Context, businessDate pgtype.Date) ([]ListDeliveredTodayRow, error) {
	rows, err := q.db.Query(ctx, listDeliveredToday, businessDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListDeliveredTodayRow{}
	for rows.Next() {
		var i ListDeliveredTodayRow
		if err := rows.Scan(
			&i.ID,
			&i.DailyNumber,
			&i.FolioName,
			&i.Status,
			&i.ServiceType,
			&i.CustomerName,
			&i.Total,
			&i.Currency,
			&i.OpenedAt,
			&i.ReadyAt,
			&i.Paid,
			&i.LineasVivas,
			&i.LineasEntregadas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLinesForDelivery = `-- name: ListLinesForDelivery :many
select id, quantity, delivered_qty, cancelled_at
from order_lines
where order_id = $1
order by id
for update
`

type ListLinesForDeliveryRow struct {
	ID           int64              `json:"id"`
	Quantity     decimal.Decimal    `json:"quantity"`
	DeliveredQty decimal.Decimal    `json:"delivered_qty"`
	CancelledAt  pgtype.Timestamptz `json:"cancelled_at"`
}

// Lo mínimo para razonar sobre la entrega de un pedido: ni precio ni producto, porque entregar no
// mueve dinero. `for update` porque de esto cuelga el cierre automático del pedido, y dos personas
// marcando renglones a la vez podrían dejarlo abierto con todo entregado.
func (q *Queries) ListLinesForDelivery(ctx context.Context, orderID int64) ([]ListLinesForDeliveryRow, error) {
	rows, err := q.db.Query(ctx, listLinesForDelivery, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinesForDeliveryRow{}
	for rows.Next() {
		var i ListLinesForDeliveryRow
		if err := rows.Scan(
			&i.ID,
			&i.Quantity,
			&i.DeliveredQty,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderLineModifiers = `-- name: ListOrderLineModifiers :many
select olm.order_line_id, olm.group_title, olm.option_name, olm.quantity, olm.price_delta
from order_line_modifiers olm
join order_lines ol on ol.id = olm.order_line_id
where ol.order_id = $1
`

type ListOrderLineModifiersRow struct {
	OrderLineID int64           `json:"order_line_id"`
	GroupTitle  string          `json:"group_title"`
	OptionName  string          `json:"option_name"`
	Quantity    int16           `json:"quantity"`
	PriceDelta  decimal.Decimal `json:"price_delta"`
}

func (q *Queries) ListOrderLineModifiers(ctx context.Context, orderID int64) ([]ListOrderLineModifiersRow, error) {
	rows, err := q.db.Query(ctx, listOrderLineModifiers, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderLineModifiersRow{}
	for rows.Next() {
		var i ListOrderLineModifiersRow
		if err := rows.Scan(
			&i.OrderLineID,
			&i.GroupTitle,
			&i.OptionName,
			&i.Quantity,
			&i.PriceDelta,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderLines = `-- name: ListOrderLines :many
select id, product_id, product_name, quantity, unit_price, modifiers_total, line_total, notes,
       delivered_qty, cancelled_at
from order_lines where order_id = $1 order by id
`

type ListOrderLinesRow struct {
	ID             int64              `json:"id"`
	ProductID      int64              `json:"product_id"`
	ProductName    string             `json:"product_name"`
	Quantity       decimal.Decimal    `json:"quantity"`
	UnitPrice      decimal.Decimal    `json:"unit_price"`
	ModifiersTotal decimal.Decimal    `json:"modifiers_total"`
	LineTotal      decimal.Decimal    `json:"line_total"`
	Notes          *string            `json:"notes"`
	DeliveredQty   decimal.Decimal    `json:"delivered_qty"`
	CancelledAt    pgtype.Timestamptz `json:"cancelled_at"`
}

func (q *Queries) ListOrderLines(ctx context.Context, orderID int64) ([]ListOrderLinesRow, error) {
	rows, err := q.db.Query(ctx, listOrderLines, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderLinesRow{}
	for rows.Next() {
		var i ListOrderLinesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProductID,
			&i.ProductName,
			&i.Quantity,
			&i.UnitPrice,
			&i.ModifiersTotal,
			&i.LineTotal,
			&i.Notes,
			&i.DeliveredQty,
			&i.CancelledAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrderPayments = `-- name: ListOrderPayments :many
select id, payment_method_id, amount, tip_amount, created_at from order_payments where order_id = $1
`

type ListOrderPaymentsRow struct {
	ID              int64           `json:"id"`
	PaymentMethodID int16           `json:"payment_method_id"`
	Amount          decimal.Decimal `json:"amount"`
	TipAmount       decimal.Decimal `json:"tip_amount"`
	CreatedAt       time.Time       `json:"created_at"`
}

func (q *Queries) ListOrderPayments(ctx context.Context, orderID int64) ([]ListOrderPaymentsRow, error) {
	rows, err := q.db.Query(ctx, listOrderPayments, orderID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOrderPaymentsRow{}
	for rows.Next() {
		var i ListOrderPaymentsRow
		if err := rows.Scan(
			&i.ID,
			&i.PaymentMethodID,
			&i.Amount,
			&i.TipAmount,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const nextDailyNumber = `-- name: NextDailyNumber :one

insert into order_counters (business_date, last_number)
values ($1, 1)
on conflict on constraint order_counters_pkey do update set last_number = order_counters.last_number + 1
returning last_number
`

// Creación
// company_id lo auto-sella el default (GUC del tenant); el folio diario es por-empresa. Se
// arbitra por NOMBRE de la PK compuesta (company_id, business_date): referir la columna por
// nombre haría fallar a sqlc, que no ve las columnas agregadas dinámicamente en la migración.
func (q *Queries) NextDailyNumber(ctx context.Context, businessDate pgtype.Date) (int32, error) {
	row := q.db.QueryRow(ctx, nextDailyNumber, businessDate)
	var last_number int32
	err := row.Scan(&last_number)
	return last_number, err
}

const recalcOrderTotals = `-- name: RecalcOrderTotals :exec
update orders o
set subtotal = coalesce((select sum(ol.line_total) from order_lines ol
                          where ol.order_id = o.id and ol.cancelled_at is null), 0),
    total    = coalesce((select sum(ol.line_total) from order_lines ol
                          where ol.order_id = o.id and ol.cancelled_at is null), 0) + o.delivery_fee,
    updated_at = now()
where o.id = $1
`

// Recalcula el total del pedido desde SUS renglones, después de agregarle más.
//
// Se suma en la base y no en Go a propósito: los renglones ya guardados son la verdad, y volver a
// calcularlos desde el comando obligaría a traerlos, re-precisarlos con la lista de precios de HOY
// —que puede haber cambiado— y reescribirlos. Un pedido de ayer cambiaría de precio por agregarle
// un café.
//
// El envío no se toca: se decidió al crear el pedido y agregar renglones no lo cambia.
func (q *Queries) RecalcOrderTotals(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, recalcOrderTotals, id)
	return err
}

const recentModifierPicks = `-- name: RecentModifierPicks :many
select ol.product_id, mo.group_id, olm.modifier_option_id::bigint as option_id, ol.created_at
from order_line_modifiers olm
join order_lines ol on ol.id = olm.order_line_id
join modifier_options mo on mo.id = olm.modifier_option_id
join orders o on o.id = ol.order_id
where o.status <> 'cancelada'
  and ol.created_at >= now() - interval '90 days'
`

type RecentModifierPicksRow struct {
	ProductID int64     `json:"product_id"`
	GroupID   int64     `json:"group_id"`
	OptionID  int64     `json:"option_id"`
	CreatedAt time.Time `json:"created_at"`
}

// Histórico de opciones elegidas por producto/grupo, para defaults contextuales.
// Excluye canceladas y limita la ventana (el decaimiento por recencia hace irrelevante lo viejo).
func (q *Queries) RecentModifierPicks(ctx context.Context) ([]RecentModifierPicksRow, error) {
	rows, err := q.db.Query(ctx, recentModifierPicks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RecentModifierPicksRow{}
	for rows.Next() {
		var i RecentModifierPicksRow
		if err := rows.Scan(
			&i.ProductID,
			&i.GroupID,
			&i.OptionID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundOrder = `-- name: RefundOrder :exec
update orders set status = 'reembolsada', refunded_at = now(),
  refunded_by = $2, refund_reason = $3, refund_amount = $4
where id = $1
`

type RefundOrderParams struct {
	ID           int64           `json:"id"`
	RefundedBy   *int64          `json:"refunded_by"`
	RefundReason *string         `json:"refund_reason"`
	RefundAmount decimal.Decimal `json:"refund_amount"`
}

// Devolución de una orden entregada: la marca 'reembolsada' (pérdida). Sin restock.
func (q *Queries) RefundOrder(ctx context.Context, arg RefundOrderParams) error {
	_, err := q.db.Exec(ctx, refundOrder,
		arg.ID,
		arg.RefundedBy,
		arg.RefundReason,
		arg.RefundAmount,
	)
	return err
}

const restockCancelledOrder = `-- name: RestockCancelledOrder :exec
insert into stock_movements (item_type, ingredient_id, product_id, movement_type, quantity, order_id, user_id, reason)
select sm.item_type, sm.ingredient_id, sm.product_id, 'cancelacion', -sm.quantity, sm.order_id, $1, 'cancelación de orden'
from stock_movements sm where sm.order_id = $2 and sm.movement_type = 'venta'
`

type RestockCancelledOrderParams struct {
	ActorID *int64 `json:"actor_id"`
	Oid     *int64 `json:"oid"`
}

// Repone el stock de una orden cancelada: movimientos 'cancelacion' que invierten las ventas.
func (q *Queries) RestockCancelledOrder(ctx context.Context, arg RestockCancelledOrderParams) error {
	_, err := q.db.Exec(ctx, restockCancelledOrder, arg.ActorID, arg.Oid)
	return err
}

const setOrderStatus = `-- name: SetOrderStatus :exec
update orders set status = $2,
  ready_at = case when $2 = 'lista'::order_status then now() else ready_at end,
  completed_at = case when $2 = 'entregada'::order_status then now() else completed_at end
where id = $1
`

type SetOrderStatusParams struct {
	ID     int64       `json:"id"`
	Status OrderStatus `json:"status"`
}

func (q *Queries) SetOrderStatus(ctx context.Context, arg SetOrderStatusParams) error {
	_, err := q.db.Exec(ctx, setOrderStatus, arg.ID, arg.Status)
	return err
}
