// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pedidos_de_plataforma.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
	"uuid"
)

const acceptIncomingOrder = `-- name: AcceptIncomingOrder :execrows
update platform_incoming_orders
   set state = 'aceptado', settled_at = now(), decided_by = $2, order_id = $3
 where id = $1 and state = 'pendiente'
`

type AcceptIncomingOrderParams struct {
	ID        int64  `json:"id"`
	DecidedBy *int64 `json:"decided_by"`
	OrderID   *int64 `json:"order_id"`
}

// `where state = 'pendiente'` DENTRO del update, no en un select previo: dos tabletas pueden tocar
// Aceptar al mismo tiempo, y quien no gane tiene que enterarse. Con :execrows, cero filas significa
// «ya estaba decidido» y el handler responde 409 en vez de fingir que hizo algo.
func (q *Queries) AcceptIncomingOrder(ctx context.Context, arg AcceptIncomingOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, acceptIncomingOrder, arg.ID, arg.DecidedBy, arg.OrderID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const candidatasDelAviso = `-- name: CandidatasDelAviso :many

select connection_id, company_id, is_active
  from candidatas_del_aviso
 where external_store_id = $1 and lower(platform_name) = lower($2::text)
 order by connection_id
`

type CandidatasDelAvisoParams struct {
	ExternalStoreID string `json:"external_store_id"`
	PlatformName    string `json:"platform_name"`
}

type CandidatasDelAvisoRow struct {
	ConnectionID int64 `json:"connection_id"`
	CompanyID    int64 `json:"company_id"`
	IsActive     bool  `json:"is_active"`
}

// ---------------------------------------------------------------------------------------------
// Resolver de qué empresa es un aviso
// ---------------------------------------------------------------------------------------------
//
// LA ÚNICA CONSULTA DEL REPOSITORIO QUE CORRE SIN EMPRESA FIJADA, y tiene que ser así: quien llama
// al webhook es la plataforma, no una persona. No hay sesión, no hay JWT y por lo tanto no hay
// `app.company_id` — la empresa ES EL RESULTADO de esta consulta, no su entrada.
//
// Va contra la VISTA `candidatas_del_aviso` y no contra las tablas, y esa es toda la diferencia:
// la vista pertenece a un rol propio que sí ve todas las filas, así que la excepción vive en el
// catálogo de Postgres —se lee en `\d`— y no en un comentario que defiende un `store.Q`.
//
// NO DEVUELVE NINGUNA LLAVE, a propósito. Un `select` sin filtro sobre esta vista revela, como
// mucho, qué id de tienda es de qué empresa. Con las llaves adentro revelaría las llaves de firma
// de TODAS las empresas, y cualquiera que la alcanzara podría firmar avisos a nombre de quien
// quisiera. La llave de cada candidata se lee después, ya con el tenant fijado.
//
// DEVUELVE VARIAS FILAS A PROPÓSITO: dos empresas pueden registrar el mismo id de tienda —pasa en
// el ambiente de pruebas, donde las plataformas reparten tiendas de demostración compartidas—.
// Quién se lo queda lo decide el servicio, no esta consulta.
func (q *Queries) CandidatasDelAviso(ctx context.Context, arg CandidatasDelAvisoParams) ([]CandidatasDelAvisoRow, error) {
	rows, err := q.db.Query(ctx, candidatasDelAviso, arg.ExternalStoreID, arg.PlatformName)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CandidatasDelAvisoRow{}
	for rows.Next() {
		var i CandidatasDelAvisoRow
		if err := rows.Scan(&i.ConnectionID, &i.CompanyID, &i.IsActive); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const claimPlatformOrder = `-- name: ClaimPlatformOrder :exec
update orders
   set register_session_id = $2, daily_number = $3
 where id = $1 and register_session_id is null
`

type ClaimPlatformOrderParams struct {
	ID                int64  `json:"id"`
	RegisterSessionID *int64 `json:"register_session_id"`
	DailyNumber       int32  `json:"daily_number"`
}

// Le da turno y folio real a UN pedido huérfano. Va dentro de la transacción que abre el turno.
func (q *Queries) ClaimPlatformOrder(ctx context.Context, arg ClaimPlatformOrderParams) error {
	_, err := q.db.Exec(ctx, claimPlatformOrder, arg.ID, arg.RegisterSessionID, arg.DailyNumber)
	return err
}

const createPlatformOrderPayment = `-- name: CreatePlatformOrderPayment :exec
insert into order_payments (order_id, payment_method_id, amount, register_session_id, received_by,
                            reference, client_uuid)
values ($1, $2, $3, $4, $5, $6, $7)
`

type CreatePlatformOrderPaymentParams struct {
	OrderID           int64           `json:"order_id"`
	PaymentMethodID   int16           `json:"payment_method_id"`
	Amount            decimal.Decimal `json:"amount"`
	RegisterSessionID *int64          `json:"register_session_id"`
	ReceivedBy        *int64          `json:"received_by"`
	Reference         *string         `json:"reference"`
	ClientUuid        *uuid.UUID      `json:"client_uuid"`
}

// El pago de un pedido de plataforma. `register_session_id` puede ir NULL: la cocina no espera a
// que alguien abra caja, y el pedido se enlaza al turno que se abra después.
func (q *Queries) CreatePlatformOrderPayment(ctx context.Context, arg CreatePlatformOrderPaymentParams) error {
	_, err := q.db.Exec(ctx, createPlatformOrderPayment,
		arg.OrderID,
		arg.PaymentMethodID,
		arg.Amount,
		arg.RegisterSessionID,
		arg.ReceivedBy,
		arg.Reference,
		arg.ClientUuid,
	)
	return err
}

const denyIncomingOrder = `-- name: DenyIncomingOrder :execrows
update platform_incoming_orders
   set state = 'rechazado', settled_at = now(), decided_by = $2, deny_reason = $3
 where id = $1 and state = 'pendiente'
`

type DenyIncomingOrderParams struct {
	ID         int64   `json:"id"`
	DecidedBy  *int64  `json:"decided_by"`
	DenyReason *string `json:"deny_reason"`
}

func (q *Queries) DenyIncomingOrder(ctx context.Context, arg DenyIncomingOrderParams) (int64, error) {
	result, err := q.db.Exec(ctx, denyIncomingOrder, arg.ID, arg.DecidedBy, arg.DenyReason)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const finishWebhookKeyRotation = `-- name: FinishWebhookKeyRotation :execrows
update platform_webhook_keys
   set key_secondary = null, rotated_at = null
 where delivery_platform_id = $1
`

// Cierra la rotación tirando la llave vieja. Una secundaria que nadie retira se queda válida para
// siempre y nadie se entera: `rotated_at` existe para poder delatarla.
func (q *Queries) FinishWebhookKeyRotation(ctx context.Context, deliveryPlatformID int16) (int64, error) {
	result, err := q.db.Exec(ctx, finishWebhookKeyRotation, deliveryPlatformID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getIncomingOrder = `-- name: GetIncomingOrder :one
select o.id, o.connection_id, p.name as platform_name, o.external_order_id, o.display_id,
       o.placed_at, o.decide_before, o.state, o.service_type, o.customer_name, o.total,
       o.order_id, o.decided_by, o.settled_at, o.deny_reason
  from platform_incoming_orders o
  join platform_connections c on c.id = o.connection_id
  join delivery_platforms p on p.id = c.delivery_platform_id
 where o.id = $1
`

type GetIncomingOrderRow struct {
	ID              int64              `json:"id"`
	ConnectionID    int64              `json:"connection_id"`
	PlatformName    string             `json:"platform_name"`
	ExternalOrderID string             `json:"external_order_id"`
	DisplayID       *string            `json:"display_id"`
	PlacedAt        pgtype.Timestamptz `json:"placed_at"`
	DecideBefore    pgtype.Timestamptz `json:"decide_before"`
	State           PlatformOrderState `json:"state"`
	ServiceType     ServiceType        `json:"service_type"`
	CustomerName    *string            `json:"customer_name"`
	Total           *decimal.Decimal   `json:"total"`
	OrderID         *int64             `json:"order_id"`
	DecidedBy       *int64             `json:"decided_by"`
	SettledAt       pgtype.Timestamptz `json:"settled_at"`
	DenyReason      *string            `json:"deny_reason"`
}

func (q *Queries) GetIncomingOrder(ctx context.Context, id int64) (GetIncomingOrderRow, error) {
	row := q.db.QueryRow(ctx, getIncomingOrder, id)
	var i GetIncomingOrderRow
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.PlatformName,
		&i.ExternalOrderID,
		&i.DisplayID,
		&i.PlacedAt,
		&i.DecideBefore,
		&i.State,
		&i.ServiceType,
		&i.CustomerName,
		&i.Total,
		&i.OrderID,
		&i.DecidedBy,
		&i.SettledAt,
		&i.DenyReason,
	)
	return i, err
}

const getIncomingOrderByExternalID = `-- name: GetIncomingOrderByExternalID :one
select id, connection_id, state, order_id
  from platform_incoming_orders
 where connection_id = $1 and external_order_id = $2
`

type GetIncomingOrderByExternalIDParams struct {
	ConnectionID    int64  `json:"connection_id"`
	ExternalOrderID string `json:"external_order_id"`
}

type GetIncomingOrderByExternalIDRow struct {
	ID           int64              `json:"id"`
	ConnectionID int64              `json:"connection_id"`
	State        PlatformOrderState `json:"state"`
	OrderID      *int64             `json:"order_id"`
}

func (q *Queries) GetIncomingOrderByExternalID(ctx context.Context, arg GetIncomingOrderByExternalIDParams) (GetIncomingOrderByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getIncomingOrderByExternalID, arg.ConnectionID, arg.ExternalOrderID)
	var i GetIncomingOrderByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.ConnectionID,
		&i.State,
		&i.OrderID,
	)
	return i, err
}

const getPlatformPaymentMethod = `-- name: GetPlatformPaymentMethod :one
select id from payment_methods
 where delivery_platform_id = $1
   and is_active
   and (name ilike '%efectivo%') = $2::boolean
 limit 1
`

type GetPlatformPaymentMethodParams struct {
	DeliveryPlatformID *int16 `json:"delivery_platform_id"`
	EnEfectivo         bool   `json:"en_efectivo"`
}

// El método de pago de una plataforma, en línea o en efectivo.
//
// Existe uno por plataforma y por forma de cobro («Uber Eats en línea», «Uber Eats efectivo»)
// desde antes de esta feature, porque la captura manual ya los usaba. Aquí solo se elige el que
// corresponde: un pedido que el cliente pagó en la app NO es lo mismo que uno contra entrega, y
// meterlos en el mismo cajón hace que el corte pida efectivo que nadie recibió.
func (q *Queries) GetPlatformPaymentMethod(ctx context.Context, arg GetPlatformPaymentMethodParams) (int16, error) {
	row := q.db.QueryRow(ctx, getPlatformPaymentMethod, arg.DeliveryPlatformID, arg.EnEfectivo)
	var id int16
	err := row.Scan(&id)
	return id, err
}

const getWebhookEventByExternalID = `-- name: GetWebhookEventByExternalID :one
select id, event_id, event_type, connection_id, processed_at, outcome, failure_kind
  from platform_webhook_events
 where event_id = $1
`

type GetWebhookEventByExternalIDRow struct {
	ID           int64              `json:"id"`
	EventID      string             `json:"event_id"`
	EventType    string             `json:"event_type"`
	ConnectionID int64              `json:"connection_id"`
	ProcessedAt  pgtype.Timestamptz `json:"processed_at"`
	Outcome      *string            `json:"outcome"`
	FailureKind  *string            `json:"failure_kind"`
}

func (q *Queries) GetWebhookEventByExternalID(ctx context.Context, eventID string) (GetWebhookEventByExternalIDRow, error) {
	row := q.db.QueryRow(ctx, getWebhookEventByExternalID, eventID)
	var i GetWebhookEventByExternalIDRow
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.EventType,
		&i.ConnectionID,
		&i.ProcessedAt,
		&i.Outcome,
		&i.FailureKind,
	)
	return i, err
}

const getWebhookKeyState = `-- name: GetWebhookKeyState :one
select (key_primary is not null) as configurada,
       (key_secondary is not null) as rotando,
       rotated_at
  from platform_webhook_keys
 where delivery_platform_id = $1
`

type GetWebhookKeyStateRow struct {
	Configurada interface{}        `json:"configurada"`
	Rotando     interface{}        `json:"rotando"`
	RotatedAt   pgtype.Timestamptz `json:"rotated_at"`
}

// Para la pantalla. Devuelve SI HAY llave, no la llave: un secreto que se puede volver a leer desde
// la interfaz es un secreto que se filtra por una captura de pantalla.
func (q *Queries) GetWebhookKeyState(ctx context.Context, deliveryPlatformID int16) (GetWebhookKeyStateRow, error) {
	row := q.db.QueryRow(ctx, getWebhookKeyState, deliveryPlatformID)
	var i GetWebhookKeyStateRow
	err := row.Scan(&i.Configurada, &i.Rotando, &i.RotatedAt)
	return i, err
}

const insertIncomingOrder = `-- name: InsertIncomingOrder :one

insert into platform_incoming_orders (
  connection_id, external_order_id, display_id, placed_at, decide_before,
  service_type, customer_name, total, raw_detail
) values ($1, $2, $3, $4, $5, $6, $7, $8, $9)
on conflict (company_id, connection_id, external_order_id) do nothing
returning id
`

type InsertIncomingOrderParams struct {
	ConnectionID    int64              `json:"connection_id"`
	ExternalOrderID string             `json:"external_order_id"`
	DisplayID       *string            `json:"display_id"`
	PlacedAt        pgtype.Timestamptz `json:"placed_at"`
	DecideBefore    pgtype.Timestamptz `json:"decide_before"`
	ServiceType     ServiceType        `json:"service_type"`
	CustomerName    *string            `json:"customer_name"`
	Total           *decimal.Decimal   `json:"total"`
	RawDetail       *string            `json:"raw_detail"`
}

// ---------------------------------------------------------------------------------------------
// Los pedidos que esperan decisión
// ---------------------------------------------------------------------------------------------
func (q *Queries) InsertIncomingOrder(ctx context.Context, arg InsertIncomingOrderParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertIncomingOrder,
		arg.ConnectionID,
		arg.ExternalOrderID,
		arg.DisplayID,
		arg.PlacedAt,
		arg.DecideBefore,
		arg.ServiceType,
		arg.CustomerName,
		arg.Total,
		arg.RawDetail,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertIncomingOrderLine = `-- name: InsertIncomingOrderLine :one
insert into platform_incoming_order_lines (
  incoming_order_id, parent_line_id, external_item_id, external_name,
  quantity, unit_price, product_id
) values ($1, $2, $3, $4, $5, $6, $7)
returning id
`

type InsertIncomingOrderLineParams struct {
	IncomingOrderID int64           `json:"incoming_order_id"`
	ParentLineID    *int64          `json:"parent_line_id"`
	ExternalItemID  string          `json:"external_item_id"`
	ExternalName    string          `json:"external_name"`
	Quantity        decimal.Decimal `json:"quantity"`
	UnitPrice       decimal.Decimal `json:"unit_price"`
	ProductID       *int64          `json:"product_id"`
}

func (q *Queries) InsertIncomingOrderLine(ctx context.Context, arg InsertIncomingOrderLineParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertIncomingOrderLine,
		arg.IncomingOrderID,
		arg.ParentLineID,
		arg.ExternalItemID,
		arg.ExternalName,
		arg.Quantity,
		arg.UnitPrice,
		arg.ProductID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertWebhookEvent = `-- name: InsertWebhookEvent :one

insert into platform_webhook_events (event_id, event_type, connection_id, raw_body)
values ($1, $2, $3, $4)
on conflict (company_id, event_id) do nothing
returning id
`

type InsertWebhookEventParams struct {
	EventID      string  `json:"event_id"`
	EventType    string  `json:"event_type"`
	ConnectionID int64   `json:"connection_id"`
	RawBody      *string `json:"raw_body"`
}

// ---------------------------------------------------------------------------------------------
// Los avisos que llegaron
// ---------------------------------------------------------------------------------------------
// Se escribe ANTES de llamar a la plataforma por el detalle, en su propia transacción: si el
// proceso se muere a media llamada, el aviso ya está en disco y el reintento lo encuentra.
// El arbitrio va por (company_id, event_id) porque el único es por empresa: la fila de OTRA
// empresa es invisible bajo RLS, y arbitrar por `event_id` solo hacía que el insert no devolviera
// nada, el servicio lo leyera como «ya procesado» y el pedido se perdiera con un 200.
func (q *Queries) InsertWebhookEvent(ctx context.Context, arg InsertWebhookEventParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertWebhookEvent,
		arg.EventID,
		arg.EventType,
		arg.ConnectionID,
		arg.RawBody,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listLinesOfIncomingOrders = `-- name: ListLinesOfIncomingOrders :many
select id, incoming_order_id, parent_line_id, external_item_id, external_name,
       quantity, unit_price, product_id
  from platform_incoming_order_lines
 where incoming_order_id = any($1::bigint[])
 order by incoming_order_id, parent_line_id nulls first, id
`

type ListLinesOfIncomingOrdersRow struct {
	ID              int64           `json:"id"`
	IncomingOrderID int64           `json:"incoming_order_id"`
	ParentLineID    *int64          `json:"parent_line_id"`
	ExternalItemID  string          `json:"external_item_id"`
	ExternalName    string          `json:"external_name"`
	Quantity        decimal.Decimal `json:"quantity"`
	UnitPrice       decimal.Decimal `json:"unit_price"`
	ProductID       *int64          `json:"product_id"`
}

// Los renglones de varios pedidos de un golpe. Uno por pedido sería N+1 sobre la consulta que la
// tableta repite cada pocos segundos.
func (q *Queries) ListLinesOfIncomingOrders(ctx context.Context, ids []int64) ([]ListLinesOfIncomingOrdersRow, error) {
	rows, err := q.db.Query(ctx, listLinesOfIncomingOrders, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListLinesOfIncomingOrdersRow{}
	for rows.Next() {
		var i ListLinesOfIncomingOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.IncomingOrderID,
			&i.ParentLineID,
			&i.ExternalItemID,
			&i.ExternalName,
			&i.Quantity,
			&i.UnitPrice,
			&i.ProductID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOrphanPlatformOrders = `-- name: ListOrphanPlatformOrders :many
select id
  from orders
 where register_session_id is null
   and delivery_platform_id is not null
   and business_date = $1
 order by opened_at
`

// Los pedidos de plataforma que se aceptaron SIN turno abierto y que le tocan al turno que se abre.
//
// Solo los del MISMO día de operación: un pedido de hace tres días aparecería como ingreso de hoy.
//
// SE LISTAN PARA RENUMERARLOS, no para un update en bloque, y ésa es la parte que no era obvia:
// `orders_folio_turno_key` es único por (company_id, register_session_id, daily_number). Mientras
// el pedido no tiene turno, su `daily_number` es 0 y no choca con nada porque Postgres trata los
// NULL de `register_session_id` como distintos entre sí. En el momento en que se le asigna el
// turno, ese 0 entra a competir con los folios reales de ese turno — y si hay dos pedidos
// huérfanos, chocan entre ellos. Por eso cada uno toma su número del contador del turno.
func (q *Queries) ListOrphanPlatformOrders(ctx context.Context, businessDate pgtype.Date) ([]int64, error) {
	rows, err := q.db.Query(ctx, listOrphanPlatformOrders, businessDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []int64{}
	for rows.Next() {
		var id int64
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingIncomingOrders = `-- name: ListPendingIncomingOrders :many
select o.id, o.connection_id, p.name as platform_name, o.external_order_id, o.display_id,
       o.placed_at, o.decide_before, o.service_type, o.customer_name, o.total
  from platform_incoming_orders o
  join platform_connections c on c.id = o.connection_id
  join delivery_platforms p on p.id = c.delivery_platform_id
 where o.state = 'pendiente'
 order by o.decide_before
`

type ListPendingIncomingOrdersRow struct {
	ID              int64              `json:"id"`
	ConnectionID    int64              `json:"connection_id"`
	PlatformName    string             `json:"platform_name"`
	ExternalOrderID string             `json:"external_order_id"`
	DisplayID       *string            `json:"display_id"`
	PlacedAt        pgtype.Timestamptz `json:"placed_at"`
	DecideBefore    pgtype.Timestamptz `json:"decide_before"`
	ServiceType     ServiceType        `json:"service_type"`
	CustomerName    *string            `json:"customer_name"`
	Total           *decimal.Decimal   `json:"total"`
}

// Lo que pinta el aviso de la tableta. Ordenado por urgencia: el más cerca de expirar primero, que
// es el único orden que le sirve a quien tiene que decidir.
func (q *Queries) ListPendingIncomingOrders(ctx context.Context) ([]ListPendingIncomingOrdersRow, error) {
	rows, err := q.db.Query(ctx, listPendingIncomingOrders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPendingIncomingOrdersRow{}
	for rows.Next() {
		var i ListPendingIncomingOrdersRow
		if err := rows.Scan(
			&i.ID,
			&i.ConnectionID,
			&i.PlatformName,
			&i.ExternalOrderID,
			&i.DisplayID,
			&i.PlacedAt,
			&i.DecideBefore,
			&i.ServiceType,
			&i.CustomerName,
			&i.Total,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const llaveDeFirmaDeLaConexion = `-- name: LlaveDeFirmaDeLaConexion :one
select k.key_primary, k.key_secondary
  from platform_connections c
  join platform_webhook_keys k
    on k.delivery_platform_id = c.delivery_platform_id
 where c.id = $1
`

type LlaveDeFirmaDeLaConexionRow struct {
	KeyPrimary   string  `json:"key_primary"`
	KeySecondary *string `json:"key_secondary"`
}

// La llave con la que se verifica un aviso de ESTA empresa. Corre con el tenant ya fijado, o sea
// bajo RLS: es lo que mantiene el secreto dentro del aislamiento.
func (q *Queries) LlaveDeFirmaDeLaConexion(ctx context.Context, id int64) (LlaveDeFirmaDeLaConexionRow, error) {
	row := q.db.QueryRow(ctx, llaveDeFirmaDeLaConexion, id)
	var i LlaveDeFirmaDeLaConexionRow
	err := row.Scan(&i.KeyPrimary, &i.KeySecondary)
	return i, err
}

const markWebhookEventDone = `-- name: MarkWebhookEventDone :exec
update platform_webhook_events
   set processed_at = now(), outcome = $2, failure_kind = $3
 where id = $1
`

type MarkWebhookEventDoneParams struct {
	ID          int64   `json:"id"`
	Outcome     *string `json:"outcome"`
	FailureKind *string `json:"failure_kind"`
}

func (q *Queries) MarkWebhookEventDone(ctx context.Context, arg MarkWebhookEventDoneParams) error {
	_, err := q.db.Exec(ctx, markWebhookEventDone, arg.ID, arg.Outcome, arg.FailureKind)
	return err
}

const rotateWebhookKey = `-- name: RotateWebhookKey :execrows
update platform_webhook_keys
   set key_secondary = key_primary, key_primary = $2, rotated_at = now()
 where delivery_platform_id = $1
`

type RotateWebhookKeyParams struct {
	DeliveryPlatformID int16  `json:"delivery_platform_id"`
	KeyPrimary         string `json:"key_primary"`
}

// Empieza una rotación: la llave que estaba pasa a secundaria y entra la nueva como primaria.
// Durante la rotación las DOS validan, que es el punto: cambiarla sin dejar de recibir pedidos.
func (q *Queries) RotateWebhookKey(ctx context.Context, arg RotateWebhookKeyParams) (int64, error) {
	result, err := q.db.Exec(ctx, rotateWebhookKey, arg.DeliveryPlatformID, arg.KeyPrimary)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const seedPlatformPaymentMethods = `-- name: SeedPlatformPaymentMethods :exec
insert into payment_methods (company_id, name, kind, delivery_platform_id, is_cash,
                             affects_cash_drawer, is_active, sort_key, auto_declare)
values
  ($1, $3::text,  'plataforma', $2, false, false, true, 400, false),
  ($1, $4::text, 'plataforma', $2, true,  true,  true, 410, false)
on conflict (company_id, name) do nothing
`

type SeedPlatformPaymentMethodsParams struct {
	CompanyID          int64  `json:"company_id"`
	DeliveryPlatformID *int16 `json:"delivery_platform_id"`
	NombreEnLinea      string `json:"nombre_en_linea"`
	NombreEfectivo     string `json:"nombre_efectivo"`
}

// Los dos métodos de cobro de una plataforma, al CONECTAR la tienda.
//
// `SeedBasePaymentMethods` los deja fuera a propósito y con razón: «vender por Uber exige que ese
// negocio haya hecho su propia vinculación con la plataforma, y darle formas de cobro que no tiene
// contratadas es peor que no darle ninguna». Conectar la tienda ES esa vinculación — es el momento
// exacto que ese comentario nombra.
//
// Sin esto, aceptar el primer pedido falla con «falta el método de pago», y el operador no tiene
// desde dónde arreglarlo: los métodos de plataforma no se crean desde ninguna pantalla.
//
// Dos y no uno: un pedido pagado en la aplicación NO es lo mismo que uno contra entrega, y meterlos
// en el mismo cajón hace que el corte pida efectivo que nadie recibió. `is_cash` y
// `affects_cash_drawer` solo en el de efectivo, que es lo que el check de la 0067 exige.
func (q *Queries) SeedPlatformPaymentMethods(ctx context.Context, arg SeedPlatformPaymentMethodsParams) error {
	_, err := q.db.Exec(ctx, seedPlatformPaymentMethods,
		arg.CompanyID,
		arg.DeliveryPlatformID,
		arg.NombreEnLinea,
		arg.NombreEfectivo,
	)
	return err
}

const upsertWebhookKey = `-- name: UpsertWebhookKey :exec


insert into platform_webhook_keys (delivery_platform_id, key_primary)
values ($1, $2)
on conflict (company_id, delivery_platform_id) do update
   set key_primary = excluded.key_primary, key_secondary = null, rotated_at = null
`

type UpsertWebhookKeyParams struct {
	DeliveryPlatformID int16  `json:"delivery_platform_id"`
	KeyPrimary         string `json:"key_primary"`
}

// Recibir los pedidos de las plataformas (spec 021).
//
// Casi todo va bajo RLS y ninguna consulta filtra por company_id: la política tenant_isolation ya
// lo hace. LA EXCEPCIÓN es ResolverTiendaDeAviso, que corre SIN empresa fijada a propósito — está
// marcada y explicada abajo, y es la única de todo el repositorio que puede hacerlo.
// ---------------------------------------------------------------------------------------------
// Las llaves con las que se verifica la firma
// ---------------------------------------------------------------------------------------------
// Capturar o reemplazar la llave primaria. `rotated_at` se limpia: poner una primaria nueva cierra
// cualquier rotación a medias que hubiera quedado abierta.
func (q *Queries) UpsertWebhookKey(ctx context.Context, arg UpsertWebhookKeyParams) error {
	_, err := q.db.Exec(ctx, upsertWebhookKey, arg.DeliveryPlatformID, arg.KeyPrimary)
	return err
}
