// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: platform_prices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countProductPlatformPrices = `-- name: CountProductPlatformPrices :one
select count(*) from product_platform_prices
`

// Para los tests de aislamiento: cuenta lo que la empresa activa alcanza a ver.
func (q *Queries) CountProductPlatformPrices(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countProductPlatformPrices)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteOptionPlatformPrice = `-- name: DeleteOptionPlatformPrice :execrows
delete from modifier_option_platform_prices where option_id = $1 and platform_id = $2
`

type DeleteOptionPlatformPriceParams struct {
	OptionID   int64 `json:"option_id"`
	PlatformID int16 `json:"platform_id"`
}

func (q *Queries) DeleteOptionPlatformPrice(ctx context.Context, arg DeleteOptionPlatformPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOptionPlatformPrice, arg.OptionID, arg.PlatformID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteProductPlatformPrice = `-- name: DeleteProductPlatformPrice :execrows
delete from product_platform_prices where product_id = $1 and platform_id = $2
`

type DeleteProductPlatformPriceParams struct {
	ProductID  int64 `json:"product_id"`
	PlatformID int16 `json:"platform_id"`
}

// :execrows y no :exec para distinguir "se borró" de "no había nada". El handler invalida el menú
// cacheado y publica menu.updated, que hace refetch a todas las tablets; sin el conteo, peticiones
// que no cambian nada provocan esa tormenta en bucle.
func (q *Queries) DeleteProductPlatformPrice(ctx context.Context, arg DeleteProductPlatformPriceParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteProductPlatformPrice, arg.ProductID, arg.PlatformID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getOptionPlatformPriceSource = `-- name: GetOptionPlatformPriceSource :one
select source from modifier_option_platform_prices where option_id = $1 and platform_id = $2
`

type GetOptionPlatformPriceSourceParams struct {
	OptionID   int64 `json:"option_id"`
	PlatformID int16 `json:"platform_id"`
}

func (q *Queries) GetOptionPlatformPriceSource(ctx context.Context, arg GetOptionPlatformPriceSourceParams) (string, error) {
	row := q.db.QueryRow(ctx, getOptionPlatformPriceSource, arg.OptionID, arg.PlatformID)
	var source string
	err := row.Scan(&source)
	return source, err
}

const getOptionPlatformPrices = `-- name: GetOptionPlatformPrices :many
select option_id, price_delta, synced_at from modifier_option_platform_prices where platform_id = $1
`

type GetOptionPlatformPricesRow struct {
	OptionID   int64              `json:"option_id"`
	PriceDelta decimal.Decimal    `json:"price_delta"`
	SyncedAt   pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) GetOptionPlatformPrices(ctx context.Context, platformID int16) ([]GetOptionPlatformPricesRow, error) {
	rows, err := q.db.Query(ctx, getOptionPlatformPrices, platformID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetOptionPlatformPricesRow{}
	for rows.Next() {
		var i GetOptionPlatformPricesRow
		if err := rows.Scan(&i.OptionID, &i.PriceDelta, &i.SyncedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlatformByID = `-- name: GetPlatformByID :one

select id, name, price_markup_pct, is_active from delivery_platforms where id = $1
`

type GetPlatformByIDRow struct {
	ID             int16           `json:"id"`
	Name           string          `json:"name"`
	PriceMarkupPct decimal.Decimal `json:"price_markup_pct"`
	IsActive       bool            `json:"is_active"`
}

// Precios por plataforma digital (spec 002). Todo bajo RLS: las queries no filtran por company_id
// porque la política tenant_isolation ya lo hace, igual que el resto del repo.
// Resuelve la plataforma de un pedido DENTRO de la empresa. Va por aquí y no por la llave foránea
// de orders: los chequeos de FK de Postgres saltan RLS, así que un id de otra empresa pasaría el
// insert y el pedido se cobraría a precio de mostrador con el ticket bien impreso.
func (q *Queries) GetPlatformByID(ctx context.Context, id int16) (GetPlatformByIDRow, error) {
	row := q.db.QueryRow(ctx, getPlatformByID, id)
	var i GetPlatformByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.PriceMarkupPct,
		&i.IsActive,
	)
	return i, err
}

const getProductPlatformPriceSource = `-- name: GetProductPlatformPriceSource :one
select source from product_platform_prices where product_id = $1 and platform_id = $2
`

type GetProductPlatformPriceSourceParams struct {
	ProductID  int64 `json:"product_id"`
	PlatformID int16 `json:"platform_id"`
}

// Quién puso el precio (0077). El de una plataforma conectada no se captura a mano.
func (q *Queries) GetProductPlatformPriceSource(ctx context.Context, arg GetProductPlatformPriceSourceParams) (string, error) {
	row := q.db.QueryRow(ctx, getProductPlatformPriceSource, arg.ProductID, arg.PlatformID)
	var source string
	err := row.Scan(&source)
	return source, err
}

const getProductPlatformPrices = `-- name: GetProductPlatformPrices :many
select product_id, price, synced_at from product_platform_prices where platform_id = $1
`

type GetProductPlatformPricesRow struct {
	ProductID int64              `json:"product_id"`
	Price     decimal.Decimal    `json:"price"`
	SyncedAt  pgtype.Timestamptz `json:"synced_at"`
}

// Solo las EXCEPCIONES de una plataforma. Un producto ausente usa el precio calculado.
func (q *Queries) GetProductPlatformPrices(ctx context.Context, platformID int16) ([]GetProductPlatformPricesRow, error) {
	rows, err := q.db.Query(ctx, getProductPlatformPrices, platformID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []GetProductPlatformPricesRow{}
	for rows.Next() {
		var i GetProductPlatformPricesRow
		if err := rows.Scan(&i.ProductID, &i.Price, &i.SyncedAt); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOptionPlatformPricesOfPlatform = `-- name: ListOptionPlatformPricesOfPlatform :many
select option_id, price_delta, source from modifier_option_platform_prices where platform_id = $1
`

type ListOptionPlatformPricesOfPlatformRow struct {
	OptionID   int64           `json:"option_id"`
	PriceDelta decimal.Decimal `json:"price_delta"`
	Source     string          `json:"source"`
}

func (q *Queries) ListOptionPlatformPricesOfPlatform(ctx context.Context, platformID int16) ([]ListOptionPlatformPricesOfPlatformRow, error) {
	rows, err := q.db.Query(ctx, listOptionPlatformPricesOfPlatform, platformID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListOptionPlatformPricesOfPlatformRow{}
	for rows.Next() {
		var i ListOptionPlatformPricesOfPlatformRow
		if err := rows.Scan(&i.OptionID, &i.PriceDelta, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPlatformsWithMarkup = `-- name: ListPlatformsWithMarkup :many
select id, name, price_markup_pct from delivery_platforms
where is_active and name <> 'Propio' order by name
`

type ListPlatformsWithMarkupRow struct {
	ID             int16           `json:"id"`
	Name           string          `json:"name"`
	PriceMarkupPct decimal.Decimal `json:"price_markup_pct"`
}

// Las plataformas que el POS ofrece como lista de precios. 'Propio' queda fuera: es reparto del
// propio negocio, sin comisión que absorber ni depósito que conciliar, y no tiene método de pago.
func (q *Queries) ListPlatformsWithMarkup(ctx context.Context) ([]ListPlatformsWithMarkupRow, error) {
	rows, err := q.db.Query(ctx, listPlatformsWithMarkup)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListPlatformsWithMarkupRow{}
	for rows.Next() {
		var i ListPlatformsWithMarkupRow
		if err := rows.Scan(&i.ID, &i.Name, &i.PriceMarkupPct); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProductPlatformPricesOfPlatform = `-- name: ListProductPlatformPricesOfPlatform :many
select product_id, price, source from product_platform_prices where platform_id = $1
`

type ListProductPlatformPricesOfPlatformRow struct {
	ProductID int64           `json:"product_id"`
	Price     decimal.Decimal `json:"price"`
	Source    string          `json:"source"`
}

func (q *Queries) ListProductPlatformPricesOfPlatform(ctx context.Context, platformID int16) ([]ListProductPlatformPricesOfPlatformRow, error) {
	rows, err := q.db.Query(ctx, listProductPlatformPricesOfPlatform, platformID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListProductPlatformPricesOfPlatformRow{}
	for rows.Next() {
		var i ListProductPlatformPricesOfPlatformRow
		if err := rows.Scan(&i.ProductID, &i.Price, &i.Source); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const optionExists = `-- name: OptionExists :one
select exists(select 1 from modifier_options where id = $1)
`

func (q *Queries) OptionExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, optionExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const productExists = `-- name: ProductExists :one
select exists(select 1 from products where id = $1)
`

// Comprobación de PERTENENCIA bajo RLS antes de escribir un precio. La llave foránea no alcanza:
// sus chequeos saltan RLS por diseño, así que un product_id de otra empresa entraba y ocupaba la
// PK global (product_id, platform_id) — dejando al dueño legítimo sin poder capturar ni borrar.
func (q *Queries) ProductExists(ctx context.Context, id int64) (bool, error) {
	row := q.db.QueryRow(ctx, productExists, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const syncOptionPlatformPrice = `-- name: SyncOptionPlatformPrice :exec
insert into modifier_option_platform_prices (option_id, platform_id, price_delta, updated_by, source, synced_at)
values ($1, $2, $3, $4, 'platform', $5)
on conflict (option_id, platform_id)
do update set price_delta = excluded.price_delta, updated_by = excluded.updated_by,
              source = 'platform', synced_at = excluded.synced_at, updated_at = now()
`

type SyncOptionPlatformPriceParams struct {
	OptionID   int64              `json:"option_id"`
	PlatformID int16              `json:"platform_id"`
	PriceDelta decimal.Decimal    `json:"price_delta"`
	UpdatedBy  int64              `json:"updated_by"`
	SyncedAt   pgtype.Timestamptz `json:"synced_at"`
}

func (q *Queries) SyncOptionPlatformPrice(ctx context.Context, arg SyncOptionPlatformPriceParams) error {
	_, err := q.db.Exec(ctx, syncOptionPlatformPrice,
		arg.OptionID,
		arg.PlatformID,
		arg.PriceDelta,
		arg.UpdatedBy,
		arg.SyncedAt,
	)
	return err
}

const syncProductPlatformPrice = `-- name: SyncProductPlatformPrice :exec
insert into product_platform_prices (product_id, platform_id, price, updated_by, source, synced_at)
values ($1, $2, $3, $4, 'platform', $5)
on conflict (product_id, platform_id)
do update set price = excluded.price, updated_by = excluded.updated_by,
              source = 'platform', synced_at = excluded.synced_at, updated_at = now()
`

type SyncProductPlatformPriceParams struct {
	ProductID  int64              `json:"product_id"`
	PlatformID int16              `json:"platform_id"`
	Price      decimal.Decimal    `json:"price"`
	UpdatedBy  int64              `json:"updated_by"`
	SyncedAt   pgtype.Timestamptz `json:"synced_at"`
}

// Lo escribe la lectura del menú, no una persona: `source = platform` bloquea la captura a mano.
func (q *Queries) SyncProductPlatformPrice(ctx context.Context, arg SyncProductPlatformPriceParams) error {
	_, err := q.db.Exec(ctx, syncProductPlatformPrice,
		arg.ProductID,
		arg.PlatformID,
		arg.Price,
		arg.UpdatedBy,
		arg.SyncedAt,
	)
	return err
}

const upsertOptionPlatformPrice = `-- name: UpsertOptionPlatformPrice :exec
insert into modifier_option_platform_prices (option_id, platform_id, price_delta, updated_by)
values ($1, $2, $3, $4)
on conflict (option_id, platform_id)
do update set price_delta = excluded.price_delta, updated_by = excluded.updated_by
`

type UpsertOptionPlatformPriceParams struct {
	OptionID   int64           `json:"option_id"`
	PlatformID int16           `json:"platform_id"`
	PriceDelta decimal.Decimal `json:"price_delta"`
	UpdatedBy  int64           `json:"updated_by"`
}

func (q *Queries) UpsertOptionPlatformPrice(ctx context.Context, arg UpsertOptionPlatformPriceParams) error {
	_, err := q.db.Exec(ctx, upsertOptionPlatformPrice,
		arg.OptionID,
		arg.PlatformID,
		arg.PriceDelta,
		arg.UpdatedBy,
	)
	return err
}

const upsertProductPlatformPrice = `-- name: UpsertProductPlatformPrice :exec
insert into product_platform_prices (product_id, platform_id, price, updated_by)
values ($1, $2, $3, $4)
on conflict (product_id, platform_id)
do update set price = excluded.price, updated_by = excluded.updated_by
`

type UpsertProductPlatformPriceParams struct {
	ProductID  int64           `json:"product_id"`
	PlatformID int16           `json:"platform_id"`
	Price      decimal.Decimal `json:"price"`
	UpdatedBy  int64           `json:"updated_by"`
}

func (q *Queries) UpsertProductPlatformPrice(ctx context.Context, arg UpsertProductPlatformPriceParams) error {
	_, err := q.db.Exec(ctx, upsertProductPlatformPrice,
		arg.ProductID,
		arg.PlatformID,
		arg.Price,
		arg.UpdatedBy,
	)
	return err
}
