// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const productMargins = `-- name: ProductMargins :many
select ol.product_name,
       sum(ol.quantity)::numeric(12,2) as qty,
       coalesce(sum(ol.line_total * (o.total - o.delivery_fee) / nullif(o.subtotal, 0)), 0)::numeric(12,2) as revenue,
       coalesce(sum(ol.unit_cost * ol.quantity), 0)::numeric(12,2) as cost,
       (coalesce(sum(ol.line_total * (o.total - o.delivery_fee) / nullif(o.subtotal, 0)) filter (where ol.unit_cost > 0), 0)
        - coalesce(sum(ol.unit_cost * ol.quantity), 0))::numeric(12,2) as margin,
       coalesce(sum(ol.line_total * (o.total - o.delivery_fee) / nullif(o.subtotal, 0)) filter (where ol.unit_cost = 0), 0)::numeric(12,2) as uncosted_revenue
from order_lines ol
join orders o on o.id = ol.order_id
where o.status not in ('cancelada', 'reembolsada')
  and ol.cancelled_at is null
  and o.business_date between $1 and $2
group by ol.product_name
order by margin desc
limit $3
`

type ProductMarginsParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
	Limit          int32       `json:"limit"`
}

type ProductMarginsRow struct {
	ProductName     string          `json:"product_name"`
	Qty             decimal.Decimal `json:"qty"`
	Revenue         decimal.Decimal `json:"revenue"`
	Cost            decimal.Decimal `json:"cost"`
	Margin          decimal.Decimal `json:"margin"`
	UncostedRevenue decimal.Decimal `json:"uncosted_revenue"`
}

// Utilidad por producto usando snapshots de las líneas (no depende del costo actual).
//
// Acotada por DÍA DE NEGOCIO y en los dos extremos, igual que sus hermanas de pantalla. Filtraba
// por `o.opened_at >= $1` sin cota superior: con un filtro de fechas encima, esta tabla habría
// seguido contestando "desde esa fecha hasta hoy" mientras el resto de la pantalla contestaba el
// rango elegido. Y `opened_at` es un instante en UTC, no el día con el que el negocio cuadra su
// caja: un pedido abierto a las 19:00 de México ya es del día siguiente en UTC.
//
// Spec 031 (D10): sin los renglones QUITADOS —no se vendieron, y ProductsSold y el total del pedido
// ya los excluían— y con el descuento del pedido repartido entre sus renglones en proporción a su
// importe. Así el ingreso por producto suma lo vendido menos envíos, que no es de ningún producto.
//
// Spec 029: lo vendido SIN COSTO CAPTURADO (`unit_cost = 0`) va en `uncosted_revenue` y no suma al
// margen. Restarle un costo de cero mostraba como margen la venta entera, y el producto sin costo
// parecía el más rentable de la carta. `unit_cost = 0` no distingue «gratis» de «sin capturar»: es
// un hecho ya guardado así, y lo honesto es decir que no hay costo, no inventar un margen.
// Misma expresión prorrateada que `revenue`, para que las dos cifras se puedan comparar.
func (q *Queries) ProductMargins(ctx context.Context, arg ProductMarginsParams) ([]ProductMarginsRow, error) {
	rows, err := q.db.Query(ctx, productMargins, arg.BusinessDate, arg.BusinessDate_2, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductMarginsRow{}
	for rows.Next() {
		var i ProductMarginsRow
		if err := rows.Scan(
			&i.ProductName,
			&i.Qty,
			&i.Revenue,
			&i.Cost,
			&i.Margin,
			&i.UncostedRevenue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const productsSold = `-- name: ProductsSold :many
with vivos as (
  select o.id, o.total, o.business_date
    from orders o
   where o.merged_into_order_id is null
     and (o.status not in ('cancelada', 'reembolsada')
          or exists (select 1 from order_refunds r where r.order_id = o.id))
), acumulado as (
  select op.order_id, coalesce(op.business_date, v.business_date) as dia, v.total,
         sum(op.amount) over (partition by op.order_id order by op.created_at, op.id) as cobrado
    from order_payments op
    join vivos v on v.id = op.order_id
), saldado as (
  select v.id as order_id,
         case when v.total <= 0 then v.business_date
              else (select min(a.dia) from acumulado a where a.order_id = v.id and a.cobrado >= a.total)
         end as dia
    from vivos v
), devuelto_acumulado as (
  select r.order_id, coalesce(r.business_date, o.business_date) as dia, o.total,
         sum(r.amount) over (partition by r.order_id order by r.created_at, r.id) as devuelto
    from order_refunds r join orders o on o.id = r.order_id
), devuelto_pedido as (
  select da.order_id, min(da.dia) as dia from devuelto_acumulado da where da.devuelto >= da.total group by da.order_id
), renglon_acumulado as (
  select r.order_line_id, coalesce(r.business_date, o.business_date) as dia, ol.line_total,
         sum(r.amount) over (partition by r.order_line_id order by r.created_at, r.id) as devuelto
    from order_refunds r
    join order_lines ol on ol.id = r.order_line_id
    join orders o on o.id = r.order_id
), devuelto_renglon as (
  select ra.order_line_id, min(ra.dia) as dia from renglon_acumulado ra where ra.devuelto >= ra.line_total group by ra.order_line_id
), renglones as (
  -- Un renglón por fila con sus dos días: el de la venta y, si se devolvió, el de la devolución.
  -- Dos columnas y no un ` + "`" + `union all` + "`" + ` de movimientos: sqlc no resuelve las columnas de esa forma, y
  -- los parámetros llevan ` + "`" + `::date` + "`" + ` porque no infiere su tipo de una columna de CTE.
  select ol.id as line_id, ol.product_id, ol.quantity, s.dia as vendido,
         coalesce(case when dr.dia < dp.dia then dr.dia else dp.dia end, dr.dia, dp.dia) as regresado
    from order_lines ol
    join saldado s on s.order_id = ol.order_id
    left join devuelto_renglon dr on dr.order_line_id = ol.id
    left join devuelto_pedido dp on dp.order_id = ol.order_id
   where ol.cancelled_at is null and s.dia is not null
), alone as (
  select rg.product_id,
         sum(case when rg.vendido between $2::date and $3::date then rg.quantity else 0 end)
         - sum(case when rg.regresado between $2::date and $3::date then rg.quantity else 0 end) as qty
    from renglones rg
   where rg.product_id is not null
     and (rg.vendido between $2::date and $3::date
          or rg.regresado between $2::date and $3::date)
   group by rg.product_id
), packed as (
  select c.product_id,
         sum(case when rg.vendido between $2::date and $3::date then c.quantity else 0 end)
         - sum(case when rg.regresado between $2::date and $3::date then c.quantity else 0 end) as qty
    from renglones rg
    join order_line_components c on c.order_line_id = rg.line_id
   where rg.vendido between $2::date and $3::date
      or rg.regresado between $2::date and $3::date
   group by c.product_id
)
select p.name as product_name,
       coalesce(a.qty, 0)::numeric(14,2) as alone,
       coalesce(k.qty, 0)::numeric(14,2) as in_packages
  from products p
  left join alone a on a.product_id = p.id
  left join packed k on k.product_id = p.id
 where (a.qty is not null or k.qty is not null) and p.type <> 'combo'
 order by coalesce(a.qty, 0) + coalesce(k.qty, 0) desc, p.name
 limit $1
`

type ProductsSoldParams struct {
	RowLimit int32       `json:"row_limit"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

type ProductsSoldRow struct {
	ProductName string          `json:"product_name"`
	Alone       decimal.Decimal `json:"alone"`
	InPackages  decimal.Decimal `json:"in_packages"`
}

// Unidades vendidas por producto, sueltas y dentro de paquetes (spec 028). Los componentes salen de
// la copia hecha al vender (order_line_components), no del paquete de hoy.
//
// EL DÍA DE UNA VENTA ES EL DÍA EN QUE SU PEDIDO QUEDÓ SALDADO (decisión del dueño, 2026-10-09):
// el del cobro que hizo que lo cobrado cubriera el total al centavo. Un pedido sin saldar —abierto o
// fiado— no ha vendido nada. Un renglón DEVUELTO resta sus piezas el día en que se devolvió: el día
// en que sus devoluciones cubren su importe, o el día en que las del pedido cubren el total (lo que
// pase primero; el que no es nulo si solo hay uno). Una devolución parcial de dinero no resta piezas: el
// producto se entregó y lo que se regresó fue una compensación. El dinero sigue contando por el
// día de cada cobro y cada devolución (SalesByMethod); esto es solo el conteo de piezas.
//
// Cancelado sin devoluciones (flujo viejo) queda fuera, igual que en SalesByMethod. Un pedido de
// total cero se da por saldado el día de su negocio: no hay cobro que lo marque.
//
// Cada rama se agrega por producto antes de unir: unir renglones y componentes en la misma consulta
// multiplicaría las filas (AGENTS.md §1).
func (q *Queries) ProductsSold(ctx context.Context, arg ProductsSoldParams) ([]ProductsSoldRow, error) {
	rows, err := q.db.Query(ctx, productsSold, arg.RowLimit, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductsSoldRow{}
	for rows.Next() {
		var i ProductsSoldRow
		if err := rows.Scan(&i.ProductName, &i.Alone, &i.InPackages); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundsByDay = `-- name: RefundsByDay :many
select o.business_date,
       count(*)::int as refunds,
       coalesce(sum(o.refund_amount), 0)::numeric(12,2) as amount
from orders o
where o.status = 'reembolsada' and o.business_date between $1 and $2
group by o.business_date
order by o.business_date
`

type RefundsByDayParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type RefundsByDayRow struct {
	BusinessDate pgtype.Date     `json:"business_date"`
	Refunds      int32           `json:"refunds"`
	Amount       decimal.Decimal `json:"amount"`
}

// Pérdidas por devolución: órdenes entregadas que se reembolsaron (no cuentan como ingreso
// en SalesByDay/ProductMargins; aquí se ven como la pérdida que son).
func (q *Queries) RefundsByDay(ctx context.Context, arg RefundsByDayParams) ([]RefundsByDayRow, error) {
	rows, err := q.db.Query(ctx, refundsByDay, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefundsByDayRow{}
	for rows.Next() {
		var i RefundsByDayRow
		if err := rows.Scan(&i.BusinessDate, &i.Refunds, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByDay = `-- name: SalesByDay :many
select o.business_date,
       count(*)::int as orders,
       coalesce(sum(o.total), 0)::numeric(12,2) as revenue
from orders o
where o.status not in ('cancelada', 'reembolsada') and o.business_date between $1 and $2
group by o.business_date
order by o.business_date
`

type SalesByDayParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type SalesByDayRow struct {
	BusinessDate pgtype.Date     `json:"business_date"`
	Orders       int32           `json:"orders"`
	Revenue      decimal.Decimal `json:"revenue"`
}

func (q *Queries) SalesByDay(ctx context.Context, arg SalesByDayParams) ([]SalesByDayRow, error) {
	rows, err := q.db.Query(ctx, salesByDay, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByDayRow{}
	for rows.Next() {
		var i SalesByDayRow
		if err := rows.Scan(&i.BusinessDate, &i.Orders, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByMethod = `-- name: SalesByMethod :many
with pagos as (
  select op.payment_method_id, count(*) as payments, sum(op.amount) as cobrado
    from order_payments op
    join orders o on o.id = op.order_id
   where (op.business_date between $1 and $2
          or (op.business_date is null and o.business_date between $1 and $2))
     and (o.status not in ('cancelada', 'reembolsada')
          or exists (select 1 from order_refunds r where r.order_id = o.id))
   group by op.payment_method_id
), devueltos as (
  select r.payment_method_id, sum(r.amount) as devuelto
    from order_refunds r
    join orders o on o.id = r.order_id
   where coalesce(r.business_date, o.business_date) between $1 and $2
   group by r.payment_method_id
)
select pm.name as method,
       coalesce(p.payments, 0)::int as payments,
       (coalesce(p.cobrado, 0) - coalesce(d.devuelto, 0))::numeric(12,2) as total,
       coalesce(d.devuelto, 0)::numeric(12,2) as refunds
from payment_methods pm
left join pagos p on p.payment_method_id = pm.id
left join devueltos d on d.payment_method_id = pm.id
where p.payment_method_id is not null or d.payment_method_id is not null
order by total desc
`

type SalesByMethodParams struct {
	Desde pgtype.Date `json:"desde"`
	Hasta pgtype.Date `json:"hasta"`
}

type SalesByMethodRow struct {
	Method   string          `json:"method"`
	Payments int32           `json:"payments"`
	Total    decimal.Decimal `json:"total"`
	Refunds  decimal.Decimal `json:"refunds"`
}

// Cobros por medio de pago: lo que ENTRÓ cada día menos lo que se DEVOLVIÓ cada día (spec 031).
//
// El dueño decidió que el dinero se clasifica por la hora de CADA movimiento: un cobro cuenta el día
// en que se cobró y una devolución el día en que se devolvió. Antes los dos tomaban el día del
// PEDIDO, así que un fiado cobrado días después aparecía en un día ya cerrado —mientras el corte de
// caja lo esperaba hoy— y una devolución del mes siguiente borraba el cobro del mes en que entró.
// Esto ya no es la venta del día (SalesByDay): es el dinero, y por eso puede diferir de ella.
//
// Qué pedidos cuentan: los no cancelados ni reembolsados, más los cancelados que tienen su
// devolución en el libro (su cobro cuenta en su día y su devolución resta en el suyo). Un cancelado
// SIN libro es anterior a 0060 —cancelar no miraba los cobros— o un reembolsado por el flujo viejo,
// que no escribía el libro: contarlos inflaría periodos cerrados con dinero que sí se regresó.
//
// Cobros y devoluciones se agregan por método cada uno antes de unirse —son dos 1:N del pedido— y
// se unen por el método, para que uno que solo tuvo devoluciones en el periodo también salga.
//
// El predicado del día va partido para usar `order_payments_company_day`: el `or` cubre solo los
// pagos que un binario anterior pudiera dejar sin día.
func (q *Queries) SalesByMethod(ctx context.Context, arg SalesByMethodParams) ([]SalesByMethodRow, error) {
	rows, err := q.db.Query(ctx, salesByMethod, arg.Desde, arg.Hasta)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByMethodRow{}
	for rows.Next() {
		var i SalesByMethodRow
		if err := rows.Scan(
			&i.Method,
			&i.Payments,
			&i.Total,
			&i.Refunds,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tipsByDay = `-- name: TipsByDay :many
select o.business_date,
       coalesce(sum(op.tip_amount), 0)::numeric(12,2) as tips
from order_payments op
join orders o on o.id = op.order_id
where o.status not in ('cancelada', 'reembolsada')
  and op.tip_amount > 0
  and o.business_date between $1 and $2
group by o.business_date
order by o.business_date
`

type TipsByDayParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type TipsByDayRow struct {
	BusinessDate pgtype.Date     `json:"business_date"`
	Tips         decimal.Decimal `json:"tips"`
}

func (q *Queries) TipsByDay(ctx context.Context, arg TipsByDayParams) ([]TipsByDayRow, error) {
	rows, err := q.db.Query(ctx, tipsByDay, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TipsByDayRow{}
	for rows.Next() {
		var i TipsByDayRow
		if err := rows.Scan(&i.BusinessDate, &i.Tips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tipsByEmployee = `-- name: TipsByEmployee :many
select coalesce(u.name, 'Sin asignar') as employee,
       count(*)::int as payments,
       coalesce(sum(op.tip_amount), 0)::numeric(12,2) as tips
from order_payments op
join orders o on o.id = op.order_id
left join users u on u.id = op.received_by
where o.status not in ('cancelada', 'reembolsada')
  and op.tip_amount > 0
  and o.business_date between $1 and $2
group by u.id, u.name
order by tips desc
`

type TipsByEmployeeParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type TipsByEmployeeRow struct {
	Employee string          `json:"employee"`
	Payments int32           `json:"payments"`
	Tips     decimal.Decimal `json:"tips"`
}

// Propinas por empleado que cobró (received_by), para repartirlas. "Sin asignar" = pago sin cajero.
// Propinas son pass-through (del personal), no ingreso del negocio; este reporte es para reparto.
//
// Agrupa por u.id y NO por u.name. Con el nombre, dos empleados que se llamen igual salían en un
// solo renglón con la suma de los dos, y un renglón así no se puede repartir: quien lo lee no sabe
// cuánto le toca a cada quien. Es el único reporte que existe para entregar dinero a una persona.
func (q *Queries) TipsByEmployee(ctx context.Context, arg TipsByEmployeeParams) ([]TipsByEmployeeRow, error) {
	rows, err := q.db.Query(ctx, tipsByEmployee, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TipsByEmployeeRow{}
	for rows.Next() {
		var i TipsByEmployeeRow
		if err := rows.Scan(&i.Employee, &i.Payments, &i.Tips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
