// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reports.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const productMargins = `-- name: ProductMargins :many
select ol.product_name,
       sum(ol.quantity)::numeric(12,2) as qty,
       coalesce(sum(ol.line_total), 0)::numeric(12,2) as revenue,
       coalesce(sum(ol.unit_cost * ol.quantity), 0)::numeric(12,2) as cost,
       coalesce(sum(ol.line_total) - sum(ol.unit_cost * ol.quantity), 0)::numeric(12,2) as margin
from order_lines ol
join orders o on o.id = ol.order_id
where o.status not in ('cancelada', 'reembolsada') and o.opened_at >= $1
group by ol.product_name
order by margin desc
limit $2
`

type ProductMarginsParams struct {
	OpenedAt time.Time `json:"opened_at"`
	Limit    int32     `json:"limit"`
}

type ProductMarginsRow struct {
	ProductName string          `json:"product_name"`
	Qty         decimal.Decimal `json:"qty"`
	Revenue     decimal.Decimal `json:"revenue"`
	Cost        decimal.Decimal `json:"cost"`
	Margin      decimal.Decimal `json:"margin"`
}

// Utilidad por producto usando snapshots de las líneas (no depende del costo actual).
func (q *Queries) ProductMargins(ctx context.Context, arg ProductMarginsParams) ([]ProductMarginsRow, error) {
	rows, err := q.db.Query(ctx, productMargins, arg.OpenedAt, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProductMarginsRow{}
	for rows.Next() {
		var i ProductMarginsRow
		if err := rows.Scan(
			&i.ProductName,
			&i.Qty,
			&i.Revenue,
			&i.Cost,
			&i.Margin,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const refundsByDay = `-- name: RefundsByDay :many
select o.business_date,
       count(*)::int as refunds,
       coalesce(sum(o.refund_amount), 0)::numeric(12,2) as amount
from orders o
where o.status = 'reembolsada' and o.business_date between $1 and $2
group by o.business_date
order by o.business_date
`

type RefundsByDayParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type RefundsByDayRow struct {
	BusinessDate pgtype.Date     `json:"business_date"`
	Refunds      int32           `json:"refunds"`
	Amount       decimal.Decimal `json:"amount"`
}

// Pérdidas por devolución: órdenes entregadas que se reembolsaron (no cuentan como ingreso
// en SalesByDay/ProductMargins; aquí se ven como la pérdida que son).
func (q *Queries) RefundsByDay(ctx context.Context, arg RefundsByDayParams) ([]RefundsByDayRow, error) {
	rows, err := q.db.Query(ctx, refundsByDay, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefundsByDayRow{}
	for rows.Next() {
		var i RefundsByDayRow
		if err := rows.Scan(&i.BusinessDate, &i.Refunds, &i.Amount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByDay = `-- name: SalesByDay :many
select o.business_date,
       count(*)::int as orders,
       coalesce(sum(o.total), 0)::numeric(12,2) as revenue
from orders o
where o.status not in ('cancelada', 'reembolsada') and o.business_date between $1 and $2
group by o.business_date
order by o.business_date
`

type SalesByDayParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type SalesByDayRow struct {
	BusinessDate pgtype.Date     `json:"business_date"`
	Orders       int32           `json:"orders"`
	Revenue      decimal.Decimal `json:"revenue"`
}

func (q *Queries) SalesByDay(ctx context.Context, arg SalesByDayParams) ([]SalesByDayRow, error) {
	rows, err := q.db.Query(ctx, salesByDay, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByDayRow{}
	for rows.Next() {
		var i SalesByDayRow
		if err := rows.Scan(&i.BusinessDate, &i.Orders, &i.Revenue); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesByMethod = `-- name: SalesByMethod :many
select pm.name as method,
       count(*)::int as payments,
       coalesce(sum(op.amount), 0)::numeric(12,2) as total
from order_payments op
join payment_methods pm on pm.id = op.payment_method_id
where op.created_at >= $1
group by pm.name
order by total desc
`

type SalesByMethodRow struct {
	Method   string          `json:"method"`
	Payments int32           `json:"payments"`
	Total    decimal.Decimal `json:"total"`
}

func (q *Queries) SalesByMethod(ctx context.Context, createdAt time.Time) ([]SalesByMethodRow, error) {
	rows, err := q.db.Query(ctx, salesByMethod, createdAt)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesByMethodRow{}
	for rows.Next() {
		var i SalesByMethodRow
		if err := rows.Scan(&i.Method, &i.Payments, &i.Total); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tipsByDay = `-- name: TipsByDay :many
select o.business_date,
       coalesce(sum(op.tip_amount), 0)::numeric(12,2) as tips
from order_payments op
join orders o on o.id = op.order_id
where o.status not in ('cancelada', 'reembolsada')
  and op.tip_amount > 0
  and o.business_date between $1 and $2
group by o.business_date
order by o.business_date
`

type TipsByDayParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type TipsByDayRow struct {
	BusinessDate pgtype.Date     `json:"business_date"`
	Tips         decimal.Decimal `json:"tips"`
}

func (q *Queries) TipsByDay(ctx context.Context, arg TipsByDayParams) ([]TipsByDayRow, error) {
	rows, err := q.db.Query(ctx, tipsByDay, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TipsByDayRow{}
	for rows.Next() {
		var i TipsByDayRow
		if err := rows.Scan(&i.BusinessDate, &i.Tips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tipsByEmployee = `-- name: TipsByEmployee :many
select coalesce(u.name, 'Sin asignar') as employee,
       count(*)::int as payments,
       coalesce(sum(op.tip_amount), 0)::numeric(12,2) as tips
from order_payments op
join orders o on o.id = op.order_id
left join users u on u.id = op.received_by
where o.status not in ('cancelada', 'reembolsada')
  and op.tip_amount > 0
  and o.business_date between $1 and $2
group by u.name
order by tips desc
`

type TipsByEmployeeParams struct {
	BusinessDate   pgtype.Date `json:"business_date"`
	BusinessDate_2 pgtype.Date `json:"business_date_2"`
}

type TipsByEmployeeRow struct {
	Employee string          `json:"employee"`
	Payments int32           `json:"payments"`
	Tips     decimal.Decimal `json:"tips"`
}

// Propinas por empleado que cobró (received_by), para repartirlas. "Sin asignar" = pago sin cajero.
// Propinas son pass-through (del personal), no ingreso del negocio; este reporte es para reparto.
func (q *Queries) TipsByEmployee(ctx context.Context, arg TipsByEmployeeParams) ([]TipsByEmployeeRow, error) {
	rows, err := q.db.Query(ctx, tipsByEmployee, arg.BusinessDate, arg.BusinessDate_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TipsByEmployeeRow{}
	for rows.Next() {
		var i TipsByEmployeeRow
		if err := rows.Scan(&i.Employee, &i.Payments, &i.Tips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
