// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: reset.sql

package db

import (
	"context"
	"time"
)

const createPasswordResetToken = `-- name: CreatePasswordResetToken :one

insert into password_reset_tokens (user_id, token_hash, expires_at)
values ($1, $2, $3)
returning id, company_id, user_id, token_hash, expires_at, used_at, created_at
`

type CreatePasswordResetTokenParams struct {
	UserID    int64     `json:"user_id"`
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
}

// Tokens de recuperación de contraseña (ver migración 0025). Todo bajo contexto de tenant.
func (q *Queries) CreatePasswordResetToken(ctx context.Context, arg CreatePasswordResetTokenParams) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, createPasswordResetToken, arg.UserID, arg.TokenHash, arg.ExpiresAt)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const getPasswordResetToken = `-- name: GetPasswordResetToken :one
select id, company_id, user_id, token_hash, expires_at, used_at, created_at from password_reset_tokens where token_hash = $1
`

func (q *Queries) GetPasswordResetToken(ctx context.Context, tokenHash string) (PasswordResetToken, error) {
	row := q.db.QueryRow(ctx, getPasswordResetToken, tokenHash)
	var i PasswordResetToken
	err := row.Scan(
		&i.ID,
		&i.CompanyID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.UsedAt,
		&i.CreatedAt,
	)
	return i, err
}

const invalidateUserResetTokens = `-- name: InvalidateUserResetTokens :exec
update password_reset_tokens set used_at = now() where user_id = $1 and used_at is null
`

// Al fijar la contraseña, invalida cualquier otro token de reset pendiente del usuario.
func (q *Queries) InvalidateUserResetTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, invalidateUserResetTokens, userID)
	return err
}

const markPasswordResetTokenUsed = `-- name: MarkPasswordResetTokenUsed :exec
update password_reset_tokens set used_at = now() where id = $1
`

func (q *Queries) MarkPasswordResetTokenUsed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markPasswordResetTokenUsed, id)
	return err
}
