// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: sales.sql

package db

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
	"github.com/shopspring/decimal"
)

const countSales = `-- name: CountSales :one
select count(*) from orders o
where o.business_date between $1 and $2
  and ($3::order_status is null or o.status = $3)
  and ($4::service_type is null or o.service_type = $4)
`

type CountSalesParams struct {
	Desde       pgtype.Date  `json:"desde"`
	Hasta       pgtype.Date  `json:"hasta"`
	Status      *OrderStatus `json:"status"`
	ServiceType *ServiceType `json:"service_type"`
}

// El mismo `where` que ListSales, palabra por palabra. Es el total del filtro para el paginador.
func (q *Queries) CountSales(ctx context.Context, arg CountSalesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSales,
		arg.Desde,
		arg.Hasta,
		arg.Status,
		arg.ServiceType,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const listSales = `-- name: ListSales :many

select o.id, o.daily_number, o.folio_name, o.business_date, o.opened_at, o.completed_at,
       o.status, o.service_type, o.customer_name, o.total, o.delivery_fee, o.refund_amount,
       dp.name as platform,
       u.name as opened_by_name,
       (select coalesce(sum(op.tip_amount), 0) from order_payments op where op.order_id = o.id)::numeric(10,2) as tips,
       (select string_agg(distinct pm.name, ' + ' order by pm.name)
          from order_payments op join payment_methods pm on pm.id = op.payment_method_id
         where op.order_id = o.id) as methods
from orders o
left join delivery_platforms dp on dp.id = o.delivery_platform_id
left join users u on u.id = o.opened_by
where o.business_date between $1 and $2
  and ($3::order_status is null or o.status = $3)
  and ($4::service_type is null or o.service_type = $4)
order by
  case when $5::text = 'total'  and $6::text = 'asc'  then o.total end asc  nulls last,
  case when $5::text = 'total'  and $6::text <> 'asc' then o.total end desc nulls last,
  case when $5::text = 'folio'  and $6::text = 'asc'  then o.daily_number end asc  nulls last,
  case when $5::text = 'folio'  and $6::text <> 'asc' then o.daily_number end desc nulls last,
  case when $5::text = 'estado' and $6::text = 'asc'  then o.status::text end asc  nulls last,
  case when $5::text = 'estado' and $6::text <> 'asc' then o.status::text end desc nulls last,
  case when $5::text = 'tipo'   and $6::text = 'asc'  then o.service_type::text end asc  nulls last,
  case when $5::text = 'tipo'   and $6::text <> 'asc' then o.service_type::text end desc nulls last,
  case when $5::text = 'fecha'  and $6::text = 'asc'  then o.opened_at end asc,
  o.opened_at desc, o.id desc
limit $8 offset $7
`

type ListSalesParams struct {
	Desde       pgtype.Date  `json:"desde"`
	Hasta       pgtype.Date  `json:"hasta"`
	Status      *OrderStatus `json:"status"`
	ServiceType *ServiceType `json:"service_type"`
	Sort        string       `json:"sort"`
	Dir         string       `json:"dir"`
	Off         int32        `json:"off"`
	Lim         int32        `json:"lim"`
}

type ListSalesRow struct {
	ID           int64              `json:"id"`
	DailyNumber  int32              `json:"daily_number"`
	FolioName    *string            `json:"folio_name"`
	BusinessDate pgtype.Date        `json:"business_date"`
	OpenedAt     time.Time          `json:"opened_at"`
	CompletedAt  pgtype.Timestamptz `json:"completed_at"`
	Status       OrderStatus        `json:"status"`
	ServiceType  ServiceType        `json:"service_type"`
	CustomerName *string            `json:"customer_name"`
	Total        decimal.Decimal    `json:"total"`
	DeliveryFee  decimal.Decimal    `json:"delivery_fee"`
	RefundAmount decimal.Decimal    `json:"refund_amount"`
	Platform     *string            `json:"platform"`
	OpenedByName *string            `json:"opened_by_name"`
	Tips         decimal.Decimal    `json:"tips"`
	Methods      []byte             `json:"methods"`
}

// Pantalla de Ventas (análisis). Distinta del tablero de pedidos: aquí se mira lo que YA pasó.
//
// Las cinco consultas comparten el mismo `where` y viven juntas A PROPÓSITO: si el filtro de la
// lista y el del resumen divergen, las cifras de arriba dejan de cuadrar con la tabla de abajo y
// nadie sabe cuál de las dos miente. Se editan en la misma pasada.
//
// Ninguna filtra por company_id, y no es un olvido: RLS agrega ese predicado a toda consulta del rol
// `gatobobah_app`. Además sqlc NO conoce la columna —la migración 0023 la agregó con SQL dinámico
// que su parser no puede leer—, así que nombrarla aquí rompería `sqlc generate` por una columna que
// sí existe en Postgres.
//
// El resumen va en tres consultas y no en una: `order_payments` y `order_lines` son ambas 1:N con
// `orders`, así que unirlas en la misma consulta multiplica las filas (2 pagos × 3 líneas = 6) y
// duplica las sumas.
// Orden por columna: @sort ∈ (fecha|folio|total|estado|tipo) × @dir (asc|desc). En SQL y no en el
// cliente porque la lista está paginada: ordenar solo las 20 filas visibles daría un orden falso.
// El desempate fijo (opened_at desc, id desc) evita que dos ventas del mismo total bailen entre
// páginas.
func (q *Queries) ListSales(ctx context.Context, arg ListSalesParams) ([]ListSalesRow, error) {
	rows, err := q.db.Query(ctx, listSales,
		arg.Desde,
		arg.Hasta,
		arg.Status,
		arg.ServiceType,
		arg.Sort,
		arg.Dir,
		arg.Off,
		arg.Lim,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListSalesRow{}
	for rows.Next() {
		var i ListSalesRow
		if err := rows.Scan(
			&i.ID,
			&i.DailyNumber,
			&i.FolioName,
			&i.BusinessDate,
			&i.OpenedAt,
			&i.CompletedAt,
			&i.Status,
			&i.ServiceType,
			&i.CustomerName,
			&i.Total,
			&i.DeliveryFee,
			&i.RefundAmount,
			&i.Platform,
			&i.OpenedByName,
			&i.Tips,
			&i.Methods,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesCancelledLines = `-- name: SalesCancelledLines :one
select count(*)::int as lineas,
       coalesce(sum(ol.line_total), 0)::numeric(12,2) as monto
from order_lines ol
join orders o on o.id = ol.order_id
where o.business_date between $1 and $2
  and ol.cancelled_at is not null
  -- El mismo filtro de tipo que el resto del resumen: sin él, filtrar la pantalla a domicilio
  -- seguía mostrando la merma de mostrador y las cifras dejaban de ser del mismo conjunto.
  and ($3::service_type is null or o.service_type = $3)
`

type SalesCancelledLinesParams struct {
	Desde       pgtype.Date  `json:"desde"`
	Hasta       pgtype.Date  `json:"hasta"`
	ServiceType *ServiceType `json:"service_type"`
}

type SalesCancelledLinesRow struct {
	Lineas int32           `json:"lineas"`
	Monto  decimal.Decimal `json:"monto"`
}

// Líneas canceladas dentro de ventas que NO se cancelaron enteras: es la merma que se pierde de
// vista, porque el pedido se cobró y el renglón no.
func (q *Queries) SalesCancelledLines(ctx context.Context, arg SalesCancelledLinesParams) (SalesCancelledLinesRow, error) {
	row := q.db.QueryRow(ctx, salesCancelledLines, arg.Desde, arg.Hasta, arg.ServiceType)
	var i SalesCancelledLinesRow
	err := row.Scan(&i.Lineas, &i.Monto)
	return i, err
}

const salesTotalsByMethod = `-- name: SalesTotalsByMethod :many
select pm.id as method_id, pm.name as method,
       count(*)::int as pagos,
       coalesce(sum(op.amount), 0)::numeric(12,2) as total,
       coalesce(sum(op.tip_amount), 0)::numeric(12,2) as propinas
from order_payments op
join orders o on o.id = op.order_id
join payment_methods pm on pm.id = op.payment_method_id
where o.business_date between $1 and $2
  and ($3::service_type is null or o.service_type = $3)
group by pm.id, pm.name
order by total desc
`

type SalesTotalsByMethodParams struct {
	Desde       pgtype.Date  `json:"desde"`
	Hasta       pgtype.Date  `json:"hasta"`
	ServiceType *ServiceType `json:"service_type"`
}

type SalesTotalsByMethodRow struct {
	MethodID int16           `json:"method_id"`
	Method   string          `json:"method"`
	Pagos    int32           `json:"pagos"`
	Total    decimal.Decimal `json:"total"`
	Propinas decimal.Decimal `json:"propinas"`
}

// Desglose por medio de pago: lo COBRADO, que no es lo mismo que lo vendido (una venta mandada a
// cocina sin cobrar suma al total y no aparece aquí). Sale de order_payments porque una venta puede
// pagarse con varios métodos.
//
// Sin filtro de estado, por el mismo motivo que SalesTotalsByStatus: el resumen dice cuánto entró
// por cada medio aunque la tabla esté filtrada a un estado. El de tipo de venta sí aplica.
func (q *Queries) SalesTotalsByMethod(ctx context.Context, arg SalesTotalsByMethodParams) ([]SalesTotalsByMethodRow, error) {
	rows, err := q.db.Query(ctx, salesTotalsByMethod, arg.Desde, arg.Hasta, arg.ServiceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesTotalsByMethodRow{}
	for rows.Next() {
		var i SalesTotalsByMethodRow
		if err := rows.Scan(
			&i.MethodID,
			&i.Method,
			&i.Pagos,
			&i.Total,
			&i.Propinas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const salesTotalsByStatus = `-- name: SalesTotalsByStatus :many
with filtrado as (
  select o.id, o.status, o.total, o.delivery_fee
  from orders o
  where o.business_date between $1 and $2
    and ($3::service_type is null or o.service_type = $3)
), propinas as (
  select op.order_id, sum(op.tip_amount) as tip_amount
  from order_payments op
  join filtrado f on f.id = op.order_id
  group by op.order_id
)
select f.status,
       count(*)::int as ventas,
       coalesce(sum(f.total), 0)::numeric(12,2) as total,
       coalesce(sum(f.delivery_fee), 0)::numeric(12,2) as envios,
       coalesce(sum(p.tip_amount), 0)::numeric(12,2) as propinas
from filtrado f
left join propinas p on p.order_id = f.id
group by f.status
`

type SalesTotalsByStatusParams struct {
	Desde       pgtype.Date  `json:"desde"`
	Hasta       pgtype.Date  `json:"hasta"`
	ServiceType *ServiceType `json:"service_type"`
}

type SalesTotalsByStatusRow struct {
	Status   OrderStatus     `json:"status"`
	Ventas   int32           `json:"ventas"`
	Total    decimal.Decimal `json:"total"`
	Envios   decimal.Decimal `json:"envios"`
	Propinas decimal.Decimal `json:"propinas"`
}

// Agrupa POR ESTADO y deja que el dominio decida qué cuenta como ingreso. Postgres hace la suma
// pesada —que es la que puede usar un índice— y en Go se queda la regla de clasificación, que es lo
// que tiene que poder probarse sin base de datos.
//
// No lleva el filtro de estado: el resumen tiene que poder decir cuánto se canceló aunque la tabla
// esté filtrada a entregadas. Filtrar aquí haría que el tile de cancelaciones marcara cero justo
// cuando se está buscando una. El de TIPO DE VENTA sí lo lleva, y en las dos ramas: con una
// subconsulta que solo filtraba por fecha, la propina sumaba la de todos los tipos y salía inflada
// junto a cifras correctas — que es peor que un número mal parejo, porque invita a confiar en el resto.
//
// Las propinas se pre-agregan por order_id antes de unirse. Sin eso, una venta con dos pagos
// duplicaría su total: order_payments es 1:N con orders.
func (q *Queries) SalesTotalsByStatus(ctx context.Context, arg SalesTotalsByStatusParams) ([]SalesTotalsByStatusRow, error) {
	rows, err := q.db.Query(ctx, salesTotalsByStatus, arg.Desde, arg.Hasta, arg.ServiceType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SalesTotalsByStatusRow{}
	for rows.Next() {
		var i SalesTotalsByStatusRow
		if err := rows.Scan(
			&i.Status,
			&i.Ventas,
			&i.Total,
			&i.Envios,
			&i.Propinas,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
