// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: settings.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const getBusinessSettings = `-- name: GetBusinessSettings :one
select id, delivery_fee, updated_at, updated_by from business_settings where id = true
`

func (q *Queries) GetBusinessSettings(ctx context.Context) (BusinessSetting, error) {
	row := q.db.QueryRow(ctx, getBusinessSettings)
	var i BusinessSetting
	err := row.Scan(
		&i.ID,
		&i.DeliveryFee,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}

const updateDeliveryFee = `-- name: UpdateDeliveryFee :one
update business_settings
set delivery_fee = $1, updated_at = now(), updated_by = $2
where id = true
returning id, delivery_fee, updated_at, updated_by
`

type UpdateDeliveryFeeParams struct {
	DeliveryFee decimal.Decimal `json:"delivery_fee"`
	UpdatedBy   *int64          `json:"updated_by"`
}

func (q *Queries) UpdateDeliveryFee(ctx context.Context, arg UpdateDeliveryFeeParams) (BusinessSetting, error) {
	row := q.db.QueryRow(ctx, updateDeliveryFee, arg.DeliveryFee, arg.UpdatedBy)
	var i BusinessSetting
	err := row.Scan(
		&i.ID,
		&i.DeliveryFee,
		&i.UpdatedAt,
		&i.UpdatedBy,
	)
	return i, err
}
