// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: stock.sql

package db

import (
	"context"
	"time"

	"github.com/shopspring/decimal"
)

const insertStockMovement = `-- name: InsertStockMovement :exec

insert into stock_movements (item_type, ingredient_id, product_id, movement_type, quantity, unit_cost, order_id, order_line_id, user_id, reason, note,
                             modifier_option_id, component_of_product_id)
values ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13)
`

type InsertStockMovementParams struct {
	ItemType             StockItemType     `json:"item_type"`
	IngredientID         *int64            `json:"ingredient_id"`
	ProductID            *int64            `json:"product_id"`
	MovementType         StockMovementType `json:"movement_type"`
	Quantity             decimal.Decimal   `json:"quantity"`
	UnitCost             *decimal.Decimal  `json:"unit_cost"`
	OrderID              *int64            `json:"order_id"`
	OrderLineID          *int64            `json:"order_line_id"`
	UserID               *int64            `json:"user_id"`
	Reason               *string           `json:"reason"`
	Note                 *string           `json:"note"`
	ModifierOptionID     *int64            `json:"modifier_option_id"`
	ComponentOfProductID *int64            `json:"component_of_product_id"`
}

// Depleción en venta
// order_line_id: de QUÉ renglón salió este descuento.
//
// Sin él, reponer un renglón cancelado obliga a recalcular su consumo con la receta de HOY, y una
// receta que cambió entre la venta y la cancelación repondría una cantidad distinta de la que salió.
// NULL en los movimientos que no vienen de una venta (ajustes, compras, mermas).
// modifier_option_id / component_of_product_id: el extra o el paquete que originó el descuento.
func (q *Queries) InsertStockMovement(ctx context.Context, arg InsertStockMovementParams) error {
	_, err := q.db.Exec(ctx, insertStockMovement,
		arg.ItemType,
		arg.IngredientID,
		arg.ProductID,
		arg.MovementType,
		arg.Quantity,
		arg.UnitCost,
		arg.OrderID,
		arg.OrderLineID,
		arg.UserID,
		arg.Reason,
		arg.Note,
		arg.ModifierOptionID,
		arg.ComponentOfProductID,
	)
	return err
}

const listStockLevels = `-- name: ListStockLevels :many

select sl.item_type,
       coalesce(i.name, p.name) as item_name,
       sl.on_hand,
       coalesce(i.min_stock, p.min_stock) as min_stock,
       coalesce(iu.code, 'pieza') as unit_code
from stock_levels sl
left join ingredients i on i.id = sl.ingredient_id
left join units iu on iu.id = i.base_unit_id
left join products p on p.id = sl.product_id
where sl.branch_id = current_branch_id()
order by item_name
`

type ListStockLevelsRow struct {
	ItemType StockItemType    `json:"item_type"`
	ItemName string           `json:"item_name"`
	OnHand   decimal.Decimal  `json:"on_hand"`
	MinStock *decimal.Decimal `json:"min_stock"`
	UnitCode string           `json:"unit_code"`
}

// Almacén / niveles
// Las de la sucursal (0076): con dos, el mismo insumo saldría dos veces sin decir de cuál es.
func (q *Queries) ListStockLevels(ctx context.Context) ([]ListStockLevelsRow, error) {
	rows, err := q.db.Query(ctx, listStockLevels)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockLevelsRow{}
	for rows.Next() {
		var i ListStockLevelsRow
		if err := rows.Scan(
			&i.ItemType,
			&i.ItemName,
			&i.OnHand,
			&i.MinStock,
			&i.UnitCode,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStockMovements = `-- name: ListStockMovements :many
select sm.id, sm.item_type, coalesce(i.name, p.name) as item_name, sm.movement_type,
       sm.quantity, sm.reason, sm.created_at
from stock_movements sm
left join ingredients i on i.id = sm.ingredient_id
left join products p on p.id = sm.product_id
order by sm.created_at desc
limit $1
`

type ListStockMovementsRow struct {
	ID           int64             `json:"id"`
	ItemType     StockItemType     `json:"item_type"`
	ItemName     string            `json:"item_name"`
	MovementType StockMovementType `json:"movement_type"`
	Quantity     decimal.Decimal   `json:"quantity"`
	Reason       *string           `json:"reason"`
	CreatedAt    time.Time         `json:"created_at"`
}

func (q *Queries) ListStockMovements(ctx context.Context, limit int32) ([]ListStockMovementsRow, error) {
	rows, err := q.db.Query(ctx, listStockMovements, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListStockMovementsRow{}
	for rows.Next() {
		var i ListStockMovementsRow
		if err := rows.Scan(
			&i.ID,
			&i.ItemType,
			&i.ItemName,
			&i.MovementType,
			&i.Quantity,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
