// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: terminals.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const activeTerminalsOfRegisterBranch = `-- name: ActiveTerminalsOfRegisterBranch :many
select t.id, t.name
  from card_terminals t
  join cash_registers r on r.branch_id = t.branch_id
 where r.id = $1 and t.archived_at is null
 order by t.id
`

type ActiveTerminalsOfRegisterBranchRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Las terminales activas de la sucursal de una caja: entre ellas se elige al cobrar.
func (q *Queries) ActiveTerminalsOfRegisterBranch(ctx context.Context, id int64) ([]ActiveTerminalsOfRegisterBranchRow, error) {
	rows, err := q.db.Query(ctx, activeTerminalsOfRegisterBranch, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ActiveTerminalsOfRegisterBranchRow{}
	for rows.Next() {
		var i ActiveTerminalsOfRegisterBranchRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const archiveCardTerminal = `-- name: ArchiveCardTerminal :execrows
update card_terminals set archived_at = now() where id = $1 and archived_at is null
`

func (q *Queries) ArchiveCardTerminal(ctx context.Context, id int64) (int64, error) {
	result, err := q.db.Exec(ctx, archiveCardTerminal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertCardTerminal = `-- name: InsertCardTerminal :one
insert into card_terminals (branch_id, name) values ($1, $2) returning id, branch_id, name
`

type InsertCardTerminalParams struct {
	BranchID int64  `json:"branch_id"`
	Name     string `json:"name"`
}

type InsertCardTerminalRow struct {
	ID       int64  `json:"id"`
	BranchID int64  `json:"branch_id"`
	Name     string `json:"name"`
}

func (q *Queries) InsertCardTerminal(ctx context.Context, arg InsertCardTerminalParams) (InsertCardTerminalRow, error) {
	row := q.db.QueryRow(ctx, insertCardTerminal, arg.BranchID, arg.Name)
	var i InsertCardTerminalRow
	err := row.Scan(&i.ID, &i.BranchID, &i.Name)
	return i, err
}

const insertSessionTerminalCount = `-- name: InsertSessionTerminalCount :exec
insert into session_terminal_counts (session_id, card_terminal_id, terminal_name, expected, declared, created_by)
values ($1, $2, $3, $4, $5, $6)
`

type InsertSessionTerminalCountParams struct {
	SessionID      int64           `json:"session_id"`
	CardTerminalID int64           `json:"card_terminal_id"`
	TerminalName   string          `json:"terminal_name"`
	Expected       decimal.Decimal `json:"expected"`
	Declared       decimal.Decimal `json:"declared"`
	CreatedBy      int64           `json:"created_by"`
}

func (q *Queries) InsertSessionTerminalCount(ctx context.Context, arg InsertSessionTerminalCountParams) error {
	_, err := q.db.Exec(ctx, insertSessionTerminalCount,
		arg.SessionID,
		arg.CardTerminalID,
		arg.TerminalName,
		arg.Expected,
		arg.Declared,
		arg.CreatedBy,
	)
	return err
}

const listBranchCardCountModes = `-- name: ListBranchCardCountModes :many
select id, name, card_count_mode from branches where is_active order by branch_number
`

type ListBranchCardCountModesRow struct {
	ID            int64  `json:"id"`
	Name          string `json:"name"`
	CardCountMode string `json:"card_count_mode"`
}

func (q *Queries) ListBranchCardCountModes(ctx context.Context) ([]ListBranchCardCountModesRow, error) {
	rows, err := q.db.Query(ctx, listBranchCardCountModes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListBranchCardCountModesRow{}
	for rows.Next() {
		var i ListBranchCardCountModesRow
		if err := rows.Scan(&i.ID, &i.Name, &i.CardCountMode); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCardTerminals = `-- name: ListCardTerminals :many

select t.id, t.branch_id, b.name as branch_name, t.name, (t.archived_at is not null)::boolean as archived
  from card_terminals t
  join branches b on b.id = t.branch_id
 order by b.branch_number, t.archived_at nulls first, lower(t.name)
`

type ListCardTerminalsRow struct {
	ID         int64  `json:"id"`
	BranchID   int64  `json:"branch_id"`
	BranchName string `json:"branch_name"`
	Name       string `json:"name"`
	Archived   bool   `json:"archived"`
}

// Terminales de tarjeta por sucursal (spec 032, puntos 8 y 9). RLS acota a la empresa.
func (q *Queries) ListCardTerminals(ctx context.Context) ([]ListCardTerminalsRow, error) {
	rows, err := q.db.Query(ctx, listCardTerminals)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListCardTerminalsRow{}
	for rows.Next() {
		var i ListCardTerminalsRow
		if err := rows.Scan(
			&i.ID,
			&i.BranchID,
			&i.BranchName,
			&i.Name,
			&i.Archived,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const paymentTerminalForRefund = `-- name: PaymentTerminalForRefund :one
select op.id, op.card_terminal_name, pm.kind
  from order_payments op
  join payment_methods pm on pm.id = op.payment_method_id
 where op.id = $1
`

type PaymentTerminalForRefundRow struct {
	ID               int64       `json:"id"`
	CardTerminalName *string     `json:"card_terminal_name"`
	Kind             PaymentKind `json:"kind"`
}

// La terminal del cobro que se devuelve: la pantalla dice en cuál hacer la devolución.
func (q *Queries) PaymentTerminalForRefund(ctx context.Context, id int64) (PaymentTerminalForRefundRow, error) {
	row := q.db.QueryRow(ctx, paymentTerminalForRefund, id)
	var i PaymentTerminalForRefundRow
	err := row.Scan(&i.ID, &i.CardTerminalName, &i.Kind)
	return i, err
}

const renameCardTerminal = `-- name: RenameCardTerminal :one
update card_terminals set name = $2 where id = $1 and archived_at is null returning id, branch_id, name
`

type RenameCardTerminalParams struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

type RenameCardTerminalRow struct {
	ID       int64  `json:"id"`
	BranchID int64  `json:"branch_id"`
	Name     string `json:"name"`
}

func (q *Queries) RenameCardTerminal(ctx context.Context, arg RenameCardTerminalParams) (RenameCardTerminalRow, error) {
	row := q.db.QueryRow(ctx, renameCardTerminal, arg.ID, arg.Name)
	var i RenameCardTerminalRow
	err := row.Scan(&i.ID, &i.BranchID, &i.Name)
	return i, err
}

const sessionTerminalCounts = `-- name: SessionTerminalCounts :many
select card_terminal_id, terminal_name, expected, declared, (declared - expected)::numeric(10,2) as difference
  from session_terminal_counts where session_id = $1 order by card_terminal_id
`

type SessionTerminalCountsRow struct {
	CardTerminalID int64           `json:"card_terminal_id"`
	TerminalName   string          `json:"terminal_name"`
	Expected       decimal.Decimal `json:"expected"`
	Declared       decimal.Decimal `json:"declared"`
	Difference     decimal.Decimal `json:"difference"`
}

func (q *Queries) SessionTerminalCounts(ctx context.Context, sessionID int64) ([]SessionTerminalCountsRow, error) {
	rows, err := q.db.Query(ctx, sessionTerminalCounts, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SessionTerminalCountsRow{}
	for rows.Next() {
		var i SessionTerminalCountsRow
		if err := rows.Scan(
			&i.CardTerminalID,
			&i.TerminalName,
			&i.Expected,
			&i.Declared,
			&i.Difference,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBranchCardCountMode = `-- name: SetBranchCardCountMode :execrows
update branches set card_count_mode = $2 where id = $1
`

type SetBranchCardCountModeParams struct {
	ID            int64  `json:"id"`
	CardCountMode string `json:"card_count_mode"`
}

func (q *Queries) SetBranchCardCountMode(ctx context.Context, arg SetBranchCardCountModeParams) (int64, error) {
	result, err := q.db.Exec(ctx, setBranchCardCountMode, arg.ID, arg.CardCountMode)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const setPaymentTerminal = `-- name: SetPaymentTerminal :exec
update order_payments set card_terminal_id = $2, card_terminal_name = $3 where id = $1
`

type SetPaymentTerminalParams struct {
	ID               int64   `json:"id"`
	CardTerminalID   *int64  `json:"card_terminal_id"`
	CardTerminalName *string `json:"card_terminal_name"`
}

func (q *Queries) SetPaymentTerminal(ctx context.Context, arg SetPaymentTerminalParams) error {
	_, err := q.db.Exec(ctx, setPaymentTerminal, arg.ID, arg.CardTerminalID, arg.CardTerminalName)
	return err
}

const terminalCollectedForSession = `-- name: TerminalCollectedForSession :many
with cobrado as (
  select op.card_terminal_id, max(op.card_terminal_name) as name, sum(op.amount + op.tip_amount) as total
    from order_payments op
   where op.register_session_id = $1::bigint and op.card_terminal_id is not null
   group by op.card_terminal_id
)
select c.card_terminal_id::bigint as terminal_id, c.name::text as name,
       coalesce(c.total, 0)::numeric(10,2) as collected
  from cobrado c
 order by c.card_terminal_id
`

type TerminalCollectedForSessionRow struct {
	TerminalID int64           `json:"terminal_id"`
	Name       string          `json:"name"`
	Collected  decimal.Decimal `json:"collected"`
}

// Lo cobrado por terminal en el turno, menos lo devuelto de esos cobros (sin pasar por el cajón).
// Se pre-agrega cada rama por terminal: cobros y devoluciones son dos 1:N.
func (q *Queries) TerminalCollectedForSession(ctx context.Context, sessionID int64) ([]TerminalCollectedForSessionRow, error) {
	rows, err := q.db.Query(ctx, terminalCollectedForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TerminalCollectedForSessionRow{}
	for rows.Next() {
		var i TerminalCollectedForSessionRow
		if err := rows.Scan(&i.TerminalID, &i.Name, &i.Collected); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
