// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tips.sql

package db

import (
	"context"

	"github.com/shopspring/decimal"
)

const inheritedTipsForSession = `-- name: InheritedTipsForSession :one
select coalesce((select p.tips_carried_over
                   from register_sessions p
                  where p.register_id = cur.register_id
                    and p.id <> cur.id
                    and p.opened_at < cur.opened_at
                  order by p.opened_at desc, p.id desc
                  limit 1), 0)::numeric(10,2) as carried_in,
       coalesce((select sum(s.amount)
                   from tip_payout_sources s
                   join register_cash_movements m on m.company_id = s.company_id and m.id = s.movement_id
                  where m.session_id = cur.id and s.order_payment_id is null), 0)::numeric(10,2) as used
  from register_sessions cur
 where cur.id = $1::bigint
`

type InheritedTipsForSessionRow struct {
	CarriedIn decimal.Decimal `json:"carried_in"`
	Used      decimal.Decimal `json:"used"`
}

// Lo que el turno anterior de la MISMA caja dejó en caja, menos lo que este turno ya entregó de
// ello. Por caja y no por empresa: con dos cajas abiertas cada una hereda solo lo suyo.
func (q *Queries) InheritedTipsForSession(ctx context.Context, sessionID int64) (InheritedTipsForSessionRow, error) {
	row := q.db.QueryRow(ctx, inheritedTipsForSession, sessionID)
	var i InheritedTipsForSessionRow
	err := row.Scan(&i.CarriedIn, &i.Used)
	return i, err
}

const insertTipMovement = `-- name: InsertTipMovement :one
insert into register_cash_movements (session_id, kind, amount, concept, user_id, recipient_user_id, recipient_name)
values ($1, 'propina', $2, $3, $4,
        $5, $6)
returning id
`

type InsertTipMovementParams struct {
	SessionID       int64           `json:"session_id"`
	Amount          decimal.Decimal `json:"amount"`
	Concept         string          `json:"concept"`
	UserID          int64           `json:"user_id"`
	RecipientUserID *int64          `json:"recipient_user_id"`
	RecipientName   *string         `json:"recipient_name"`
}

func (q *Queries) InsertTipMovement(ctx context.Context, arg InsertTipMovementParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertTipMovement,
		arg.SessionID,
		arg.Amount,
		arg.Concept,
		arg.UserID,
		arg.RecipientUserID,
		arg.RecipientName,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertTipSource = `-- name: InsertTipSource :exec
insert into tip_payout_sources (movement_id, order_payment_id, amount)
values ($1, $3, $2)
`

type InsertTipSourceParams struct {
	MovementID     int64           `json:"movement_id"`
	Amount         decimal.Decimal `json:"amount"`
	OrderPaymentID *int64          `json:"order_payment_id"`
}

func (q *Queries) InsertTipSource(ctx context.Context, arg InsertTipSourceParams) error {
	_, err := q.db.Exec(ctx, insertTipSource, arg.MovementID, arg.Amount, arg.OrderPaymentID)
	return err
}

const lockSessionForTips = `-- name: LockSessionForTips :one
select id from register_sessions where id = $1 and status = 'abierta' for update
`

// Dos tabletas repartiendo a la vez leerían el mismo pendiente y entregarían dos veces lo mismo;
// el candado del turno las pone en fila.
// Solo si sigue abierto: un cierre que confirmó mientras se esperaba ya heredó esta propina.
func (q *Queries) LockSessionForTips(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, lockSessionForTips, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const refundedTipsByOrderForSession = `-- name: RefundedTipsByOrderForSession :many
select r.order_id, sum(r.tip_amount)::numeric(10,2) as refunded_tips
  from order_refunds r
 where r.tip_amount > 0
   and r.order_id in (select op.order_id from order_payments op
                       where op.register_session_id = $1::bigint and op.tip_amount > 0)
 group by r.order_id
`

type RefundedTipsByOrderForSessionRow struct {
	OrderID      int64           `json:"order_id"`
	RefundedTips decimal.Decimal `json:"refunded_tips"`
}

// Propina devuelta de los pedidos que cobraron propina en este turno, en el turno que sea: lo
// devuelto deja de ser propina del personal aunque la devolución ocurra mañana.
func (q *Queries) RefundedTipsByOrderForSession(ctx context.Context, sessionID int64) ([]RefundedTipsByOrderForSessionRow, error) {
	rows, err := q.db.Query(ctx, refundedTipsByOrderForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []RefundedTipsByOrderForSessionRow{}
	for rows.Next() {
		var i RefundedTipsByOrderForSessionRow
		if err := rows.Scan(&i.OrderID, &i.RefundedTips); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTipsCarriedOver = `-- name: SetTipsCarriedOver :exec
update register_sessions set tips_carried_over = $2 where id = $1
`

type SetTipsCarriedOverParams struct {
	ID              int64           `json:"id"`
	TipsCarriedOver decimal.Decimal `json:"tips_carried_over"`
}

func (q *Queries) SetTipsCarriedOver(ctx context.Context, arg SetTipsCarriedOverParams) error {
	_, err := q.db.Exec(ctx, setTipsCarriedOver, arg.ID, arg.TipsCarriedOver)
	return err
}

const tipPaymentsForSession = `-- name: TipPaymentsForSession :many

with entregado as (
  select s.order_payment_id, sum(s.amount) as paid_out
    from tip_payout_sources s
   where s.order_payment_id is not null
   group by s.order_payment_id
)
select op.id, op.order_id, pm.is_cash,
       op.tip_amount, coalesce(e.paid_out, 0)::numeric(10,2) as paid_out
  from order_payments op
  join payment_methods pm on pm.id = op.payment_method_id
  left join entregado e on e.order_payment_id = op.id
 where op.register_session_id = $1::bigint
   and op.tip_amount > 0
 order by op.created_at, op.id
`

type TipPaymentsForSessionRow struct {
	ID        int64           `json:"id"`
	OrderID   int64           `json:"order_id"`
	IsCash    bool            `json:"is_cash"`
	TipAmount decimal.Decimal `json:"tip_amount"`
	PaidOut   decimal.Decimal `json:"paid_out"`
}

// Propinas por entregar (spec 032). El pendiente se calcula siempre desde los hechos —cobros,
// devoluciones y entregas— y nunca se guarda: un saldo guardado es una segunda verdad que diverge.
// Cada cobro del turno con propina, con lo que ya se entregó de él. Las entregas se pre-agregan por
// cobro antes de unirse: son 1:N y unirlas tal cual multiplicaría la propina.
func (q *Queries) TipPaymentsForSession(ctx context.Context, sessionID int64) ([]TipPaymentsForSessionRow, error) {
	rows, err := q.db.Query(ctx, tipPaymentsForSession, sessionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []TipPaymentsForSessionRow{}
	for rows.Next() {
		var i TipPaymentsForSessionRow
		if err := rows.Scan(
			&i.ID,
			&i.OrderID,
			&i.IsCash,
			&i.TipAmount,
			&i.PaidOut,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const tipPayoutTotalsForSession = `-- name: TipPayoutTotalsForSession :one
select coalesce(sum(s.amount), 0)::numeric(10,2) as paid_out,
       coalesce(sum(s.amount) filter (where pm.is_cash is false), 0)::numeric(10,2) as non_cash_paid_in_cash
  from tip_payout_sources s
  join register_cash_movements m on m.company_id = s.company_id and m.id = s.movement_id
  left join order_payments op on op.id = s.order_payment_id
  left join payment_methods pm on pm.id = op.payment_method_id
 where m.session_id = $1::bigint
`

type TipPayoutTotalsForSessionRow struct {
	PaidOut           decimal.Decimal `json:"paid_out"`
	NonCashPaidInCash decimal.Decimal `json:"non_cash_paid_in_cash"`
}

// Lo entregado en el turno y cuánto de eso fue propina de un medio que no es efectivo, pagada con
// efectivo del cajón (punto 2). Lo heredado cuenta como efectivo: ya estaba en el cajón.
func (q *Queries) TipPayoutTotalsForSession(ctx context.Context, sessionID int64) (TipPayoutTotalsForSessionRow, error) {
	row := q.db.QueryRow(ctx, tipPayoutTotalsForSession, sessionID)
	var i TipPayoutTotalsForSessionRow
	err := row.Scan(&i.PaidOut, &i.NonCashPaidInCash)
	return i, err
}
