// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package db

import (
	"context"
	"time"

	"uuid"
)

const clearAllPins = `-- name: ClearAllPins :exec
update users set pin_hash = null, pin_lookup = null, updated_at = now()
where pin_hash is not null or pin_lookup is not null
`

// Borra los PINs de TODAS las personas de la empresa, activas o no.
//
// Lo usa el encendido del modo de solo-PIN: los PINs de antes son de 4 dígitos y sin garantía de ser
// distintos, y de lo guardado no se puede saber ni una cosa ni la otra. Obligar a recapturarlos es
// el único momento en que el PIN está en claro y se puede validar largo y unicidad.
//
// También a quien está dado de baja: decía `where is_active` y a esa persona le quedaba su PIN de
// cuatro dígitos intacto, así que reactivarla metía en un negocio de seis dígitos un PIN de cuatro
// que abre la caja — 10,000 combinaciones en vez de un millón, y sin nada que lo delatara.
//
// Nadie queda encerrado: quien no tiene PIN entra con usuario y contraseña, que sigue funcionando.
func (q *Queries) ClearAllPins(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAllPins)
	return err
}

const countUsers = `-- name: CountUsers :one
select count(*) from users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createRefreshToken = `-- name: CreateRefreshToken :one
insert into refresh_tokens (user_id, token_hash, expires_at, family_id)
values ($1, $2, $3, $4)
returning id, user_id, token_hash, expires_at, revoked_at, created_at, family_id
`

type CreateRefreshTokenParams struct {
	UserID    int64      `json:"user_id"`
	TokenHash string     `json:"token_hash"`
	ExpiresAt time.Time  `json:"expires_at"`
	FamilyID  *uuid.UUID `json:"family_id"`
}

// family_id es la CADENA a la que pertenece la credencial: nace en un login y se propaga en cada
// rotación. Es lo que deja cortar al ladrón sin tumbar la tableta del compañero, que comparte cuenta.
func (q *Queries) CreateRefreshToken(ctx context.Context, arg CreateRefreshTokenParams) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, createRefreshToken,
		arg.UserID,
		arg.TokenHash,
		arg.ExpiresAt,
		arg.FamilyID,
	)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.FamilyID,
	)
	return i, err
}

const createUser = `-- name: CreateUser :one
insert into users (name, username, role, pin_hash, pin_lookup, password_hash, recovery_email, must_change_password)
values ($1, $2, $3, $4, $8, $5, $6, $7)
returning id, name, username, role, pin_hash, password_hash, is_active, created_at, updated_at, company_id, recovery_email, must_change_password, pin_lookup
`

type CreateUserParams struct {
	Name               string  `json:"name"`
	Username           *string `json:"username"`
	Role               string  `json:"role"`
	PinHash            *string `json:"pin_hash"`
	PasswordHash       *string `json:"password_hash"`
	RecoveryEmail      *string `json:"recovery_email"`
	MustChangePassword bool    `json:"must_change_password"`
	PinLookup          *string `json:"pin_lookup"`
}

// company_id lo auto-sella el default (current_setting) desde el GUC del tenant; RLS lo exige.
func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.Name,
		arg.Username,
		arg.Role,
		arg.PinHash,
		arg.PasswordHash,
		arg.RecoveryEmail,
		arg.MustChangePassword,
		arg.PinLookup,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Role,
		&i.PinHash,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.RecoveryEmail,
		&i.MustChangePassword,
		&i.PinLookup,
	)
	return i, err
}

const getRefreshToken = `-- name: GetRefreshToken :one
select id, user_id, token_hash, expires_at, revoked_at, created_at, family_id
from refresh_tokens where token_hash = $1
`

func (q *Queries) GetRefreshToken(ctx context.Context, tokenHash string) (RefreshToken, error) {
	row := q.db.QueryRow(ctx, getRefreshToken, tokenHash)
	var i RefreshToken
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.TokenHash,
		&i.ExpiresAt,
		&i.RevokedAt,
		&i.CreatedAt,
		&i.FamilyID,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
select id, name, username, role, pin_hash, password_hash, is_active, created_at, updated_at, company_id, recovery_email, must_change_password, pin_lookup from users where id = $1
`

// RLS acota a la empresa del tenant activo (GUC app.company_id); no hace falta filtrar por company_id aquí.
func (q *Queries) GetUserByID(ctx context.Context, id int64) (User, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Role,
		&i.PinHash,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.RecoveryEmail,
		&i.MustChangePassword,
		&i.PinLookup,
	)
	return i, err
}

const getUserByUsername = `-- name: GetUserByUsername :one
select id, name, username, role, pin_hash, password_hash, is_active, created_at, updated_at, company_id, recovery_email, must_change_password, pin_lookup from users where username = $1 and is_active
`

func (q *Queries) GetUserByUsername(ctx context.Context, username *string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByUsername, username)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Role,
		&i.PinHash,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.RecoveryEmail,
		&i.MustChangePassword,
		&i.PinLookup,
	)
	return i, err
}

const getUserPreference = `-- name: GetUserPreference :one
select value from user_preferences where user_id = $1 and key = $2
`

type GetUserPreferenceParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
}

func (q *Queries) GetUserPreference(ctx context.Context, arg GetUserPreferenceParams) ([]byte, error) {
	row := q.db.QueryRow(ctx, getUserPreference, arg.UserID, arg.Key)
	var value []byte
	err := row.Scan(&value)
	return value, err
}

const listActiveUsers = `-- name: ListActiveUsers :many
select id, name, username, role, pin_hash, password_hash, is_active, created_at, updated_at, company_id, recovery_email, must_change_password, pin_lookup from users where is_active order by name
`

func (q *Queries) ListActiveUsers(ctx context.Context) ([]User, error) {
	rows, err := q.db.Query(ctx, listActiveUsers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Username,
			&i.Role,
			&i.PinHash,
			&i.PasswordHash,
			&i.IsActive,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.CompanyID,
			&i.RecoveryEmail,
			&i.MustChangePassword,
			&i.PinLookup,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeRefreshFamily = `-- name: RevokeRefreshFamily :exec
update refresh_tokens set revoked_at = now()
where family_id = $1 and family_id is not null and revoked_at is null
`

// La cadena que nació en UN login, y solo esa.
//
// Es el castigo del reuso, y la constitución lo pide así: revocar por usuario tumbaba también la
// tableta del compañero, que en este negocio comparte cuenta. Un robo en la barra dejaba a la caja
// pidiendo contraseña con el cliente enfrente.
//
// company_id no se nombra: RLS ya lo aplica, y sqlc no ve las columnas que 0023 agregó con
// EXECUTE format().
func (q *Queries) RevokeRefreshFamily(ctx context.Context, familyID *uuid.UUID) error {
	_, err := q.db.Exec(ctx, revokeRefreshFamily, familyID)
	return err
}

const revokeRefreshToken = `-- name: RevokeRefreshToken :exec
update refresh_tokens set revoked_at = now() where token_hash = $1
`

func (q *Queries) RevokeRefreshToken(ctx context.Context, tokenHash string) error {
	_, err := q.db.Exec(ctx, revokeRefreshToken, tokenHash)
	return err
}

const revokeRefreshTokenIfActive = `-- name: RevokeRefreshTokenIfActive :execrows
update refresh_tokens set revoked_at = now() where token_hash = $1 and revoked_at is null
`

// Rotación atómica: revoca solo si sigue activo. RowsAffected=0 => otro request ya lo
// revocó (rotación concurrente o reuso). Cierra el TOCTOU del rotate read-then-revoke.
func (q *Queries) RevokeRefreshTokenIfActive(ctx context.Context, tokenHash string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeRefreshTokenIfActive, tokenHash)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const revokeUserRefreshTokens = `-- name: RevokeUserRefreshTokens :exec
update refresh_tokens set revoked_at = now() where user_id = $1 and revoked_at is null
`

// TODAS las sesiones de una persona. Es lo correcto para un cambio de contraseña: si la contraseña
// cambió, nada de lo emitido con la anterior debe seguir sirviendo.
//
// NO es lo correcto para un reuso: ahí se revoca solo la familia comprometida (ver la de abajo).
func (q *Queries) RevokeUserRefreshTokens(ctx context.Context, userID int64) error {
	_, err := q.db.Exec(ctx, revokeUserRefreshTokens, userID)
	return err
}

const setUserPassword = `-- name: SetUserPassword :exec
update users set password_hash = $2, must_change_password = $3, updated_at = now() where id = $1
`

type SetUserPasswordParams struct {
	ID                 int64   `json:"id"`
	PasswordHash       *string `json:"password_hash"`
	MustChangePassword bool    `json:"must_change_password"`
}

// must_change_password lo fija quien llama (true tras reset por admin, false en cambio propio).
func (q *Queries) SetUserPassword(ctx context.Context, arg SetUserPasswordParams) error {
	_, err := q.db.Exec(ctx, setUserPassword, arg.ID, arg.PasswordHash, arg.MustChangePassword)
	return err
}

const setUserPin = `-- name: SetUserPin :exec
update users set pin_hash = $2, pin_lookup = $3, updated_at = now() where id = $1
`

type SetUserPinParams struct {
	ID        int64   `json:"id"`
	PinHash   *string `json:"pin_hash"`
	PinLookup *string `json:"pin_lookup"`
}

func (q *Queries) SetUserPin(ctx context.Context, arg SetUserPinParams) error {
	_, err := q.db.Exec(ctx, setUserPin, arg.ID, arg.PinHash, arg.PinLookup)
	return err
}

const setUserPreference = `-- name: SetUserPreference :exec
insert into user_preferences (user_id, key, value, updated_at)
values ($1, $2, $3, now())
on conflict (user_id, key) do update set value = excluded.value, updated_at = now()
`

type SetUserPreferenceParams struct {
	UserID int64  `json:"user_id"`
	Key    string `json:"key"`
	Value  []byte `json:"value"`
}

func (q *Queries) SetUserPreference(ctx context.Context, arg SetUserPreferenceParams) error {
	_, err := q.db.Exec(ctx, setUserPreference, arg.UserID, arg.Key, arg.Value)
	return err
}

const setUserRecoveryEmail = `-- name: SetUserRecoveryEmail :exec
update users set recovery_email = $2, updated_at = now() where id = $1
`

type SetUserRecoveryEmailParams struct {
	ID            int64   `json:"id"`
	RecoveryEmail *string `json:"recovery_email"`
}

func (q *Queries) SetUserRecoveryEmail(ctx context.Context, arg SetUserRecoveryEmailParams) error {
	_, err := q.db.Exec(ctx, setUserRecoveryEmail, arg.ID, arg.RecoveryEmail)
	return err
}

const setUserSecretsByUsername = `-- name: SetUserSecretsByUsername :execrows
update users set password_hash = $2, pin_hash = $3, pin_lookup = $4, is_active = true, updated_at = now()
where username = $1
`

type SetUserSecretsByUsernameParams struct {
	Username     *string `json:"username"`
	PasswordHash *string `json:"password_hash"`
	PinHash      *string `json:"pin_hash"`
	PinLookup    *string `json:"pin_lookup"`
}

// La huella va JUNTO al hash, siempre. Reiniciar el admin dejaba el pin_hash nuevo y la huella
// vieja, así que el índice único que impide dos PINs iguales seguía comparando contra un PIN que
// ya no existe, y con el modo de solo-PIN encendido el admin no podía desbloquear con el suyo.
func (q *Queries) SetUserSecretsByUsername(ctx context.Context, arg SetUserSecretsByUsernameParams) (int64, error) {
	result, err := q.db.Exec(ctx, setUserSecretsByUsername,
		arg.Username,
		arg.PasswordHash,
		arg.PinHash,
		arg.PinLookup,
	)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const tomarSesionDeEstacion = `-- name: TomarSesionDeEstacion :one
update refresh_tokens set revoked_at = now()
where token_hash = $1 and revoked_at is null and expires_at > $2 and user_id = $3
returning expires_at
`

type TomarSesionDeEstacionParams struct {
	TokenHash string    `json:"token_hash"`
	ExpiresAt time.Time `json:"expires_at"`
	UserID    int64     `json:"user_id"`
}

// Toma la sesión que la estación viene presentando: la revoca y devuelve su vencimiento.
//
// REVOCAR Y LEER EN LA MISMA SENTENCIA, no un select y luego un update. Separados, dos relevos con
// la misma cookie ven las dos el token vivo en la lectura, las dos emiten sesión, y el update de la
// perdedora toca cero filas sin error: de un refresh salen dos vivos, y cerrar sesión revoca uno y
// deja el otro. Es el estado que motivó la feature — un usuario de producción con 4 sesiones vivas.
//
// Sin filas = no hay sesión viva en esta estación, y ahí el relevo se niega: emitir un plazo nuevo
// sería renovar el turno entero a cambio de un PIN.
//
// Solo esta sesión. Revocar todas las de la persona tumbaba sus otras tabletas: entregar la
// estación 1 dejaba al compañero de la estación 2 con "terminó el turno" a media venta.
//
// Y tiene que ser de QUIEN VIENE OPERANDO la estación ($3, que sale del token de acceso): sin ese
// predicado servía cualquier refresh vivo de la empresa, así que un token filtrado por otro lado
// —un respaldo, un log— tomaba la estación ajena, heredaba su reloj y se la revocaba de paso.
func (q *Queries) TomarSesionDeEstacion(ctx context.Context, arg TomarSesionDeEstacionParams) (time.Time, error) {
	row := q.db.QueryRow(ctx, tomarSesionDeEstacion, arg.TokenHash, arg.ExpiresAt, arg.UserID)
	var expires_at time.Time
	err := row.Scan(&expires_at)
	return expires_at, err
}

const unlockCandidates = `-- name: UnlockCandidates :many
select id, name from users
where is_active and pin_hash is not null
order by name
`

type UnlockCandidatesRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// Quiénes pueden desbloquear una estación con su PIN.
//
// SOLO id y nombre: esta lista se pinta en una tableta a la vista del público, así que el correo,
// el rol y el teléfono no tienen por qué salir del servidor.
//
// Solo activos y CON PIN: quien no lo tiene configurado no entraría aunque lo tocara, y ofrecerlo
// sería mandarlo a un callejón. Esa persona entra con usuario y contraseña, que sigue funcionando.
func (q *Queries) UnlockCandidates(ctx context.Context) ([]UnlockCandidatesRow, error) {
	rows, err := q.db.Query(ctx, unlockCandidates)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []UnlockCandidatesRow{}
	for rows.Next() {
		var i UnlockCandidatesRow
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
update users
set name = $2, role = $3, is_active = $4, recovery_email = $5, updated_at = now()
where id = $1
returning id, name, username, role, pin_hash, password_hash, is_active, created_at, updated_at, company_id, recovery_email, must_change_password, pin_lookup
`

type UpdateUserParams struct {
	ID            int64   `json:"id"`
	Name          string  `json:"name"`
	Role          string  `json:"role"`
	IsActive      bool    `json:"is_active"`
	RecoveryEmail *string `json:"recovery_email"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.Name,
		arg.Role,
		arg.IsActive,
		arg.RecoveryEmail,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Username,
		&i.Role,
		&i.PinHash,
		&i.PasswordHash,
		&i.IsActive,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CompanyID,
		&i.RecoveryEmail,
		&i.MustChangePassword,
		&i.PinLookup,
	)
	return i, err
}

const userByPinLookup = `-- name: UserByPinLookup :one
select id, name from users
where is_active and pin_lookup = $1
`

type UserByPinLookupRow struct {
	ID   int64  `json:"id"`
	Name string `json:"name"`
}

// De quién es este PIN. Solo tiene sentido con el modo de solo-PIN, donde el PIN identifica.
func (q *Queries) UserByPinLookup(ctx context.Context, pinLookup *string) (UserByPinLookupRow, error) {
	row := q.db.QueryRow(ctx, userByPinLookup, pinLookup)
	var i UserByPinLookupRow
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
