// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: uso.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countActiveUsersByRole = `-- name: CountActiveUsersByRole :one
select count(*)::bigint from users where role = $1 and is_active
`

// Cuántas personas activas tiene ese rol en la empresa del request (RLS acota la consulta).
//
// Es lo que decide si el rol se guarda o se deja en blanco: con menos de dos, escribirlo es escribir
// un nombre. Se pregunta al ESCRIBIR porque es el único momento en que la decisión no se puede
// deshacer — y porque quien lee no podría: la consola no tiene permiso sobre `users`.
func (q *Queries) CountActiveUsersByRole(ctx context.Context, role string) (int64, error) {
	row := q.db.QueryRow(ctx, countActiveUsersByRole, role)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const deleteOldUsageDaily = `-- name: DeleteOldUsageDaily :execrows
delete from usage_daily where day < current_date - ($1::int * interval '1 day')
`

// Y el del agregado, con su propia retención (más larga: es lo que se mira).
func (q *Queries) DeleteOldUsageDaily(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldUsageDaily, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteOldUsageEvents = `-- name: DeleteOldUsageEvents :execrows
delete from usage_events where occurred_at < now() - ($1::int * interval '1 day')
`

// El recorte del grano fino. Corre con conexión de DUEÑO: el rol de la aplicación está bajo RLS y
// solo borraría lo de su empresa, dejando el recorte a medias sin que nada fallara.
func (q *Queries) DeleteOldUsageEvents(ctx context.Context, dollar_1 int32) (int64, error) {
	result, err := q.db.Exec(ctx, deleteOldUsageEvents, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertUsageEvent = `-- name: InsertUsageEvent :exec

insert into usage_events (screen, action, role)
values ($1, $2, $3)
`

type InsertUsageEventParams struct {
	Screen string    `json:"screen"`
	Action *string   `json:"action"`
	Role   *UserRole `json:"role"`
}

// EL USO DEL SISTEMA (spec 017).
//
// Dos caminos que no se cruzan: el POS ESCRIBE (las tres primeras, con el rol de la aplicación) y
// la consola LEE (la última, con el rol de plataforma, que no tiene permiso sobre el grano fino).
// El grano fino, un hecho por fila. Sin quién lo hizo: la tabla no tiene esa columna.
//
// `detail` NO se recibe de nadie: existe para las coordenadas del futuro (FR-013) y se queda nulo.
// Aceptarlo desde el cuerpo del POST convertiría esa puerta en un campo libre.
//
// ponytail: una fila por evento, hasta 50 por lote y por transacción. A 3 pedidos/día medidos (y
// 100 en el escenario de diseño) son milisegundos; si algún día un cliente mete miles de eventos
// por minuto, esto pasa a un `copy`.
func (q *Queries) InsertUsageEvent(ctx context.Context, arg InsertUsageEventParams) error {
	_, err := q.db.Exec(ctx, insertUsageEvent, arg.Screen, arg.Action, arg.Role)
	return err
}

const sumUsageForMap = `-- name: SumUsageForMap :many
select screen,
       action,
       role,
       sum(hits)::bigint as veces
from usage_daily
where day between $1::date and $2::date
  and ($3::bigint is null or company_id = $3::bigint)
group by screen, action, role
order by screen, action nulls first, role nulls first
`

type SumUsageForMapParams struct {
	Desde   pgtype.Date `json:"desde"`
	Hasta   pgtype.Date `json:"hasta"`
	Company *int64      `json:"company"`
}

type SumUsageForMapRow struct {
	Screen string    `json:"screen"`
	Action *string   `json:"action"`
	Role   *UserRole `json:"role"`
	Veces  int64     `json:"veces"`
}

// Lo que lee la consola: el conteo del periodo por pantalla, acción y rol.
//
// Suma en la base y no en Go: son decenas de filas por día y por empresa, pero un año de 13 meses
// por varias empresas son decenas de miles, y no hay razón para moverlas.
//
// `company` nulo = todas las empresas juntas (FR-008). Lo que hace posible ese "todas" es la
// política `plataforma_lee_todo_el_uso`; sin ella esta misma consulta devuelve una empresa, o cero.
func (q *Queries) SumUsageForMap(ctx context.Context, arg SumUsageForMapParams) ([]SumUsageForMapRow, error) {
	rows, err := q.db.Query(ctx, sumUsageForMap, arg.Desde, arg.Hasta, arg.Company)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SumUsageForMapRow{}
	for rows.Next() {
		var i SumUsageForMapRow
		if err := rows.Scan(
			&i.Screen,
			&i.Action,
			&i.Role,
			&i.Veces,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertUsageDaily = `-- name: UpsertUsageDaily :exec
insert into usage_daily (day, screen, action, role, hits)
values (current_date, $1, $2, $3, $4)
on conflict on constraint usage_daily_llave
do update set hits = usage_daily.hits + excluded.hits
`

type UpsertUsageDailyParams struct {
	Screen string    `json:"screen"`
	Action *string   `json:"action"`
	Role   *UserRole `json:"role"`
	Hits   int64     `json:"hits"`
}

// El conteo del día. Recibe el lote YA PRE-AGREGADO: suma `excluded.hits`, no `+1`.
//
// Cada `update` deja la versión vieja de la fila muerta, y estas filas son pocas y calientes:
// medido, 135 filas con 2,000 incrementos de a uno pasan de 64 kB a 232 kB antes de que autovacuum
// llegue. Pre-agregar convierte hasta 50 escrituras físicas en una.
func (q *Queries) UpsertUsageDaily(ctx context.Context, arg UpsertUsageDailyParams) error {
	_, err := q.db.Exec(ctx, upsertUsageDaily,
		arg.Screen,
		arg.Action,
		arg.Role,
		arg.Hits,
	)
	return err
}
