-- +goose Up
-- Revoca TODAS las sesiones vivas: las que se emitieron antes de que el turno durara un turno.
--
-- Hasta 0050 el refresh se emitía con 30 días fijos. Esas credenciales siguen en la base con su
-- vencimiento viejo, y el arreglo de la rotación las CONSERVA a propósito —rotar no debe correr el
-- fin del turno hacia adelante—, así que sin esto una tableta que ya estaba dentro se quedaría con
-- un mes de sesión y el límite de horas no aplicaría a nadie hasta que cada una volviera a entrar.
-- En producción hay una con cuatro sesiones vivas, la más vieja de tres días antes.
--
-- El costo es que todos vuelven a entrar UNA vez, con usuario y contraseña. Se hace en la
-- migración y no a mano porque a mano se olvida, y lo que se olvida aquí es la feature entera.
--
-- No se borran las filas: el histórico de sesiones es lo que deja ver un reuso más adelante.
--
-- CADUCA, no revoca, y la diferencia vale el POS entero. `ClassifyRefresh` mira `revoked` ANTES que
-- `expiresAt`: una credencial REVOCADA que reaparece es, por definición, un robo, y el castigo del
-- robo es `RevokeUserRefreshTokens`, que revoca por `user_id` — todas las sesiones de esa persona,
-- en todas las tabletas, no solo la cadena comprometida.
--
-- En este negocio dos estaciones comparten cuenta (lo dice el comentario de 0050). Revocando en
-- bloque: la tableta A entra con contraseña, la B despierta con su cookie vieja y le revoca la
-- sesión a A, A refresca y le revoca la sesión a B. Un ping-pong de quince minutos que no converge
-- mientras las dos se usen — contraseña a media operación, para siempre.
--
-- Caducar dice lo que de verdad pasó: el turno terminó. Sale un 401 limpio, sin respuesta de robo y
-- sin tocar a la otra estación. El costo buscado —todos vuelven a entrar UNA vez— es idéntico.
update refresh_tokens set expires_at = now() where revoked_at is null and expires_at > now();

-- +goose Down
-- Sin vuelta atrás, y no es un descuido.
--
-- No se guarda el vencimiento anterior de cada credencial, así que devolverlo sería inventarlo — y
-- las que ya estaban caducadas por su propio turno no se distinguen de las que caducó esta
-- migración. El rollback es no hacer nada: quien vuelva a entrar tendrá su sesión nueva.
select 1;
